---
title: "Affiliated Projects"
listing:
  template: templates/projects.ejs
  contents: affiliated
  sort: "order"
  image-placeholder: "images/logo.png"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: false
---

There are many instances where researchers might benefit from a formal and flexible affiliation with the Psychological Science Accelerator (PSA). For example, researchers seeking funding may need to deviate from the typical PSA procedures in order to submit a convincing grant proposal. To support these sorts of projects, the PSA is piloting a PSA Affiliation Project initiative.

In general, PSA-affiliated projects are expected to follow four rules:

1) Be led by at least one member of the PSA who has agreed to abide by the PSA Code of Conduct.
2) Follow the five PSA Core Principles: Diversity and Inclusion, Decentralized Authority, Transparency, Rigor, and Openness to Transparency (see the PSA Vision Plan for more information about our principles. Alternatively, the project leads should transparently articulate why those principles are not followed).
3) Provide quarterly updates on project progress (e.g., how PSA core principles are being upheld).
4) Provide a net gain (e.g., funding or other strategic gains) for the PSA.

The form will be reviewed by the Associate Directors of the PSA to determine eligibility for the PSA Affiliated Project initiative. We ask for up to 6 weeks to review these applications, but can consider exceptions on an as-needed basis. Proposals are approved if 75% of Associate Directors vote to support it. By default, the Associate Directors should ask for feedback from the PSA network before approving an affiliated project proposal (e.g., by posting a copy of this completed form to the general channel of the PSA slack), and Associate Directors may consult PSA Committees on an as-needed basis.

Please use this form: [Affiliated Form](https://docs.google.com/document/d/1QBl_LZEKarBBBdkEiTqp-W3u9IpE4SoZr5OoUwV9LoY/edit?tab=t.0) and send it in a word document format to [directors at psysciacc dot org](mailto:directors@psysciacc.org) for consideration. 
