---
title: "Previous Conferences"
page-layout: full
---

In 2020, the PSA created the first conference focused on big team science. In [2020](https://psysciacc.org/psacon2020-videos/) and [2021](https://psysciacc.org/psacon2021-videos/), this conference was called PSA-CON and largely focused on projects conducted by members of the PSA.

By 2022, it was clear that big team science had proliferated far beyond our community. Thus, we did what we do best: collaborated! Working with the [ManyBabies](https://manybabies.github.io/) and [ManyPrimates](https://manyprimates.github.io/) consortia, we re-focused the conference on all things big team science and gave it a new name: the [Big Team Science Conference](https://bigteamscienceconference.github.io/) (BTS-CON). The inaugural 2022 BTS-CON had over 450 registrants and 50 sessions. With continued support, we hope that this conference will continue to be an inaugural event where people can come together to discuss the challenges, benefits, successes, and future directions of big team science. 

Interested in attending the next BTS-CON? Check out the [conference page](https://bigteamscienceconference.github.io/)!
