---
title: "PSA004: True Belief"
doi: 10.31234/osf.io/zeux9
osf: x978m
categories:
  - knowledge
  - multi-language
personnel:
  proposers:
    - Braeden Hall 
    - Jordan Wagge 
  pm: Jordan Wagge 
  methodology: Braeden Hall
  data: Dan Dunleavy
  translation: Jan Philipp Röer
  ethics: Erica Musser
---

According to the Justified True Belief (JTB) account of knowledge, a person’s ability to know something is defined by having a belief that is both justified and true (i.e., knowledge is justified true belief). However, this account fails to consider the role of luck. In 1963, Gettier argued that JTB is insufficient because it does not account for certain situations, called Gettier cases, wherein a person is justified for believing something true but only because of luck. It is unclear whether lay people’s intuitions about knowledge lead them to agree with Gettier, such that lay people believe that individuals in these cases lack knowledge (referred to as Gettier intuitions). We attempt to provide a robust estimate of the Gettier intuition effect size by replicating Turri and colleagues’ (2015) Experiment 1. The Collaboration Replications and Education Project (CREP) selected this study for replication based on its undergraduate appeal, feasibility, and pedagogical value. However, in light of some inconsistent results, suboptimal designs, and inconsistent evidence for cultural variation (e.g., Machery et al., 2015; Nagel, et al., 2013; Seyedsayamdost et al., 2015; Starman & Friedman, 2012; Weinberg et al., 2001), the improved methodology of Turri et al. (2015) make it an important study to replicate cross-culturally. Therefore, we propose a multisite Collaboration preregistered replication of Turri and colleague’s (2015) Experiment 1 (35 labs from 14 countries across 4 continents signed up at time of submission; expected minimum N = 1,500). Results of this study are expected to provide a clearer picture of the Gettier intuition effect size, lay people’s theory and practice of knowledge, and potentially cross-cultural similarities and differences.

Hall, B. F., Schmidt, K., Wagge, J. R., Lewis, S. C., Weissgerber, S. C., Kiunke, F., … Buchanan, E. M. (2018, October 15). Registered Replication Report: A Large Multilab Cross-Cultural Conceptual Replication of Turri, Buckwalter, & Blouw (2015). <https://doi.org/10.31234/osf.io/zeux9>
