---
title: "Timeline for late 2017 and early 2018"
author: "Chris Chartier"
date: 2017-10-25
---

Here is a brief run-down of our timeline for the remainder of 2017 and
early 2018. Currently happening: Review the 8 (quite interesting and
promising) submissions that we received in response to our first call
for studies. November 2017: Make final selections for which studies to
include in our initial data collection sessions. December 2017: Finalize
all data collection materials, protocols, and data analytic plans for
selected studies in collaboration with the proposing authors of the
selected studies. December 2017: Pair data collection teams with
selected studies based on power analyses, match between lab resources
and the demands of the selected studies, and the overall data collection
capacity of the network. Early 2018: Submit our commentary paper
introducing the Psychology Science Accelerator's mission, core
principles, policies, promise, and likely challenges. Early 2018:
Commence data collection on our first empirical projects! Early 2018:
Seek funding to support general development of the Accelerator and to
facilitate data collection for resource intensive studies. 2018 and
forever onward: Re-evaluate our policies and procedures based on public
feedback and lessons learned from our first round of study selection,
data collection team matching, and the logistics of early data
collection. 2018 and forever onward: Review and accept more study
submissions and collect LOTS of data. 2018 and forever onward: Recruit
more researchers all around the world to contribute in any way they can
to the Psychological Science Accelerator! This, of course, is the
optimistic version :)

