---
title: "PSA Updates for October 15th: Accelerated CREP Preprint, Code of Conduct, and New Studies Being Announced Soon"
author: "Chris Chartier"
date: 2018-10-15
categories:
  - mailchimp backup
---

Accelerators,

We have 4 updates to share today.

1. The Accelerated CREP project will be submitted as a Stage 1 RRR to AMPPS on October 22nd. We have just posted a preprint here (https://psyarxiv.com/zeux9) , a blog post to recruit additional labs here (https://psysciacc.org/news/2018-10-15_update-on-the-accelerated-crep-registered-replication-report-submission-coming-soon-more-labs-welcome-to-join.html) , and a twitter thread to spread the word here (https://twitter.com/PsySciAcc/status/1051865123147718664). Labs can still join this project at Stage 1 if they take action over the next week. Please share this news in your networks and consider joining this project if you have a student who would be a good fit. Thank you to Braeden Hall, Jordan Wagge, and Jon Grahe for their leadership on this project.

2. Our first study (face perception around the world) is under review at NHB as a Stage 1 RR at the moment, but we are simultaneously attempting to recruit a few additional labs in Africa, Central America, Mexico, the Middle East, and Scandinavia to strengthen the project. You can read more about it, and sign up, here (https://psysciacc.org/news/2018-10-09_psa-face-rating-study-last-call-for-labs-in-africa-central-america-mexico-the-middle-east-and-scandinavia.html) .

3. The leadership team has been hard at work drafting a range of PSA-wide policy documents. All will be shared with the full network for a 1 week feedback period, followed by a round of edits based on that feedback, and ultimately a full network vote to officially ratify them as PSA policy. The first document to go through this process is our Code of Conduct. We welcome your comments on this draft document (https://docs.google.com/document/d/1cVao6M2J_Il2K7vpYNQqUU4iX_UwlezvAZrQabdwc_A/edit#) through October 22nd.

4. New PSA study selections will be announced this week! Be on the lookout for the news here and on the blog and twitter.

Thank you for all of your hard work accelerating psychological science!
