---
title: "PSA Updates for October 22nd: a newly selected study(!), a draft psa membership policy, and an invite to work on theory development in psych"
author: "Chris Chartier"
date: 2018-10-22
categories:
  - mailchimp backup
---

Accelerators,

First, welcome to all those who have recently signed up for the PSA (we have had 36 sign-ups in October alone)! I have 3 updates today:

1. The PSA has selected its next study! “A Large-Scale, Multi-Site Examination of Stereotype Threat Across Varying Operationalizations” was submitted by Patrick S. Forscher (University of Arkansas), Valerie Jones Taylor (Lehigh University), Neil A. Lewis, Jr. (Cornell University), and Daniel Cavagnaro (California State Fullerton). Congrats to them! You can read about the study, and find relevant links (to the proposal, sign-up form, etc.) in this blog post (https://psysciacc.org/news/2018-10-19_a-large-scale-multi-site-examination-of-stereotype-threat-across-varying-operationalizations-a-newly-selected-accelerator-study.html). Thank you to everyone who contributed to reviewing and evaluating submissions from our current round of proposals. Three other submissions received "revise and resubmit" decisions, so be on the lookout for more study selection announcements in the coming months!

2. Thank you for the comments and suggestions to the Code of Conduct document (https://docs.google.com/document/d/1cVao6M2J_Il2K7vpYNQqUU4iX_UwlezvAZrQabdwc_A/edit#). I'll prepare the document for a full PSA vote soon. In the meantime feel free to continue to make suggestions if you haven't done so already. The next PSA-wide policy document up for feedback and consideration is our Membership Policy (https://docs.google.com/document/d/18_od1Ywo3iJsn78HEKbb9SyQYF8-_Lw2FG3aHiiav4E/edit). What does it mean to be a member of the PSA? Please provide your comments over the next week. I will then edit accordingly and put the policy up for a vote.

3. Erich Witte is interested in forming a group focused on theory development in psychology and would like to welcome PSA members to get involved. You can read the full text of his message, and find his contact info if you are interested, pasted below.

Thank you for all you have done and continue to do to accelerate psychological science.

From Erich:

Dear colleagues,

We all are convinced that our science needs a push forward. Empirical testing is one part to be improved, the more fundamental part, however, is the theoretical development. A progressive research program needs empirical point-predictions:

https://www.frontiersin.org/articles/10.3389/fpsyg.2017.01847/full
https://www.frontiersin.org/articles/10.3389/fpsyg.2018.00460/full

In general, our theories are only able to predict qualitative deviations in one direction. It is time now to create an innovative group of researchers in Theoretical Psychology to improve the existing theoretical constructs.

My idea is to find a small group of theoreticians who enter such a group with her own theory or an admired theoretical concept which should be developed so that point-hypotheses can be deduced.
This concrete process of construction will give us an impression what a good theory is about and how can we reach this aim.

If you are interested, please contact me at witte_e_h@uni-hamburg.de (mailto:witte_e_h@uni-hamburg.de)

Best wishes,
Erich H. Witte
