---
title: "A few PSA updates for July 30th"
author: "Chris Chartier"
date: 2018-07-30
categories:
  - mailchimp backup
---

Hello!

I have just a few PSA updates for everyone today.

First, we got some good news recently. Our introductory paper has been accepted for publication at Advances in Methods and Practices in Psychological Science! This is the first publication to come out fo the PSA, and will introduce a broad readership to what we're up to. Thank you to all of the co-authors, and especially to Hannah Moshontz for leading this effort. You can find the most recent version of the ms here (https://psyarxiv.com/785qu/) .

Second, a member of the PSA, Balazs Aczel, has been working on a collaboration platform to help researchers connect for collaborations much smaller than the very-large PSA projects we're all working on. It is quite similar to StudySwap, but has some very nice searching and filtering functions. To see if there is community support for such a platform, and perhaps to show serious interest from our community when seeking funding for it's development, Balazs asks PSA members to fill out this very brief survey (https://docs.google.com/forms/d/e/1FAIpQLSdO2QDTnLx2NU3TA3bXJwG4hS-Un0jbMXsAO3V7fE74MV7ADA/viewform) here. Thank you in advance for anyone who takes a few minutes to help out a fellow member of the PSA community!

Finally, we are making very nice progress on our empirical projects in the pipeline. Study 1 received a Revise and Resubmit decision from Nature Human Behavior. Ben Jones, Lisa DeBruine, and Jess Flake are revising it now. Studies 2 & 3 are progressing and being prepared for Registered Reports submissions. Thank you to Curtis Phills, Sau-chin Chen, Zoltan Kekecs, and Anna Szabelska for their efforts leading the work on these manuscripts! The Accelerated CREP submission is also being revised after receiving some very excellent and positive feedback from two editors at AMPPS. Thank you to Braeden Hall and Jordan Wagge for all their work on this project!

More soon!
