---
title: "PSA Updates for 6/18/2018: SIPS, Policy Documents, and Study Selection"
author: "Chris Chartier"
date: 2018-06-18
categories:
  - mailchimp backup
---

Accelerators,

I write today with a few updates, reminders, and small requests for input and feedback:
1. Many of us will be attending the 3^rd meeting of the Society for the Improvement of Psychological Science, in Michigan, this Sunday through next Tuesday (50 of us to be exact…20% of the conference attendees!). We will have several PSA working meetings as well as social get-togethers. For those in attendance, check out this PSA schedule for SIPS (https://docs.google.com/spreadsheets/d/1SSzySIC51hU2uERR4_wx09bxWZjdxD0XgTe-POIasBc/edit#gid=0) to see our plans and to suggest working meetings. Feel free to drop by at any time listed on the schedule in either green or pink (also listed as “open” or with the working meeting title for our color-blind friends). For those who can’t make it, we will keep note of some of our discussions and plans for working meetings in this folder (https://drive.google.com/drive/u/0/folders/1dVaaHhZFb3l5zEnIxT0ijQlYmfZrOOfU). Feel free to follow along and contribute. In addition, I’d be happy to meet and chat with anyone in the PSA via google hangouts during the
conference. Just let me know via email at cchartie@ashland.edu (mailto:cchartie@ashland.edu) .
2. Our next round of study submissions are due on Wednesday. This will begin an exciting new period of submission evaluation and selection. First, the Study Selection Committee will take two weeks to conduct feasibility reviews. Next, peer reviewers (selected by the leadership team) will review each submission. Concurrently, we will ask for quantitative ratings of each submission from the full PSA network. Finally, the Study Selection Committee will make final decisions on which studies to accept, reject, or invite in revised form in future calls for studies.
3. Two working groups have made substantial progress drafting policy documents that are very important to the future of the PSA. Patrick Forscher has lead a team in drafting our data management policies (https://docs.google.com/document/d/1NlL2_0RxB8W4ETKWQa28ZFOcXJdfgHEVpkOF366Ane8/edit?ts=5b27db5a#heading=h.bia4l1ovvkzg). Peder Isager has led a team in drafting more formal guidelines for PSA peer reviewers (https://docs.google.com/document/d/1r-CXP4onzn8In6NIcatRXQKo14lKGgJNvduokzNXD28/edit?ts=5b266154). Please review these documents and provide feedback and suggestions on the google documents via comments. Our hope is that both will documents eventually evolve into manuscripts to be submitted to peer reviewed journal (after being reformatted and fully contextualized), so be sure to document your contributions to inform later authorship decisions.
4. Much progress has also been made on the various publications and projects already in our pipeline. We are revising our general introductory manuscript, which received a very favorable set of reviews, and a revise and resubmit decision, from Advances in Methods and Practices in Psychological Science. We are waiting for peer reviews and an editorial decision on the Stage 1 Registered Report submission for study 1 at Nature Human Behavior. The lead authors of Study 2, Study 3, and the Accelerated CREP are all preparing RR manuscripts for submission in the coming months. All contributors who have signed up for those projects will be looped into the drafting process very soon.
5. Finally, we received a large and impressive pool of applicants for our last Associate Director position. We will be announcing our decision there, restructuring several committees, and selecting our Assistant Directors very soon!

I continue to be humbled by the massive enthusiasm and support of this community. I very much look forward to meeting many of you soon, and continuing to work with all members of the Accelerator!
