---
title: "1 Year Anniversary Coming Up(!) & Some Invitations"
author: "Chris Chartier"
date: 2018-08-20
categories:
  - mailchimp backup
---

Hi Everyone!

Monday will mark the 1 year anniversary of the blog post that started the PSA! (Here's the initial blog post, in case your'e curious (https://christopherchartier.com/2017/08/26/building-a-cern-for-psychological-science/) ). Years from now, I think we will look back with immense gratitude for the researchers who decided to support this fledgling initiative during its first 365 days (YOU!). To commemorate, I plan to post a brief personal story on my own blog, but also post a timeline of progress and achievements on the PSA blog. So, as part of the blog post commemorating our first birthday, I wanted to welcome each of you to send along your own brief (perhaps between 50 and 200 words) personal reflections on what it has been like helping to launch and establish this initiative. I think this would be a great way to celebrate our community, reflect on how much we’ve done this year, and share some positive stories that may help recruit and inspire new members. If you send me your contribution by
the end of the week (the 26^th), I will be able to include it in the blog post to be published on Monday (the 27^th). Also, feel free to join me in drafting the PSA blog post. So much has happened, that I'm sure to miss key events on my own. Here's a google doc link (https://docs.google.com/document/d/11PnMjIQxkefRFyjst8Gz8QqaecSje0lKG4nQfxeKUH0/edit) to the draft document (which is empty now, but hopefully not for long).


A few updates:
-Later this week, you will receive an invitation to check out the 5 study proposals we're currently considering from our most recent round of submissions. They are diverse and exciting! All members of the network will have the opportunity to (although no requirement to) provide feedback on these submissions. Additionally, you can indicate for each submission, should it be selected, if you would be interested in contributing to it. I'm looking forward to hearing what everyone thinks.

-Don’t forget that we’re still cranking away preparing our already-selected empirical projects. You can still sign up for Study 1 (https://psysciacc.org/news/2017-11-08_the-psychological-science-accelerators-first-study.html) , the Study 2 (https://psysciacc.org/news/2018-01-24_new-study-accepted-the-object-orientation-effect.html) /3 (https://psysciacc.org/news/2017-12-05_accepted-for-2018-gendered-social-category-representations.html) bundle, or have your students join the Accelerated CREP (https://psysciacc.org/news/2018-04-08_the-accelerated-crep.html) .

-Finally, a team of Accelerators welcome contributors/co-authors for a paper on code review and error prevention. I have pasted their description of the project below for anyone who is interested!

Thank you all so much for everything you have done and continue to do!

"Psychology has shifted towards demanding greater accuracy. Many researchers are now establishing or revisiting how their lab does research, mostly spurred by replicability and open science concerns, but also increased awareness about an abundance of errors making it through to final publications (e.g., Nuijten et al., 2016 about StatCheck). Psychology researchers however often do not really know how to reduce errors in analysis/code, aside from rather generic recommendations to “slow down” and “be more careful”. We are planning to write an article on code review, borrowing methods from computer science to reduce errors. The proposed manuscript will be a non-technical primer for psychology audience for how to formally conduct code/data review. We believe this would help catch errors before publication, improve accessibility and sharing of data and scripts, and help ease researchers’ nerves about data sharing and thus promote it. Such errors can be consequential, even more so with the newly
established (GDPR) guidelines in Europe.

We invite the PSA members to be a part of the writing of this manuscript, first aimed at psychology in general, but also with the goal of implementing these practices into PSA’s formal policies.
We invite authors for the following tiers:
-Tier 2 authors (providing feedback on first structure, co-authoring different drafts)
-Tier 3 authors (providing feedback on full drafts)

Please get in touch with subject heading “PSA Code Review” if you have any questions and/or if you are interested in participating. Please indicate which tier you are interested in.

All the best, also on behalf of Rick Klein and Hans IJzerman,
Sophia Weissgerber (sophiaweissgerber@gmail.com)"




