---
title: "PSA Updates for November 1st 2018: New Stage 1 Preprints, Crowdfunding for Member Labs, Policies, and Committees in Need of Contributors"
author: "Chris Chartier"
date: 2018-11-01
categories:
  - mailchimp backup
---

Accelerators,

It's been a very busy and productive 10 days since my last update!

1. The Stage 1 RR ms for the "Social Perception of Faces Around the World (https://psyarxiv.com/n26dy) " project is back under review for what really feels like the last round of revisions. Fingers crossed for an in principle acceptance at NHB, and data collection commencement, very soon!

2. Braeden Hall and Jordan Wagge submitted the Stage 1 RR ms for the "Accelerated CREP (https://psyarxiv.com/zeux9) " to AMPPS. We now await peer review!

3. Sau-Chin Chen and Anna Szabelska submitted the Stage 1 RR ms for the "Object Orientation Effects Across 14 Languages (https://psyarxiv.com/t2pjv) " project to Psychonomic Bulletin and Review. We now await peer review!

4. We now have 27 US labs signed up for the "Large-Scale, Multi-Site Examination of Stereotype Threat Across Varying Operationalizations (https://osf.io/d3wbk/) " project, but still welcome labs in the US to join if they have the capacity. Here is the sign-up form (https://docs.google.com/forms/d/e/1FAIpQLScMFuuVepTdSC5Bnwh5nYyRqbYKOF7l3u5pfhBG0IlOHhIffw/viewform) .

5. While we are making slow and steady progress on grant funding and more institutional support, we also initiated a crowdfunding campaign to help support data collection in PSA member labs who need funding in order to contribute to these studies. You can read about it and give if you are so inclined at this blog post (https://christopherchartier.com/2018/10/26/help-accelerate-psychological-science-with-a-donation-to-the-psa/). Thanks to some generous donors we have already raised $1,000! Soon we will create a brief funding request form so that PSA labs who could use this support can apply for it. For now, if you'd like to inquire about these funds you can reply to this email to discuss a funding request.

6. We seek feedback on our draft document outlining our policies for Elections and Appointments for PSA Leadership Team Members (Director, Associate Directors, Assistant Directors) and Committee Members. Please have a look and provide your feedback here (https://docs.google.com/document/d/1aXjXwouFc6wvcyy7IFmEKGL0j2yxzYukyI_YFf6sZtM/edit). You will also notice that several of our committees could still use additional members, particularly the newly formed Training and Funding committees. Please let me know if you are interested in contributing to those committees' activities.

If you have any questions, please do not hesitate to let me know. Thank you for all of your continued enthusiasm and work for the PSA and its projects!

