---
title: "PSA Updates for December 20th 2018: New Study, Policy Vote, Monthly Newsletter"
author: "Chris Chartier"
date: 2018-12-20
categories:
  - mailchimp backup
---

Accelerators,

We now plan to release monthly newsletter updates on PSA activities on the blog. Here is our first installment (https://psysciacc.org/news/2018-12-20_news-from-the-accelerator-december-2018.html) , for December 2018. We hope these newsletters will help all network members get a sense of the "big picture" and have more information about PSA activities that they are not directly involved in. I will always email the full network with newsletter links, but will keep my update emails more brief, and provide more information in the newsletter. I do want to highlight a few key pieces of info today:

-We have selected a new study! Check it out here (https://psysciacc.org/news/2018-12-20_new-psa-study-on-the-universality-of-moral-thinking-cross-cultural-variation-in-the-influence-of-personal-force-and-intention-in-moral-dilemma-judgments.html). Info on lab recruitment and project timeline will be coming soon.

-Our code of conduct is now ratified (thanks for all the votes). You can read it here (https://psysciacc.org/code-of-conduct/) .

-We now call for a vote on our membership policy document (https://docs.google.com/document/d/18_od1Ywo3iJsn78HEKbb9SyQYF8-_Lw2FG3aHiiav4E/edit). Please read it and vote via email by January 15th, 2019 to vote. To vote in favor you can reply to this email with "Yes, I vote in support of this membership policy." To vote against you can reply to this email with "No, I vote against this membership policy." Feel free to provide your criticism/feedback/suggested edits when voting against the policy.

-Finally, we welcome feedback on our draft Personnel, Appointments, and Elections Policy Document (https://docs.google.com/document/d/1aXjXwouFc6wvcyy7IFmEKGL0j2yxzYukyI_YFf6sZtM/edit). Please provide your comments and suggested edits by January 15th, 2019. We will then edit accordingly, and potentially (depending on feedback) put it up for a vote in late January.

In 2017 we introduced the idea of the PSA, recruited nearly 200 labs to the network, and selected our first studies. In 2018 we built on our initial momentum, made substantial headway formalizing how the PSA works, and made exciting progress on several of our studies. A few highlights include publishing our introductory paper (https://psyarxiv.com/785qu/) , securing our first in principle acceptance for the face perception study, submitting two more registered reports (still under review :)), selecting 2 new studies, formalizing our leadership team and committee structure (https://psysciacc.org/people/) , and more than doubling the size of the laboratory network (https://psysciacc.org/map/). Thank you for the countless, and at times thankless hours of work that all of you have contributed to make the PSA a success in 2018.

Here’s to an even more productive and exciting 2019 full of Accelerating Psychological Science!
