---
title: "PSA Updates for July 10th, 2018"
author: "Chris Chartier"
date: 2018-07-10
categories:
  - mailchimp backup
---

Accelerators,

I have a diverse set of exciting and important updates on the PSA. The last few months have been quite active. I think we are really laying the foundation for the long-term success of our initiative!

1. Our introductory paper (https://psyarxiv.com/785qu/) describing the background, policies, procedures, challenges, and benefits of the PSA has now been accepted pending minor revisions at the new APS methods focused journal Advances in Methods and Practices in Psychological Science! We expect to see it in press soon and hope it reaches a wide audience. Congrats to Hannah Moshontz for leading this effort so effectively, and to her 90 or so co-authors for all of their work!

2. Over the last few months we have put considerable time and effort into refining our organizational structure, both to better handle the projects currently in our pipeline, but also to make sure we are well positioned to function efficiently as our network continues to grow and grow (we now have 346 distinct labs involved, from 305 institutions, in 53 countries). We now have 5 Associate Directors working with me to oversee all PSA operations and policy decisions (Dana Basnight-Brown, Felix Cheung, Charlie Ebersole, Hans IJzerman, and Heather Urry), and 11 Assistant Directors who will lead specific committees (official announcements coming soon!). We are seeking up to 9 additional candidates for Assistant Director positions (each committee can have up to 2 Assistant Directors). Please follow this link (https://docs.google.com/forms/d/1_YwnjeWe_NJ6d1EtHlDfZttqUsc_z7onp-KD_vbWrTs/prefill) to see more info on the available positions and to apply.

3. We are getting more serious in our search for funding to support PSA infrastructure, specific empirical projects, and our member labs. For example, we would love to be able to provide small awards to our data collection labs, particularly those with fewer research resources already at their disposal. We have a few irons in the fire, but want to conduct the most comprehensive funding search possible. If you know of funding sources that could support any part of the PSA and its labs, please add your idea, with a link to relevant info, to this google doc (https://docs.google.com/document/d/1yA49hfOA_qk_6hOg84QZMbwMe-INXvcZXK6hEp1XeWk/edit). Thank you!

4. On a related note, to aid in a possible grant application led by Hans IJzerman, we welcome you to complete this brief survey (https://metupsych.qualtrics.com/jfe/form/SV_e8S4y1vt12J6dmd) on which psychological constructs, methods, and tools you would like to see tested in non-WEIRD samples via the PSA. The responses will be used to help shape the eventual grant proposal.

5. We received 5 extremely interesting submissions in response to our last call for studies. The Study Selection Committee are wrapping up their feasibility reviews as we speak. We will be reaching out to peer reviewers soon (thank you to everyone who indicated their willingness to review submissions on our recent google form survey). All members of the network will also be given the opportunity to provide a brief assessment of the strength of each submission, and their in principle willingness to join each project should it be selected, so be on the lookout for that in the next week or so.

6. Preparations for our first 4 empirical studies are moving steadily along. Study 1 (Faces) is still under review as a stage 1 RR at Nature Human Behaviour. We hope to hear back soon and begin collecting data ASAP. Studies 2 (Objects) and 3 (Categories) are still being piloted and stage 1 RR manuscripts are in prep. Finally, the Accelerated CREP cleared an initial editorial round at AMPPS, and they have welcomed us to submit a stage 1 RR manuscript, which is also in prep and should be submitted in the next month. Please email me at the PSA account (psysciaccelerator@gmail.com (mailto:psysciaccelerator@gmail.com) ) if you would like any more info about these projects.

That’s all for now! Exciting times! Thank you for your continued work (and patience) as we make slow but steady progress on many fronts!
