---
title: "Our intro paper has been published, and several other fun updates!"
author: "Chris Chartier"
date: 2018-10-01
categories:
  - mailchimp backup
---

Accelerators,

I have a few exciting updates to share today:

1. Our introductory paper was published online at Advances in Methods and Practices in Psychological Science today! This is the first publication to come out of the PSA, and is a moment we can all celebrate together. Please share the paper with potentially interested colleagues. Here is the APS link (http://journals.sagepub.com/eprint/7KCGDCqWiRfGfrEnjKbs/full) , and here is the preprint (https://psyarxiv.com/785qu/) .

2. The Stage 1 Registered Report (peer review prior to data collection) manuscript for our first study has been revised (by Ben Jones, Lisa DeBruine, and Jess Flake) and resubmitted to Nature Human Behaviour. Here is the preprint (https://psyarxiv.com/n26dy). Fingers crossed for good news so we can begin data collection soon!

3. We have finalized our new committee list and have appointed our initial set of Assistant Directors. Thank you to all who applied, and congratulations to those selected. You can see a full list of committees along with our Associate and Assistant Directors on our website (https://psysciacc.org/people/). You can expect to hear much more from the Assistant Directors in the near future!

4. Finally, PSA member, and contributor to our Methods and Analysis Committee, Nick Fox is conducting a study on psychological researchers that involves testing a new resource for accessing academic literature - to participate, click or copy/paste the following link: https://rutgers.ca1.qualtrics.com/jfe/form/SV_bBdKmMYWtP1Oq3P

We continue working hard on many fronts, and I hope to have more exciting news to share with you in the coming weeks. Thank you for all that you have done, and continue to do, to accelerate psychological science through your work with the PSA!
