---
title: "006 Resubmitted & Recruiting Labs in India or Japan"
author: "Chris Chartier"
date: 2019-10-07
categories:
  - mailchimp backup
---

Accelerators,

The lead author team for PSA 006 did some amazing work on the revisions of the Stage 1 Registered Report manuscript and it is now back under review at Nature Human Behaviour. I'm sharing the updated preprint here (https://psyarxiv.com/9uaqm/). We could use additional data collection labs for this project in both Japan and India. If you'd like to join on, please just let us know by replying to this email. Thanks!

Also, as a more general update, I wanted to let everyone know that I plan to send slightly more frequent update emails (perhaps weekly) via this mailing list in the coming months. I had been using only the newsletter as an opportunity for monthly updates, and I'll still publish and email those to the full network, but we now have enough projects reaching major milestones that I think more frequent project specific updates (such as the one above) are appropriate and will help keep everyone in the loop! I hope these do not become too burdensome on your inbox.

As always, thank you for all of your past, present, and future work accelerating psychological science as part of this amazing and ever-expanding team :)

