---
title: "News from the Accelerator - January 2019"
author: "Chris Chartier"
date: 2019-01-31
categories:
  - mailchimp backup
---

Accelerators,
It has been an exciting month for the PSA! You can read a full summary of recent activities and PSA news here in our January newsletter (https://psysciacc.org/news/2019-01-31_news-from-the-accelerator-january-2019.html). A few highlights include:
* We have just received an in principle acceptance for “Investigating object orientation effects across 14 languages (https://psyarxiv.com/t2pjv/) ” at Psychonomic Bulletin and Review.
* We also recently received a favorable revise and resubmit decision for “Accelerated CREP: RRR: Turri, Buckwalter, & Blouw (2015) (https://psyarxiv.com/zeux9) ” at Advances in Methods and Practices in Psychological Science.
* We are recruiting labs (https://t.co/wRxvjJcygd)  for “On the universality of moral thinking: Cross-cultural variation in the influence of personal force and intention in moral dilemma judgments (https://osf.io/d2ptq/) .” The current list of contributing labs is up to 105 sites representing 42 countries!
* Data collection continues for “To which world regions does the valence-dominance model apply (https://psyarxiv.com/n26dy) .” We have now collected data from over 2,000 participants across 48 labs.


Thank you for all of your work! Full speed ahead!
