---
title: "Introducing the PSA001 Secondary Analysis Challenge"
date: 2019-09-01
---

<strong>Patrick Forscher, Lisa DeBruine, Ben Jones, Jess Flake, Nick Coles, Chris Chartier</strong>
<h6><i><span style="font-weight:400;">Please cite this blog post as: </span></i>Forscher, P. S., DeBruine, L. M., Jones, B. C., Flake, J. K., Coles, N. A., &amp; Chartier, C. R. (2019, September 1). Introducing the PSA001 Secondary Analysis Challenge. <a href="https://www.google.com/url?q=https://psysciacc.org/2019/09/01/introducing-the-psa001-secondary-analysis-challenge/&amp;sa=D&amp;ust=1590158890036000&amp;usg=AFQjCNEEvUxsA8HKtyLsvYi0j6ew7xRxyQ" target="_blank" rel="noopener">https://psysciacc.org/2019/09/01/introducing-the-psa001-secondary-analysis-challenge/</a></h6>
<span style="font-weight:400;">We are offering up to 10 awards of $200 to research teams that use data from our first study (</span><a href="https://psyarxiv.com/n26dy" target="_blank" rel="noopener">PSA001</a><span style="font-weight:400;">) to follow an analysis pipeline meeting our specifications. We describe the background, rationale, and details below. </span>

<i><span style="font-weight:400;">Background</span></i>

<span style="font-weight:400;">Psychology datasets contain a wealth of information, including dozens, hundreds, and sometimes even thousands of variables. Datasets that are well-documented can be even richer, as appropriate documentation can allow these datasets to be merged with secondary information (or </span><i><span style="font-weight:400;">meta-data</span></i><span style="font-weight:400;">), exponentially expanding the universe of possible analyses.</span>

<span style="font-weight:400;">Although some researchers use publicly posted data in their research, we believe the potential of secondary analyses is, as yet, untapped. Some of this untapped potential may result from the typical structure of a psychology dataset release. In the best case, the dataset is described in an article in a journal (such as the </span><a href="https://openpsychologydata.metajnl.com/" target="_blank" rel="noopener">Journal of Open Psychology Data</a><span style="font-weight:400;"> or </span><a href="https://www.nature.com/sdata/" target="_blank" rel="noopener">Scientific Data</a><span style="font-weight:400;">). In the worst, the dataset is undocumented and only available on request (if at all). We believe we can do better to make our datasets maximally informative.</span>

<i><span style="font-weight:400;">Phased dataset release (with incentives)</span></i>

<span style="font-weight:400;">Our test case for innovating with improving the data release process is </span><a href="https://psyarxiv.com/n26dy" target="_blank" rel="noopener">PSA001</a><span style="font-weight:400;">, a project to test whether the valence-dominance model of face perception generalizes across world regions.  The primary dataset contains ratings from over 11,000 participants across 11 world regions, 48 countries, and 28 languages. Each participant rated 120 faces twice on one of 13 traits. In addition to these ratings, we have access to datasets containing various meta-data. These include datasets of participant characteristics (such as race and gender </span><span style="font-weight:400;">–</span><span style="font-weight:400;"> some locations only), site characteristics (such as world region and institutional affiliation), and characteristics of the faces that were rated (such as the gender of the face, picture luminance, and the size of various facial features).</span>

<span style="font-weight:400;">In our release of this dataset, we are following the lead of other high quality data releases by carefully curating and documenting our datasets.  However, we are adding an extra innovation: we are structuring the release in a way that we think will maximize the value of the resulting secondary analyses.  Specifically, we are releasing </span><i><span style="font-weight:400;">separate</span></i><span style="font-weight:400;"> exploratory and confirmatory segments of the data and </span><i><span style="font-weight:400;">incentivizing</span></i><span style="font-weight:400;"> the use of these separate segments by offering up to </span><b>10 awards of $200</b><span style="font-weight:400;"> to research teams who complete the analysis pipeline of exploring with the exploratory segment, confirming with the confirmatory segment, and sharing the results on </span><a href="https://psyarxiv.com/" target="_blank" rel="noopener">PsyArXiv</a><span style="font-weight:400;">.</span>

<i><span style="font-weight:400;">The details</span></i>

<span style="font-weight:400;">The data release plan for this project consists of three phases: release of a simulated dataset (to allow people not directly involved in the project time to understand the variables we collected), release of an exploratory segment (⅓ of the full dataset), and release of a confirmatory segment (the full dataset).  We will stratify by lab when creating our exploratory and confirmatory segments; in other words, we will randomly sample ⅓ of the participants within each lab that contributed data to create the exploratory segment. The full dataset will demarcate the exploratory and confirmatory All data drops will occur at randomly selected UTC times between 12am and 11pm.</span>

<span style="font-weight:400;">We will provide up to 10 awards of $200 each for research teams that make secondary contributions from the exploratory and confirmatory datasets.  If more than 10 teams submit contributions the winners will be chosen at random.  To be eligible, a research team must:</span>
<ul>
 	<li style="font-weight:400;"><span style="font-weight:400;">Write a computationally reproducible script that analyzes the exploratory dataset.  </span><span style="font-weight:400;">The script may be written in any data analysis software, but we strongly encourage the use of open-source software such as R.</span></li>
 	<li style="font-weight:400;"><span style="font-weight:400;">Post the script to a project on the Open Science Framework and create a date-stamped preregistration of the script using </span><a href="https://osf.io/prereg/" target="_blank" rel="noopener">OSF preregistrations</a><span style="font-weight:400;">.  The proposing teams can use a preregistration template, such as <a href="https://osf.io/v4z3x/" target="_blank" rel="noopener">this one for secondary data analysis</a>, or they can use an open-ended preregistration that only contains the script that the team will use to analyze the confirmatory segment and a date stamp.</span><span style="font-weight:400;">  At the top of the script, the proposing team should write their names and the following text: “I commit to analyzing the confirmatory segment of PSA001 Social Faces using this script upon the project’s release”. The date stamp of the preregistration must be before 12pm UTC, November 30, 2019, which is the point at which the confirmatory segment will be released.  The script will be checked for computational reproducibility by a member of the PSA’s </span><a href="https://osf.io/x7e4m/" target="_blank" rel="noopener">Data and Methods Committee</a><span style="font-weight:400;">.</span></li>
 	<li style="font-weight:400;"><span style="font-weight:400;">After the release of the confirmatory segment, post a preprint to </span><a href="https://psyarxiv.com/" target="_blank" rel="noopener">PsyArXiv</a><span style="font-weight:400;"> detailing the results of the analyses of the exploratory and confirmatory segments.  </span><span style="font-weight:400;">To be eligible for the award, the preprint must be date-stamped by 12pm UTC, January 31, 2020.  For the purposes of winning the award, the preprint may be very brief –tables or figures illustrating the results along with some descriptive text are sufficient.  However, if the research team wishes, the preprint may be more detailed.  The PsyArXiv preprint should be tagged with the study code for this project: “PSA001”.</span></li>
</ul>
<span style="font-weight:400;">Before issuing the awards, members of the Data and Methods Committee will verify that these steps have been followed.</span>

<span style="font-weight:400;">Below are the key dates of this data release plan:</span>
<ol>
 	<li style="font-weight:400;"><span style="font-weight:400;">The </span><b>simulated dataset</b><span style="font-weight:400;">, along with a </span><b>codebook</b><span style="font-weight:400;">, will be released (posted on OSF, tweeted, Facebooked, and blogged) on August 31, 2019, 24:00 UTC, 8pm EST (so it’s available today!!). It, along with detailed documentation of the dataset, are available at </span><a href="https://osf.io/8xd7r/" target="_blank" rel="noopener">this OSF page</a><span style="font-weight:400;">.</span></li>
 	<li style="font-weight:400;"><span style="font-weight:400;">The </span><b>exploratory segment</b><span style="font-weight:400;"> can be found <a href="https://osf.io/yrveh/" target="_blank" rel="noopener">here</a>, and was posted on October 31, 2019, concurrent with the submission of this project’s Stage 2 Registered Report.</span></li>
 	<li style="font-weight:400;"><span style="font-weight:400;">The </span><b>preregistered analyses</b><span style="font-weight:400;"> should be submitted via </span><a href="https://forms.gle/4UpUigozZtn7kMWh9" target="_blank" rel="noopener">this form</a><span style="font-weight:400;"> by November 30, 2019, 12pm UTC.</span></li>
 	<li style="font-weight:400;"><span style="font-weight:400;">The </span><b>confirmatory segment</b><span style="font-weight:400;"> will be released concurrently with the publication of the Stage 2 paper at Nature Human Behaviour.</span></li>
 	<li style="font-weight:400;"><span style="font-weight:400;">The </span><b>preprint</b><span style="font-weight:400;"> should be posted within one month of the release of the confirmatory segment.  Once posted, the preprint can be submitted to the PSA001 team via this </span><a href="https://forms.gle/AdDjCbPY5z58anhn9" target="_blank" rel="noopener">form</a><span style="font-weight:400;">.</span></li>
</ol>
<span style="font-weight:400;">If you have questions about this process, or the data that we have available, contact the PSA001 data manager (Patrick S. Forscher) at </span><a href="mailto:schnarrd@gmail.com"><span style="font-weight:400;">schnarrd@gmail.com</span></a><span style="font-weight:400;">.</span>

<i><span style="font-weight:400;">Conclusion</span></i>

<span style="font-weight:400;">We hope this project can serve as an exemplar of how the details of data release can add value to the scientific knowledge generated from a particular dataset. We hope you consider participating in our Secondary Analysis Challenge so we can see if this is indeed the case.</span>
