---
title: "News from the Accelerator - February 2019"
author: "Chris Chartier"
date: 2019-02-28
categories:
  - mailchimp backup
---

Accelerators,

You can read up on the last month (our 18th month of existince!) of PSA activities in our February newsletter (https://psysciacc.org/news/2019-02-28_news-from-the-accelerator-february-2019.html). It includes updates on policy docs, the funding committee's work, our 6 studies, and PSA members presenting at conferences, being interviewed on podcasts, and publishing online articles about our work.

For current members, we now call for a vote on our Personnel, Elections, and Appointments policy document (https://docs.google.com/document/d/1aXjXwouFc6wvcyy7IFmEKGL0j2yxzYukyI_YFf6sZtM/edit). Please read it and provide your vote by replying to this email with either "Yes, I vote in support of this policy" or "No, I vote against this policy." You can provide your feedback/criticism/rationale for voting against the policy also in your email. We will accept votes through March 15th, 2019.

Thank you for all of your hard work on the PSA!

