---
title: "The PSA is Two Years Old. Let’s Celebrate!"
date: 2019-08-22
---

<span style="font-weight:400;">This coming Monday the Psychological Science Accelerator turns two. To celebrate, we’re planning a week of exciting announcements, blogposts, and hackathons. Today we just wanted to post a full schedule for the week, with brief descriptions of each event in case you wanted to follow along or join in. Watch our twitter account for frequent updates and links throughout the week.</span>
<h2 style="text-align:center;"><b>Blog schedule</b></h2>
<i><span style="font-weight:400;">Monday</span></i>
<p style="padding-left:30px;">Highlights<span style="font-weight:400;"> from our first 2 years</span></p>
<i><span style="font-weight:400;">Tuesday</span></i>
<p style="padding-left:30px;"><span style="font-weight:400;">Updates on our Patreon grassroots funding campaign</span></p>
<i><span style="font-weight:400;">Wednesday</span></i>
<p style="padding-left:30px;"><span style="font-weight:400;">Announcing a new batch of PSA member lab grants for 2019/2020 and how you can apply</span></p>
<i><span style="font-weight:400;">Thursday</span></i>
<p style="padding-left:30px;"><span style="font-weight:400;">Celebrating and making more visible the sometimes invisible work of PSA members filling study-specific support roles (e.g., project monitoring, data management, translation coordination)</span></p>
<i><span style="font-weight:400;">Friday</span></i>
<p style="padding-left:30px;"><span style="font-weight:400;">Releasing and soliciting feedback on the first draft of our vision statement for the PSA (precursor to a 5-year strategic plan)</span></p>
<i><span style="font-weight:400;">Saturday</span></i>
<p style="padding-left:30px;"><span style="font-weight:400;">Announcing Study 001’s data release plan, including incentives for pre-registered secondary analyses</span></p>

<h2 style="text-align:center;"><b>Hackathon schedule</b></h2>
<i><span style="font-weight:400;">Monday</span></i>
<p style="padding-left:30px;"><a href="https://docs.google.com/document/d/1aQys_HcgQLLay7ZBLLzrHU3ooN3v5I3QPuuLXP4-6-w/edit" target="_blank" rel="noopener">Vision Statement Draft Feedback and Editing</a><span style="font-weight:400;"> (Chris Chartier, 10:30 UTC, 6:30am EST)</span></p>
<p style="padding-left:30px;"><a href="https://docs.google.com/document/d/1p3q9BkQZsPeODG5Ykiob3DRaN7Cgc6ojmHeDoX46RRw/edit" target="_blank" rel="noopener">Google drive migration</a><span style="font-weight:400;"> (Patrick Forscher, 17:00 UTC, 1:00PM EST) </span></p>
<i><span style="font-weight:400;">Tuesday</span></i>
<p style="padding-left:30px;"><a href="https://drive.google.com/open?id=1WNHspyaq98Max2PAVFll_vpkTDcK6dCstEoBZru-aaw" target="_blank" rel="noopener">Meta-science policies</a><span style="font-weight:400;"> (Nick Fox, 18:00 UTC, 2:00pm EST)</span></p>
<i><span style="font-weight:400;">Wednesday</span></i>
<p style="padding-left:30px;"><a href="https://drive.google.com/open?id=1xHWDwRqGSnApEg8JyqP50Mvvw2afcgZoX5oO61Xz1lw" target="_blank" rel="noopener">Member site and roster info form</a><span style="font-weight:400;"> (Erin Buchanan, 13:30 UTC, 9:30am EST)</span></p>
<i><span style="font-weight:400;">Thursday</span></i>
<p style="padding-left:30px;"><a href="https://drive.google.com/open?id=1De5w8g4I7VTEoS6bL6n-QO5HRLItAMC8cdl7w-TUnRQ" target="_blank" rel="noopener">Election logistics</a><span style="font-weight:400;"> (Charlie Ebersole, 16:30 UTC, 2:30pm EST)</span></p>
<i><span style="font-weight:400;">Friday</span></i>
<p style="padding-left:30px;"><a href="https://docs.google.com/document/d/1yQlcSU3F8mF5FdxRWItKRHr9qm9lqMVdHn5x_gsf6lQ/edit?usp=sharing" target="_blank" rel="noopener">Patreon and Donor Campaign</a><span style="font-weight:400;"> (Chris Chartier, 13:00 UTC, 9:00am EST)</span></p>
<p style="padding-left:30px;"><a href="https://docs.google.com/document/d/1-Xvm0w8QvLdBYfaCS2LiHGTiJtwNO5yqVgoZ2fhGRXA/edit?usp=sharing" target="_blank" rel="noopener">Synergy hack-a-thon</a><span style="font-weight:400;"> (Patrick Forscher, 15:00 UTC, 11:00am EST)</span></p>
<span style="font-weight:400;">We hope to see you during the week!</span>
