---
title: "The PSA’s Draft Vision Document is Open for Feedback"
author: "Chris Chartier"
date: 2019-08-30
---

We are releasing our [draft vision
document](https://docs.google.com/document/d/1FiPxP9d2It6ULd87JiYd90UlzHCTeqLAH4GPZdA6Rk0/edit#){target="_blank"}
for feedback from anyone. You do not need to be a PSA member to comment,
and we welcome your input via comments in the google doc or sent via
email (psysciaccelerator@gmail.com). Soon after founding the PSA, we
collectively established our mission statement, core values, selected
our first studies, and drafted initial policies for how we conduct our
projects. Then we got to work! We focused on the most pressing needs of
planning and conducting our studies and setting up our organizational
and governance structures. We now need to also focus on long-term
planning to ensure the PSA is a sustainable project that works best for
psychological science and its members. The current document represents
an early step in our formal planning process in two ways: 1) it will
undergo several rounds of feedback from PSA members prior to being voted
on as possible PSA policy, and 2) if it is ratified it will form just
one portion of a more detailed strategic plan to be drafted in 2020 and
then reassessed annually thereafter. Before we can draft a full
strategic plan that includes more specific activities, goals, funding
strategy, and a projected budget, we need broad community buy-in on the
ideas and basic plans outlined in the vision document. To that end, the
draft now open for feedback from anyone (PSA member or not) during the
entire month of September 2019. The PSA Directors will edit the document
in response to this feedback during October, and we will put the revised
document up for a vote by the PSA network during November. If the vision
statement is not ratified during that vote, we will continue to
iteratively solicit feedback, edit, and vote until a version has been
ratified. If it is ratified during the November vote, it will be
published on the PSA website in December. We will then begin the more
detailed strategic planning process. The 5-year strategic plan will
follow the same timeline in 2020 as this vision document is following in
2019. The Directors will draft the plan January through August, we will
solicit feedback in September, we will edit in October, and all PSA
members will vote in November. The process of assessing, revising,
seeking feedback, and ultimately voting on the strategic plan will occur
annually thereafter following the same month-by-month schedule. Thank
you in advance for any feedback you provide!

