---
title: "Several important updates and requests - News from the Accelerator - September 2019"
author: "Chris Chartier"
date: 2019-09-05
categories:
  - mailchimp backup
---

Hello!

We have a host of updates in our September newsletter. Read for context and plenty of useful links! I also want to particularly highlight, in this email, two important requests:

1. We have launched a PSA member website (https://member.psysciacc.org/login.php) thanks to the hard work of Erin Buchanan. For now, we are asking all members of the PSA to create an account on the site, login in, and complete the member information form. Erin also put together this awesome tutorial video (https://www.youtube.com/watch?v=YZvD5Wi-KnI&feature=youtu.be)  to walk you through the process! Doing so will allow you to apply for PSA grant support, to vote on policies and elected positions, to see and review study submissions, and to join future PSA studies.

2. We now call for a vote on our “meta-policy” document (https://docs.google.com/document/d/14D6GrE4i7FJejq_BUZ9DPC2bQfCb2PztdEB63QldOow/edit) ! It describes how current PSA polices can be amended and how members can propose new policies. All members can vote by replying to this email with a simple "yes" or "no" vote. Thanks!
