---
title: "The PSA’s Patreon Sustainability Drive"
date: 2019-08-27
---

<span style="font-weight:400;">The PSA owes its success to the enthusiasm of its members.  That enthusiasm has led to an outpouring of volunteer work hours. In 2019, we estimate that these hours total 19,390, equivalent to approximately 10 full-time people per year. </span>

<span style="font-weight:400;">However, enthusiastic volunteerism has its limits. First, some items, such as software licenses and compensation for participants, cannot be bought solely with volunteer labor. Second, volunteer time necessarily comes at the expense of time spent on other activities -- activities that more directly benefit one’s career. Thus, for the PSA to maximize its positive impact, it needs to develop a broad set of reliable funding streams, both to enable special projects that require direct funding and to guard against the eventuality that enthusiasm for the PSA diminishes.</span>

<span style="font-weight:400;">That’s where you come in. We have recently created a </span><a href="https://www.patreon.com/psysciacc" target="_blank" rel="noopener">Patreon page</a><span style="font-weight:400;"> to allow interested people to make regular contributions to help the PSA fulfill its goals. The exact items that we fund with the Patreon will change on a regular basis; however, we have made a pledge that all the money we receive through this Patreon page will be reinvested into the PSA in a way that directly supports our mission and is in line with our core principles.</span>

<span style="font-weight:400;">In the coming year, we hope to use the Patreon to fund two items, both of which will be discussed further in a blog post of their own later this week:</span>
<ol>
	<li style="font-weight:400;"><b>Six grants of $400</b><span style="font-weight:400;"> to PSA member labs who wish to collect data for one of our studies but lack the resources to do so</span></li>
	<li style="font-weight:400;"><b>Six stipends of $400</b><span style="font-weight:400;"> to help compensate people who take on study-specific administrative roles</span></li>
</ol>
<span style="font-weight:400;">We will feel comfortable funding these if our Patreon reaches the threshold of </span><b>$400 per month</b><span style="font-weight:400;"> by </span><b>Tuesday September 3, 5pm UTC</b><span style="font-weight:400;">. We will provide regular updates as to our progress.</span>

<span style="font-weight:400;">If you are able to donate a monthly contribution and you think our goal is worthy, </span><a href="https://www.patreon.com/psysciacc" target="_blank" rel="noopener">consider becoming a patron</a><span style="font-weight:400;">. Even $1 a month gets us closer to your goal. Help us reach our goal and thereby incrementally advance the improvement of psychological science!</span>
