---
title: "News from the Accelerator - May 2019"
date: 2019-05-31
---

This month we announce an upcoming call for studies, seek contributors to several key committees, and give mini progress reports on all 6 of our current studies.
<h2><span style="font-weight:400;">New Call for Studies Coming Soon</span></h2>
<span style="font-weight:400;">It is almost time for another round of study selection (our 3rd)! On June 15th we will release a detailed call for studies post with our updated submission guidelines. The deadline for study submissions will be September 15th. To begin planning now, you can review our <a href="https://psysciacc.org/2018/04/30/the-psychological-science-accelerator-call-for-study-submissions-deadline-june-20th/" target="_blank" rel="noopener">prior call for studies</a>, or reply to this email with any presubmission inquiries. We are excited to see what great ideas are submitted this round!</span>
<h2>Committees Seeking Contributors</h2>
<span style="font-weight:400;">Several committees could use additional members to better support our current studies, provide training for the PSA network, and to prepare for our next round of study review and selection.</span>
<ul>
	<li><span style="font-weight:400;">Ethics Committee: </span>The Ethics Committee is seeking representation from the following broad geographic regions: Africa, Asia, Australia, and Central and South America. We are currently a group of 7; however, we are almost exclusively located in the US and Europe, and we want to meet the diverse needs of all PSA-represented regions and beyond. Currently, we have the following roles: 1) provide reviews of proposed PSA projects with an eye toward ethics, 2) provide reviews of accepted PSA project IRB and ethics review board materials prior to distribution to the larger PSA group, 3) provide ethics-oriented consultation to ongoing PSA projects, 4) work with other PSA committees to ensure ethical practices. Zoom-based meetings are approximately monthly. For more information and/or to submit a CV, please contact Erica Musser at <span style="font-weight:400;">emusser@fiu.edu.</span></li>
	<li>Study Selection Committee: The Study Selection Committee serves a vital role in the workflow of the PSA by facilitating the review of proposed projects and ultimately deciding on their acceptance to be run by our network. We are currently seeking 2-4 new members to aid in our next round of selection in late summer and early fall of this year. Committee members must commit to serve for 1 year but may choose to resign at any point thereafter. Unlike many of the other PSA committees, the work of the Study Selection Committee is concentrated to a few months per year. The PSA solicits study proposal submissions on an ad hoc basis. After each call for submissions is closed, the Study Selection Committee evaluates the submissions for feasibility and general quality. We then vote on whether each proposal merits review. Suitable proposals are then reviewed by experts in and outside of the network. The Study Selection Committee compiles and synthesizes this feedback. The committee then makes the final selections on the basis of reviewers’ responses, evaluations from the PSA network, and the PSA’s mission, values and capacity. If you would like to join the committee, please submit a CV to committee co-chair and PSA Assistant Director Kathleen Schmidt (<a href="mailto:kathleenschmidt1@gmail.com">kathleenschmidt1@gmail.com</a> or <a href="mailto:kathleen.schmidt@siu.edu">kathleen.schmidt@siu.edu</a>).</li>
	<li><span style="font-weight:400;">Training Committee: </span><span style="font-weight:400;">The Training Committee is recruiting committee coordinators to help organize and provide trainings for the PSA and larger science community. If you are interested in joining our team, please read about our openings and apply! </span>Link: <a href="https://forms.gle/yiS89d22bNA6P5hRA"><span>https://forms.gle/yiS89d22bNA6P5hRA</span></a></li>
	<li><span style="font-weight:400;">Translation Coordinator for Study 004, The Accelerated CREP Project: </span>We are looking for a translation coordinator for PSA 004 (Accelerated CREP) to coordinate and monitor the translations according to PSA’s translation policies. The Accelerated CREP is a pedagogical project conducted by student teams in collaboration with faculty supervisors. The preprint of the registered report (under review and hopefully very close to an in principle acceptance at <em>AMPPS</em>) is available at <a href="https://psyarxiv.com/zeux9"><span>https://psyarxiv.com/zeux9   </span></a><span style="font-weight:400;">. The study is currently translated into nine different languages and most of these are ready for the next step in the translation process (back translations and controlling for equivalence). The translation coordinator is expected to coordinate the remainder of the translation process and monitor them. The translation coordinator will earn authorship on the resulting manuscript.</span></li>
</ul>
<h2>Current Studies</h2>
<ul>
	<li>001 FACE PERCEPTION: We have collected data from over 10,000 participants and are on track to finish data collection in September. <a href="https://psyarxiv.com/n26dy/" target="_blank" rel="noopener">001 Preprint</a></li>
	<li>002 OBJECT ORIENTATION &amp; 003 GENDERED PREJUDICE: The 003 pre-registration is being finalized by the lead team and data collection for the bundled projects will commence in June! <a href="https://psyarxiv.com/t2pjv" target="_blank" rel="noopener">002 Preprint</a></li>
	<li>004 TRUE BELIEF: The Stage 1 Registered Report is under review (following 2 rounds of "revise and resubmit") at <em>Advances in Methods and Practices in Psychological Science</em>. <a href="https://psyarxiv.com/zeux9" target="_blank" rel="noopener">004 Preprint</a></li>
	<li>005 STEREOTYPE THREAT: The Stage 1 Registered Report draft is nearly complete and will be submitted to <em>Nature Human Behavior</em> very soon.</li>
	<li>006 TROLLEY PROBLEM: The Stage 1 Registered Report is under review at <em>Nature Human Behaviour</em>. <a href="https://psyarxiv.com/9uaqm/" target="_blank" rel="noopener">006 Preprint</a></li>
</ul>
<h2><span style="font-weight:400;">Postdoctoral Researcher Position</span></h2>
Tomorrow (June 1) is the last day to <a href="https://euraxess.ec.europa.eu/jobs/410163" target="_blank" rel="noopener">apply for the PSA post-doc position</a>. We (a team led by Hans IJzerman) are looking for a talented and motivated postdoctoral researcher. The position is for two years and will be hosted at LIP/PC2S at Université Grenoble Alpes. The position’s primary focus is to support the Psychological Science Accelerator (PSA: <a href="https://psysciacc.org/">https://psysciacc.org</a>) in grant writing. The first priority for the postdoctoral researcher is to help write a Synergy Grant (<a href="https://erc.europa.eu/funding/synergy-grants">https://erc.europa.eu/funding/synergy-grants</a>), where the proposed co-PIs are John Ioannidis (Stanford University), Denny Borsboom and Eric Jan Wagenmakers (University of Amsterdam), Lisa DeBruine and Ben Jones (University of Glasgow), and Hans IJzerman (Université Grenoble Alpes). The postdoctoral researcher will also be involved in PSA-related research and will be involved in some supervision of students who do PSA-related research. The candidate we search should be an excellent writer and should have ample experience with open science (and be familiar with R and/or Python). To read more about context in which the postdoctoral researcher will be embedded, please go to <a href="http://www.corelab.io/">www.corelab.io</a>.
