---
title: "Highlights of the PSA’s First Two Years"
date: 2019-08-26
---

<span style="font-weight:400;">On August 26, 2017, Chris Chartier wrote a blog post posing a simple question: what might happen if psychology adopted the collaborative “big science” model seen in physics and built a “CERN for psychological science”?</span>

<span style="font-weight:400;">2018 gave us a glimpse of the answer: a rapidly-expanding network of over 300 psychology labs from over fifty countries. The first year was a flurry of activity as, in quick succession, the PSA accepted four studies and had its first academic paper accepted. The network’s rapid expansion in its first year speaks to the hunger for ambitious solutions to two of the problems that psychology currently faces: lower-than-desired levels of replicability and generalizability of psychological findings.</span>

<span style="font-weight:400;">The PSA’s second year has marked the beginnings of a transition from idea to action.  The network has continued to expand, now standing at over </span><a href="https://nicholas-coles.shinyapps.io/PSA_Map_Prototype/" target="_blank" rel="noopener">500 labs from over 70 countries</a><span style="font-weight:400;">.  We have selected 2 new studies, collected data from over 11,000 participants for our first study, initiated data collection in 3 other studies, received in principle acceptance for 2 registered report manuscripts, and submitted another 2 for stage 1 peer review. </span>

<span style="font-weight:400;">This productivity in the selection, preparation, and conduct of our studies was matched by a substantial organizational infrastructure development</span><span style="font-weight:400;">. PSA members named Assistant Directors to lead the committees that do the bulk of its administrative and coordination work, initiated a project to formalize its study pipeline, drafted a coherent set of policies dictating how the PSA manages and releases its data, made the PSA’s first full-time hire (Patrick Forscher at Université Grenoble Alpes), announced the first round of PSA elections, created a Patreon, submitted several grant proposals, and drafted a vision statement outlining the PSA’s long-term priorities. If the PSA’s first year was focused on growth and excitement, its second year was focused on </span><i><span style="font-weight:400;">turning plans into action and establishing sustainability</span></i><span style="font-weight:400;">, and we hope our third year is one of securing large-scale funding to more effectively pursue our mission with six key aims: </span>
<ol>
	<li style="font-weight:400;"><span style="font-weight:400;">Collect samples that represent all people </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">Train and support our global network of researchers</span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">Expand the PSA’s capacity to include more complex behavioral studies</span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">Release large-scale data-sets that are maximally informative for secondary re-use</span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">Improve psychological science through meta-scientific and instructional contributions</span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">Expand capacity to conduct more, and bigger, studies</span></li>
</ol>
<span style="font-weight:400;">Below we have created a chronological timeline of important events in the PSA. All of these accomplishments represent the work of literally hundreds of researchers. We can’t thank them enough for joining us on this journey to accelerate psychological science. Here’s to many more productive and rewarding years ahead!</span>

<b>Timeline of important PSA events (with links)</b>

<i><span style="font-weight:400;">Year one</span></i>
<ul>
	<li style="font-weight:400;"><span style="font-weight:400;">August 26, 2017: </span><a href="https://christopherchartier.com/2017/08/26/building-a-cern-for-psychological-science/" target="_blank" rel="noopener">CERN for psych blog post</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">September 5, 2017: </span><a href="https://christopherchartier.com/2017/09/05/update-building-a-cern-for-psychological-science/" target="_blank" rel="noopener">72 labs recruited</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">September 21, 2017: </span><a href="https://christopherchartier.com/2017/09/21/the-psychological-science-accelerator-a-distributed-laboratory-network/" target="_blank" rel="noopener">Renamed Psychological Science Accelerator</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">October 1, 2017: First call for studies</span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">October 12, 2017: </span><a href="https://christopherchartier.com/2017/10/12/on-the-verge-of-acceleration-the-psa-has-received-its-first-submissions/" target="_blank" rel="noopener">First study submissions</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">October 24, 2017: </span><a href="https://twitter.com/PsySciAcc/status/922857196223840258" target="_blank" rel="noopener">PSA logo created by Lisa DeBruine</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">October 25, 2017: </span><a href="https://twitter.com/PsySciAcc/status/923202501595168771" target="_blank" rel="noopener">psysciacc.org website created</a><span style="font-weight:400;">  </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">October 31, 2017: </span><a href="https://psysciacc.org/2017/11/08/the-psychological-science-accelerators-first-study/" target="_blank" rel="noopener">Study PSA001 (face perception) accepted by the PSA</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">November 8, 2017: </span><a href="https://www.sciencemag.org/news/2017/11/new-accelerator-aims-bring-big-science-psychology" target="_blank" rel="noopener">First press coverage, by Science Magazine</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">November 28, 2017: </span><a href="https://psysciacc.org/2017/12/05/accepted-for-2018-gendered-social-category-representations/" target="_blank" rel="noopener">Study PSA002 (object orientation) accepted by the PSA</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">December 12, 2017: </span><a href="https://psysciacc.org/2018/01/24/new-study-accepted-the-object-orientation-effect/" target="_blank" rel="noopener">Study PSA003 (gendered prejudice) accepted by the PSA</a></li>
	<li style="font-weight:400;"><span style="font-weight:400;">December 13, 2017: </span><a href="https://fivethirtyeight.com/features/can-teamwork-solve-one-of-psychologys-biggest-problems/" target="_blank" rel="noopener">Coverage of the PSA by FiveThirtyEight</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">January 7, 2018: </span><a href="https://twitter.com/PsySciAcc/status/950058716673527813" target="_blank" rel="noopener">192 sites in 44 countries</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">February 7, 2018: </span><a href="https://psysciacc.org/translation-process/" target="_blank" rel="noopener">Translation guidelines drafted</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">April 2, 2018: </span><a href="https://psyarxiv.com/785qu/" target="_blank" rel="noopener">Preprint posted of our first policy paper</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">April 3, 2018: </span><a href="https://www.buzzfeednews.com/article/stephaniemlee/psychology-science-accelerator-replication#.ih7a5n82V" target="_blank" rel="noopener">Coverage of the PSA by Buzzfeed</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">April 8, 2018: </span><a href="https://psysciacc.org/2018/04/08/the-accelerated-crep/" target="_blank" rel="noopener">PSA004 (accelerated CREP) accepted by the PSA</a></li>
	<li style="font-weight:400;"><span style="font-weight:400;">April 30, 2018: </span><a href="https://psysciacc.org/2018/04/30/the-psychological-science-accelerator-call-for-study-submissions-deadline-june-20th/" target="_blank" rel="noopener">Second call for studies issued</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">May 3, 2018: </span><a href="https://twitter.com/CRChartier/status/992098414002294785" target="_blank" rel="noopener">Three Associate Directors appointed</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">May 18, 2018: </span><a href="https://psyarxiv.com/n26dy/" target="_blank" rel="noopener">PSA001 Registered Report submitted</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">June 22, 2018: </span><a href="https://twitter.com/PsySciAcc/status/1010224649853120516" target="_blank" rel="noopener">Remaining Associate Directors appointed</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">June 24, 2018: </span><a href="https://twitter.com/PsySciAcc/status/1011024688250785793" target="_blank" rel="noopener">Chris Chartier wins SIPS Leadership Award for his work on the PSA and StudySwap</a><span style="font-weight:400;">  </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">July 3, 2018: </span><a href="https://twitter.com/PsySciAcc/status/1014152298455556097" target="_blank" rel="noopener">346 labs from 53 countries</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">July 20, 2018: </span><a href="https://twitter.com/hmoshontz/status/1020330269847576578" target="_blank" rel="noopener">Intro paper accepted at Advances in Methods and Practices in Psychological Science</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">August 13, 2018: </span><a href="https://psyarxiv.com/vg649" target="_blank" rel="noopener">Scientific Utopia III, on large-scale collaborations (including the PSA), posted as a preprint</a><span style="font-weight:400;"> </span></li>
</ul>
<i><span style="font-weight:400;">Year two</span></i>
<ul>
	<li style="font-weight:400;"><span style="font-weight:400;">August 26, 2018: </span><a href="https://psysciacc.org/2018/08/26/the-psychological-science-accelerators-first-year/" target="_blank" rel="noopener">PSA one-year anniversary</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">September 5, 2018: </span><a href="https://twitter.com/PsySciAcc/status/1037366722901225472" target="_blank" rel="noopener">Assistant Directors named</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">October 15, 2018: </span><a href="https://psyarxiv.com/zeux9/" target="_blank" rel="noopener">PSA004 posted as preprint</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">October 19, 2018: </span><a href="https://psysciacc.org/2018/10/19/a-large-scale-multi-site-examination-of-stereotype-threat-across-varying-operationalizations-a-newly-selected-accelerator-study/" target="_blank" rel="noopener">PSA005 (stereotype threat) accepted by the PSA</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">November 1, 2018: </span><a href="https://psyarxiv.com/t2pjv" target="_blank" rel="noopener">PSA003 posted as a preprint</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">November 5, 2018: </span><a href="https://twitter.com/PsySciAcc/status/1059442677261967360" target="_blank" rel="noopener">PSA001 accepted in principle at Nature Human Behaviour</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">December 20, 2018: </span><a href="https://psysciacc.org/2018/12/20/new-psa-study-on-the-universality-of-moral-thinking-cross-cultural-variation-in-the-influence-of-personal-force-and-intention-in-moral-dilemma-judgments/" target="_blank" rel="noopener">PSA006 accepted by PSA</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">January 31, 2019: </span><a href="https://twitter.com/PsySciAcc/status/1090957780499005440" target="_blank" rel="noopener">PSA003 accepted in principle at Psychonomic Bulletin and Review</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">March 9, 2019: </span><a href="https://www.patreon.com/psysciacc?utm_medium=social&amp;utm_source=twitter&amp;utm_campaign=creatorshare2" target="_blank" rel="noopener">PSA Patreon launched</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">March 20, 2019: </span><a href="https://psyarxiv.com/buqyc" target="_blank" rel="noopener">Data management policies ratified and released</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">June 15, 2019: </span><a href="https://psysciacc.org/2019/06/15/the-psychological-science-accelerator-calls-for-study-submissions/" target="_blank" rel="noopener">Third call for studies issued</a></li>
	<li style="font-weight:400;"><span style="font-weight:400;">June 24, 2019: </span><a href="https://twitter.com/psforscher/status/1143215706923773954" target="_blank" rel="noopener">PSA’s first full-time hire (through Université Grenoble Alpes)</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;"><span style="font-weight:400;">June 29, 2019: </span><a href="https://psysciacc.org/2019/06/29/update-on-the-accelerated-crep-a-collaborative-crep-replication-project-powered-by-the-psa/" target="_blank" rel="noopener">PSA004 accepted in principle at Advances in Methods and Practices in Psychological Science</a><span style="font-weight:400;"> </span></li>
	<li style="font-weight:400;">July 17, 2019: <a href="https://psyarxiv.com/6hju9" target="_blank" rel="noopener">PSA005 posted as preprint</a></li>
</ul>
