---
title: "News from the Accelerator - September 2019"
date: 2019-09-05
---

August was a very productive and exciting month for the PSA. Here we summarize last month's progress and activities, some exciting new things coming in the near future, and make a few small requests of all PSA members.
<h2><span style="font-weight:400;">PSA Member Site</span></h2>
We have been organizing information about PSA members in a shared google sheet until now. This worked OK for a while, but as our network grew it became disorganized, unwieldy, and error-prone. Lucky for us, Erin Buchanan has been working hard on a new membership website (complete with member database) and is ready for all PSA members to register and provide some information. Eventually, we hope the site can become a "one stop shop" for each PSA member to find information about the status and next steps for any PSA studies they have joined, and any PSA tasks that need new contributors.

For now, we are asking all members of the PSA t<a href="https://member.psysciacc.org/login.php" target="_blank" rel="noopener">o create an account on the site, login in, and complete the member information form</a>. Erin also put together t<a href="https://www.youtube.com/watch?v=YZvD5Wi-KnI&amp;feature=youtu.be" target="_blank" rel="noopener">his awesome tutorial video</a> to walk you through the process!
<h2><span style="font-weight:400;">2 Policy Documents are Open for PSA-wide Feedback</span></h2>
<h3>Vision Statement</h3>
We have drafted and released a PSA <a href="https://docs.google.com/document/d/1FiPxP9d2It6ULd87JiYd90UlzHCTeqLAH4GPZdA6Rk0/edit" target="_blank" rel="noopener">vision statement</a>. This document is a precursor to a more complete 5-year strategic plan to be drafted in 2020. We welcome feedback this month before editing and ultimately calling for a vote to make this statement a PSA policy.
<h3>Analysis Plan Approval Policy</h3>
In future projects, the Data and Methods (DM) committee intends to review the project analysis plan before the project is registered and/or submitted for peer review. This process is meant to ensure that all necessary components (sample size justification, analysis scripts, etc.) are present in the analysis plan when it is submitted for external review. Furthermore, the approval process should provide some minimum reassurance that major methodological issues and flaws in the analysis plan have been addressed before launch of data collection, in the very rare cases that such flaws escape the awareness of the co-author team. In line with the proposed guidelines for PSA policy proposals, the DM committee have sought and incorporated feedback from the PSA director and associate directors. We now invite all members of the PSA to provide feedback on <a href="https://docs.google.com/document/d/1DtoIMZoi3-a4nmgvQbV0LsbEH2xNMgRNnS94H6Jx3jo/edit?usp=sharing" target="_blank" rel="noopener">the document, which can be found here</a>.

The document will be <b>open for feedback for one week</b> as of the posting of this newsletter. After this period the DM committee will incorporate feedback, and subsequently submit the policy for approval by vote by PSA Directors and all members of the PSA.
<h2>Policy Document up for a Vote</h2>
<span style="font-weight:400;">We now call for a vote on our <a href="https://docs.google.com/document/d/14D6GrE4i7FJejq_BUZ9DPC2bQfCb2PztdEB63QldOow/edit" target="_blank" rel="noopener">"meta-policy" document</a>! It describes how current PSA polices can be amended and how members can propose new policies. All members will receive a separate email asking for them to vote yes or no on this proposed policy document.</span>
<h2>The PSA Just Turned 2!</h2>
<span style="color:var(--color-text);">August 26th marked two years of accelerating psychological science. To celebrate we had a flurry of productive hackathons and published 6 blog posts on exciting new developments and future plans for the PSA. We:</span>
<ul>
	<li><a href="https://psysciacc.org/2019/08/26/highlights-of-the-psas-first-two-years/" target="_blank" rel="noopener">Celebrated our 2-year anniversary</a></li>
	<li><a href="https://psysciacc.org/2019/08/27/the-psas-patreon-sustainability-drive/" target="_blank" rel="noopener">Described improvements to our Patreon page and described 2 specific projects we hope to fund.</a></li>
	<li><a href="https://psysciacc.org/2019/08/28/announcing-psa-member-lab-grants-for-2019-2020/" target="_blank" rel="noopener">Announced new member lab grants that you can apply for.</a></li>
	<li><a href="https://psysciacc.org/2019/08/29/recognizing-invisible-labor-in-the-psa/" target="_blank" rel="noopener">Highlighted the amazing work of under-recognized contributors to the PSA and our studies.</a></li>
	<li><a href="https://psysciacc.org/2019/08/30/the-psas-draft-vision-document-is-open-for-feedback/" target="_blank" rel="noopener">Shared our vision statement and announced the next steps in our strategic planning process.</a></li>
	<li><a href="https://psysciacc.org/2019/09/01/introducing-the-psa001-secondary-analysis-challenge/" target="_blank" rel="noopener">Released phase 1 data (simulated data) for PSA 001 and announced an incentivized "challenge" for preregistered secondary analyses.</a></li>
</ul>
<h2>Seeking Additional Assistant Director of the Project Monitoring Committee</h2>
We are calling for applications for a second Assistant Director of the Project Monitoring Committee, to serve alongside Hannah Moshontz. <a href="https://docs.google.com/forms/d/e/1FAIpQLSepxFdyHS2Wc3DOK_j0dCHouGSSCP5NGAdAiRnxCn1ls16xyw/viewform" target="_blank" rel="noopener">You can read more and apply here</a>.
<h2>2 PSA Members Suggest a Theory Committee</h2>
Peder Isager and Nick Coles have made a quite interesting suggestion - that the PSA could use a theory committee - in <a href="https://pedermisager.netlify.com/post/psa-theory-committee/" target="_blank" rel="noopener">a recent blogpost</a>. Have a read and let them know what you think!
