---
title: "2 PSA action items: please provide feedback on study submissions, and more labs are welcome to join Study 002/003 Bundle!"
author: "Chris Chartier"
date: 2020-01-30
categories:
  - mailchimp backup
---

Accelerators,


Two items that you may want to take action on today!

Item 1: We are entering the final stages of study selection for this year, and we ask all network members to provide feedback on the 8 submissions under consideration by February 5th! When you provide your feedback here on the member site (https://member.psysciacc.org/login.php), just make sure you click all the way through to the “thank you” page to ensure your feedback is saved. You can come back to finish later if you do not want to do all of them at once. You can provide feedback over the next week. We hope to send decision letters to all proposing authors in 3-4 weeks. Thank you!

Item 2: The PSA's 002 and 003 project bundle has recently revised their timeline (after receiving an extension from Psychonomic Bulletin and Review) to allow for additional data collection, and even for new teams to join. The new timeline anticipates that data collection will be completed by May. If you are interested in checking out the details of these two projects, you can peruse their OSF pages here: https://osf.io/e428p/ and here: https://osf.io/bdycf/. You can also track the progress the project has made here: https://scgeeker.github.io/PSA002_log_site/index.html. We are particularly keen to onboard a few labs whose non-English participants speak one of the languages on the collection list (Languages that have translated materials: Brazilian Portuguese, Deustch, Greek, Hebrew, Hindi, Magyar, Norwegian, Polish, Simple Chinese, Slovak, Spanish, Thai, Traditional Chinese, and Turkish). If you are interested in getting involved, you can contact Jeremy Miller (millerj@willamette.edu), the
project monitor.

