---
title: "News from the Accelerator - May 2020"
date: 2020-05-21
---

<!-- wp:paragraph -->
<p>This month, we have updates on myriad fronts, including but not limited to, a spike in new PSA membership sign-ups, progress on studies  PSA 001 through PSA 006, information about our recently launched PSA Covid Rapid Studies, a call for new members on two PSA working groups, and several interesting opportunities to collaborate with other PSA members on research projects.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>MEMBERSHIP</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Our network has officially grown to over 1, 000 members. Welcome new accelerators!! We have no doubts that you will do great things in our network. Just in the last couple months since our last newsletter, we have added hundreds of members. We are stoked to see our network continue to grow.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>STUDY UPDATES</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>PSA 001- The Stage 2 Registered Report received a revise-and-resubmit from <em>Nature Human Behaviour</em>. The lead authors have made the requested changes, and the participating labs are currently reviewing the updated manuscript. After the lead authors address those comments, they will resubmit the<a rel="noreferrer noopener" href="https://psyarxiv.com/n26dy" target="_blank"> manuscript.</a></li><li>PSA 002/003- As a result of the pandemic, face-to-face data collection for the 002/003 bundle has been suspended until further notice. We are currently testing the feasibility of moving the procedure online, in case there are no opportunities for in-person data collection for the remainder of the year. Our goal is to complete data collection and submit <a rel="noreferrer noopener" href="https://psyarxiv.com/t2pjv/" target="_blank">002’s Stage 2 registered report</a> by the end of 2020. Thus far, we have collected data from 2,560 participants across 16 languages!</li><li>PSA 004- The Accelerated CREP originally should have been ending data collection right about now, but has been extended through the end of 2020 because of Coronavirus-related delays. You can still join the project to collect data (onboarding form&nbsp;<a rel="noreferrer noopener" target="_blank" href="https://slack-redir.net/link?url=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLSdUif1jYxmf_Mr6svuPm3oqBC7vm3EjbiBdewiqNgzU-Iz7ng%2Fviewform">here</a>)! All data collection can happen online.</li><li>PSA 005- The lead team is working on finishing up its revisions of the Stage 1 <a rel="noreferrer noopener" href="https://psyarxiv.com/6hju9" target="_blank">Registered Report</a>. Our editor at <em>Nature Human Behaviour</em> asked us to do some pilot testing of our technical implementation of the adaptive algorithm that governs condition assignment. With Erin Buchanan's help, we implemented all aspects of the project in formr and conducted a variety of tests to ensure that the condition assignment changes as appropriate in light of different kinds of evidence. This whole effort went slower than expected due to the outbreak of the coronavirus, but we received an extension from our editor. We've also finished a first draft of our paper revisions and our response to reviewers. We expect to submit the revision within 1-2 weeks.</li><li>PSA 006- The PSA 006 project is currently collecting data. So far, the ~150 participating labs have collected data from 8,450 participants. Following the <a href="https://psyarxiv.com/9uaqm/">registered plan</a>, the team is conducting sequential data analyses in three cultural clusters. Further rounds of data collection are expected later this year.</li><li>PSACR 1/2/3- PSA Covid Rapid (PSACR) is three bundled studies running together along with some general questions. PSACR 001 and 003 will be submitted for publication after data collection is complete. PSACR 002 was accepted as a Stage 1 Registered Report at <em>Nature Human Behavior</em>. Data collection is live for all three studies in English, Hungarian, and Dutch and many more languages are in the translation and implementation pipeline. Over 5,000 people have participated so far. Many people have been working hard to pull off this project and in particular, Heather Urry, Max Primbs, and Erin Buchanan have done tremendous work to keep the project afloat, catch errors, and help move translation and implementation along.</li><li>Upcoming New Studies- Resulting&nbsp; from our 2019 call for studies, 1 proposal has been accepted pending minor revisions, two are being revised and resubmitted with possible acceptance in 2020, and several more are being revised and resubmitted in preparation for future calls for studies.</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p><strong>PSA SERVER</strong> <strong>PURCHASED</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Thanks to a generous donation from Erin Buchanan, we were able to purchase new server equipment to support the increasing complexity and data collection load of our current and future PSA studies! The new server has been blazing fast in our initial tests, and it should be ready for us to start using in earnest soon. This also means we are going to be able to overhaul our&nbsp; member website to give it&nbsp;a functioning dashboard that will be more effective and user-friendly for members.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>PLANNING THE PSA'S FIRST CONFERENCE</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>We are hoping to host a virtual meeting in 2020 and are exploring possible dates. Our preliminary plan is to hold the conference in September (on the 1st, 2nd, and 3rd, or on 8th, 9th, and 10th) with sessions spreading across 12 hour each days to help accommodate the vast time zone differences of PSA members. We are hoping to get feedback on which set of days works best for our members (starting on the 1st of September or starting on the 8th of September). We are planning to have a range of session types, including update presentations on current PSA studies, workshops on how to get involved in our studies, study submission tips, as well as presentations on non-PSA research that our members are currently working on. We hope to have further details for y'all soon. Please reach out to <a href="mailto:slewis16@ashland.edu">slewis16@ashland.edu</a> to give feedback on preferred dates or if you would like to be added to our email list of possible attendees.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>DATA AND METHODS COMMITTEE SEEKS NEW MEMBERS</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The PSA Data and Methods Committee is seeking a new standing member of our committee. The Data and Methods Committee (DM) is responsible for operation and policy development related to methodology, meta-science, and data management within the PSA. Those interested to join the committee should read our bylaws here: <a href="https://osf.io/p65qe/">https://osf.io/p65qe/</a>. This position is a two-year commitment, starting in June 2020, with the following responsibilities:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>Attend bi-weekly Data and Methods committee meetings</li><li>Assist with the committee’s operation and research responsibilities</li><li>Advise on matters of committee policy</li><li>Vote on research projects and amendments to the committee’s bylaws</li><li>Fulfill assigned responsibilities (as delegated by the Assistant Directors)</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Some examples of recent work carried out by the committee are:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>Writing, revising, and ratifying the analysis plan approval process</li><li>Coordinating with the larger PSA leadership to develop a needs assessment</li><li>Selecting methodological reviewers for proposals</li><li>Recruiting methodologists and data managers for accepted projects</li><li>Developing a metascience study submission process</li><li>Conducting and contributing to DM research projects undertaken by DM members</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>We expect Standing Committee Members will devote approximately 8-16 hours per month of time to their work. These are not set limits and may fluctuate from month to month. Any members of the PSA are eligible to apply. Previous service experience with the PSA is desired but not required. Application materials to submit:</p>
<!-- /wp:paragraph -->

<!-- wp:list {"ordered":true} -->
<ol><li>Statement of interest outlining interest in working with the DM and relevant experience (short; max 500 words)</li><li>Relevant documentation that supports the information described in the statement of interest and experience (can be a CV, a personal website, blog, osf page, etc.)</li><li>E.g., If you describe experience managing open data you might want to put on your CV links to OSF pages, or link to a github or blog, that is ok -- submit a CV or other document that provides background for your experience</li></ol>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Applicants who move on to the next step of recruitment will be asked to attend a DM committee meeting so that they can become acquainted with our process and procedures. <strong>Review of applications to begin within one week, review rolling until position is filled.&nbsp;</strong> <strong>Please send application materials to: dataandmethods@gmail.com.</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong><b>P</b>SA METASCIENCE SUBCOMMITTEE SEEKS NEW MEMBERS</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The PSA Metascience subcommittee is looking for up to 5 new members to help facilitate Metascience research projects within the PSA.&nbsp; The role of the subcommittee will be to review proposals on work that uses the PSA to research the process of science, as well as develop policy to support metascience research. Responsibilities of subcommittee members will include reviewing proposals, interfacing with members of the Study Selection, Data and Methods, and Data Management Committees when appropriate, and meeting monthly as a group to review progress.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>If you’re interested, send your information to Nick Fox: nfox423@gmail.com by Friday May 29th.</strong>&nbsp; Include a short paragraph on why you’d like to join the subcommittee, what you’re looking to get out of being a subcommittee member, and any metascience or methodological research experience you’ve had (it’s not required, but will be helpful for us to try and maximize the diversity of experiences!).&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>OTHER OPPORTUNITIES TO COLLABORATE WITH PSA MEMBERS</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>African Many Labs</strong></p>
<!-- /wp:paragraph -->

<!-- wp:html -->
<ul><li>We are starting the ManyLabs: Africa project, which is a doctoral thesis on the replicability and generalizability of effects across African and Western populations. The project is led by Adeyemi Adetula, currently at Université Grenoble Alpes (France). The project is supervised by Drs.<a href="https://corelab.io/"> Hans IJzerman</a>,<a href="https://www.usiu.ac.ke/423/brown-dana-basnight-phd/?schl=school-of-humanities-social-sciences"> Dana Basnight- Brown</a> and<a href="https://corelab.io/"> Patrick Forscher</a>.&nbsp; <p></p>
<p>We call for researchers from Africa to serve as collaborators in a pilot study (using the CREP framework for a one-study project) and researchers from Africa, Europe, and North America for the main study (ManyLabs: Africa). As part of this project, we will provide online training / webinar courses on open science access and tools to African researchers.&nbsp;                                                                                                  </p><p>Collaborators can earn authorship for data collection, translation, and coordination of their research unit. Other activities could include consultation on study/effects nomination and evaluation.                                                                                                     </p><p>Interested researchers can sign up<a href="https://docs.google.com/forms/d/e/1FAIpQLSd5dytA4zjRaw4oOzoQUgW4PJ6BUgehVM7CXLO-TOkjfzLRgw/viewform?usp=sf_link"> here</a>. For further information, please contact Adeyemi Adetula at adeyemiadetula1@gmail.com.</p></li></ul>
<!-- /wp:html -->

<!-- wp:paragraph -->
<p><strong>Two Opportunities from Balazs Aczel:&nbsp;</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>Balazs Aczel's lab advertises a collaboration opportunity to find out why people violate lock down. Join the project if you can organize online data collection in your country to extend the multinational datasets. Collaborators are expected to collect data (min 350 pps) from a country with some level of current lock down. <strong>More info:&nbsp; </strong><a href="https://tinyurl.com/ConfinementNonadherence"><strong>https://tinyurl.com/ConfinementNonadherence</strong></a></li></ul>
<!-- /wp:list -->

<!-- wp:list -->
<ul><li><strong>Research on how you cope with home-office</strong></li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Our team would like to explore how researchers cope with working from home now and in general. This is a great opportunity for the research community to change old routines and optimize the time they spend in the office and work from home. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>From our survey results, we will create recommendations for institutions on how to support researchers' efficiency and work-life balance regarding their options and condition in remote working. After responding, you can sign up to win a <strong>100 USD</strong> Amazon (or your choice) voucher. If your region was in recent lockdown, please share your experience with home-office in this <strong>~4-min </strong>anonymous survey. <strong> Follow this link to the</strong><a href="https://elteppk.eu.qualtrics.com/jfe/form/SV_0ctBMsqd6ytUM5v"> Survey.</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><p>We appreciate it if you share this survey with your colleagues. Thank you for your support.</p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Balazs Aczel,  ELTE, Hungary</p>
<!-- /wp:paragraph -->
