---
title: "News from the Accelerator- October 2020"
date: 2020-10-28
---

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:paragraph -->
<p><strong>Study Capacity Policy up for a Vote</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>In an effort to more systematically assess our study acceptance capacity, we have drafted  a new PSA policy document. All members of the PSA, please read this<a rel="noreferrer noopener" href="https://docs.google.com/document/d/1hdJesAgxjhgjRUUXFd3QQDcfouRPH1W2sdZRKlxbsME/edit?usp=sharing" target="_blank"> document,</a> and then vote yes or no, by logging into the <a rel="noreferrer noopener" href="https://member.psysciacc.org/" target="_blank">member site</a> and finding the voting form under the "your tasks" heading on the main page.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:paragraph -->
<p><strong>Data Collection Updates</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li><strong>PSA 004:</strong> We have 2640 participants in over 50 labs. The deadline to sign up is past, but if your lab hasn't started data collection then we will need you to start by November 15. Data collection ends in December.&nbsp;</li></ul>
<!-- /wp:list -->

<!-- wp:list -->
<ul><li><strong>PSA 006:</strong> 006 is in the final stages of data collection. We are going strong but are not accepting any new labs at this time. Data collection is set to end at the end of 2020.</li></ul>
<!-- /wp:list -->

<!-- wp:list -->
<ul><li><strong>PSACR 001/002/003:</strong> Data collection for the PSACR bundle was completed on October 23rd! Considering people who completed at least 90% of questions on a given component of the survey, our estimated <em>Ns </em>are: 44,217 for the general questions; 16,618 for Study 1 (Loss Gain); 20,805 for Study 2 (Cognitive Reappraisal); and 18,594 for Study 3 (Self Determination). We also met our goal for Study 2 of having 35 countries with <em>N </em>&gt;= 200<em>.</em> Anyone can explore Ns by study, language, and different percent completion thresholds at <a href="http://formr.psysciacc.org/shiny/shiny_app/">http://formr.psysciacc.org/shiny/shiny_app/</a>.</li></ul>
<!-- /wp:list --></div></div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:paragraph -->
<p><strong>Publication Updates&nbsp;</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li><strong>PSA 001:</strong> The final copy of the paper has been accepted and we are working on responding to the various editorial formatting requests prior to publication! This is our first study to have a final, Stage 2, acceptance.</li></ul>
<!-- /wp:list -->

<!-- wp:list -->
<ul><li><strong>PSA 002/003: </strong>We are currently waiting on the journal editor’s comments about the modifications we made earlier. He will give us their decisions and suggestions in a few days, so we will have a lot of editing to do soon!</li></ul>
<!-- /wp:list -->

<!-- wp:list -->
<ul><li><strong>PSA 005:</strong> We have received Stage 1 acceptance at Nature Human Behavior! <a href="https://psyarxiv.com/6hju9/">Here</a> is a preprint of the manuscript if y’all want to give it a read!</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:paragraph -->
<p><strong>Training Committee&nbsp;Update</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>We are trying to get some feedback from you all on what kind of training you think you need in order to be successful in the PSA and the many studies. <a href="https://docs.google.com/forms/d/e/1FAIpQLSel88f6kNbkmPslGPc90q877Etcf_-ptTqMA2iLzkpIKAjG-w/viewform">Here</a> is a google form you can all fill out to provide some feedback on what you think would be helpful.&nbsp;</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:paragraph -->
<p><strong>Community Building and Network Expansion Committee Update</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>From Crystal: </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>We have a position opening in the Community Building and Network Expansion Committee in December. We really hope folks from non-US/CA/EU areas consider going for the position. Having someone from these geographic regions in a leadership role, especially for this committee, is crucial for PSA's growth and development. I will miss being CBNEC assistant director but I am SO excited about seeing where new leadership can take this committee and the PSA in general.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>If you think you might be even kinda sorta interested in this position, please DM me on Slack or email me at cnsteltenp@usi.edu! I'd love to chat about the group and brainstorm on where it can go from here!&nbsp;&nbsp;</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->

<!-- wp:group {"padding":"no"} -->
<div class="wp-block-group has-no-padding"><div class="wp-block-group__inner-container"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:paragraph -->
<p><strong>Gathering feedback on a possible PSA translation service </strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>PSA member, Adeyemi Adetula, would like to solicit your feedback on potential demand for a paid translation service for African languages in terms of interest and to assess available funds to dedicate to such a service.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>In general, there is little research on African populations in psychology. Even in the Psychological Science Accelerator (PSA), African participation in multi-site studies has been poor, with a recent project including just two&nbsp;(out of several thousand) African indigenous languages. To facilitate inclusion and improve generalizability of psychology, we propose a paid translation service for African languages and thereafter offer a more general translation service (for full details regarding this service, see <a href="https://corelab.blog/psatranslation/">here</a>).</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Who could use this service?</strong> Any researcher interested in conducting research amongst African populations.&nbsp;&nbsp;&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>What do I stand to benefit?</strong> First, users would get a high-quality translation. Quality of these translations is of high priority and we intend to adopt the already established translation procedures of the PSA. This procedure required a forward translation (source to targeted language), a back translation (serving as validation), editing (reconciling text difference of first version and validation version), external reading (feedback from potential respondents), cultural adjustment, proofreading, and implementation (transfer of translated note into a survey software). Second, such a translation service allows one to conduct research in African populations as we will also try to connect users with local researchers.&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Survey.</strong> We invite you to give us feedback on this proposed service via this short (5 minute) <a href="https://survey.eu.qualtrics.com/jfe/form/SV_2ayaVaYccAsuKsB">survey</a> (if you are instead interested in being a translator, you can fill in the survey <a href="https://survey.eu.qualtrics.com/jfe/form/SV_5hH4NjtBNHVGu7H">here</a>).</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group --></div></div>
<!-- /wp:group -->
