---
title: "24 Hours to Vote on 11 Possible Studies for the PSA COVID-19 Rapid and Impactful Project"
author: "Chris Chartier"
date: 2020-03-18
categories:
  - mailchimp backup
---

Accelerators,


I’m writing with an update on the PSA COVID-19 Rapid and Impactful Studies project. We received 66 submissions (!!!) from an amazing group of proposing authors all around the world. A small group of us (Hans IJzerman, Charlie Ebersole, Dana Basnight-Brown, Erin Buchanan, Heather Urry, and I) have selected 11 submissions to move on to the next phase of selection.

We now ask all network members to vote and provide comments on the submissions so that we can make final selection decisions. Feel free to vote “yes” on all studies that you think the PSA will support (you could vote “yes” for 0 studies, all 11 studies, or any number in-between). We are trying to move as quickly as possible, given the urgency of the situation and have set a 24 hour deadline for voting. Thus, voting will stop at 2:00 PM UTC on March 19th.

To vote, log in or create an account at the membership website: https://member.psysciacc.org/. On the homepage, under Tasks, click on the link “Vote on COVID Rapid”. Once you get to the voting page, you can download the submissions using the “Click here to download the study proposals” link. The submission order has been randomized, so please match the name of the submission PDF to the submission name on the voting page.

Join the PSA slack (https://join.slack.com/t/psych-sci-accelerator/shared_invite/zt-6xdadc02-JKn5bEPNMN8vliJlAJBU5w) to get involved in the conversation and consider donating to support these studies (https://psysciacc.org/news/2020-03-18_support-the-psa-covid-19-rapid-and-impactful-studies-with-a-donation.html) !

Thank you for all the amazing things you are doing right now. We are overwhelmed and humbled by the response and action from this community.

