---
title: "Accelerator News - May 2020"
author: "Chris Chartier"
date: 2020-05-21
categories:
  - mailchimp backup
---

Accelerators,



It’s been a very productive and exciting 3 months since our last newsletter update. First, there are now well over 1,000 (!!!) of us signed on as members of the PSA. Second, we announced, selected, prepared, and then launched 3 COVID Rapid Response studies. Third, we’ve made progress on announcing our next batch of “normal” studies. Finally, we have updates to report on studies PSA 001 through PSA 006. This newsletter is a bit longer than normal in order to get all of us, new members and longtime members alike, up to speed on many of our current studies, future studies, and other initiatives.



You can read the newsletter here. (https://psysciacc.org/news/2020-05-21_news-from-the-accelerator-may-2020.html)

As always, thank you so much for all of the inspiring energy, humbling dedication, and insightful expertise that you bring to the PSA and its projects!
