---
title: "Assessing Translation Capacity"
author: "Chris Chartier"
date: 2020-07-22
categories:
  - mailchimp backup
---

Assessing Translation Capacity

Accelerators,

Our experience thus far with the PSA Rapid-Response COVID-19 studies has revealed that the PSA can accomplish a truly exceptional amount of collective work and data collection quite quickly (more updates on getting the studies "across the finish line" coming soon!). But a need also emerged, recognized by Ilker Dalgar, Miguel Silan, and Max Primbs, to better assess and organize the network’s translation capability. Thus, the Translation and Cultural Diversity Committee (TCDC) would like to collect data on the translation capacity of the PSA for future projects: in which countries and for which languages do we have adequate potential translators? This knowledge will help us to determine our potential capacity, or lack-there-of, in many possible data collection languages, and thus make better plans for future projects.

Please answer this very short, 1-minute survey, to help us. Thank you!!
Link:  https://docs.google.com/forms/d/e/1FAIpQLSfkWhCPl_Zj1o4EhW3jdwGRLo0Wd9h4aMOW9wXk9wt9CLpYiw/viewform (https://slack-redir.net/link?url=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLSfkWhCPl_Zj1o4EhW3jdwGRLo0Wd9h4aMOW9wXk9wt9CLpYiw%2Fviewform)
