---
title: "News from the Accelerator- July 2020"
date: 2020-07-24
---

<!-- wp:paragraph -->
<p>July has been extremely active in the PSA, and this newsletter contains updates on many projects, but we’d like to highlight two things up front:</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>First, the PSA has taken a very big and important step as an organization this month by initiating our first truly democratic election for an open Associate Director position! You can read the candidates’ statements at the links below to prepare for the vote.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Second, we are continuing data collection on the PSA-Covid-Rapid studies as long as we can afford to, which is likely through the end of August. The team could use some more data collection help to make sure we clear our pre-registered N targets! &nbsp;Email psacovid@gmail.com if you are interested in joining or have questions about joining.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Election</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The two candidates in our election for an open Associate Director position, Peter Mallik and John Protzko, have provided written statements describing why they've chosen to run, and describing what they'd like to achieve in the Associate Director role if elected.&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>You can read each statement by clicking the candidate's name here: <a href="https://osf.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&amp;id=b3ade8bed0&amp;e=2a954b69c4">Mallik</a> and <a href="https://osf.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&amp;id=6e158964fc&amp;e=2a954b69c4">Protzko</a>. Additionally, we have posted each statement in dedicated slack channels. I encourage all members to read them, consider them carefully, and ask any questions you have for the candidates! You can ask questions by joining the PSA slack workspace at <a href="https://osf.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&amp;id=43dbddd38d&amp;e=2a954b69c4">this link</a>, and then joining the #associatedirectorelection_protzko and #associatedirectorelection_mallik channels. The slack discussion closes today, but you can read the questions and answers throughout the election. Soon, we will email each PSA member with instructions about how to vote.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Conference</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Approximately ⅔ of the available seats are full, so make sure to <a href="https://osf.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&amp;id=77613ed75a&amp;e=fad273e495">register now</a> to claim your spot if you’d like to attend. We have a recent surge of attendees requesting free admission, and would very much like to to be able to fill all requests, so we would be very grateful if a few additional members were able and willing to pay the $60 admission fee to open up more free spots. Also, the program is&nbsp; slowly but surely filling up. If you have work or ideas you would like to present at the conference be sure to fill out of new <a href="https://osf.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&amp;id=2ba832a3cc&amp;e=fad273e495">submission form</a>! We’ve started a <a href="https://osf.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&amp;id=0517f472ef&amp;e=fad273e495">general info page</a> that highlights a few presentations already set and links out to the current draft program. We hope to have the full program set in late August and will share an update with the full network when it is ready to go!</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Current Studies</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li><strong>PSA 001- </strong>The Stage 2 Registered Report has been resubmitted to Nature Human Behaviour. Now we are waiting for the final decision from the editor.</li><li><strong>PSA 002/003-</strong> The 002 and 003 teams are in the final stages of moving our experiments from Open Sesame/Qualtrics to Lab.JS. Thanks to the hard work of Merle Schuckart, we have drafts of the new programs and are in the process of ensuring that the web versions of the studies retain fidelity to the original protocols and troubleshooting the studies. The new version of the experiment should fully integrate both the 002 and 003 procedures into one online protocol, greatly simplifying future data collection.</li><li><strong>PSA 004- </strong>Data collection has slowed down as many members’ universities have concluded their semesters. We do however need more CREP reviewers as we wrap up this project at the end of the year. CREP reviewers look over each lab’s OSF page to ensure that each lab is performing the study as planned. If you or someone else is interested please have them fill out this <a href="https://docs.google.com/forms/d/e/1FAIpQLSdB7BDtPSI6q_7UxeUcqy4EKNxtYazZwR7P9SVbVKmd6rFBlg/viewform">form</a>.</li><li><strong>PSA 005- </strong>005 is waiting on a decision on our Stage 1 submission at Nature Human Behaviour.</li><li><strong>PSA 006- </strong>006 is continuing data collection and is slated to finish sometime between October and December. We continue to have new labs join and are extremely excited to finish up this year!</li><li><strong>PSACR 001/002/003- </strong>The PSACR bundle is still collecting data. We now have over 19,000 participants (i.e., people who have completed the general questions about the pandemic and participated in one or more of the study surveys). The survey is offered in 38 (!!) languages and dialects, with a handful more to be implemented very soon. We are still planning to collect data as long as we can afford to, which we expect to be through August. We are also welcoming new labs to join data collection if they use one of the languages we've translated already (see here for a list of implemented and soon-to-be implemented languages <a href="https://slack-redir.net/link?url=http%3A%2F%2Fformr.psysciacc.org%2Fshiny%2Fshiny_app%2F">http://formr.psysciacc.org/shiny/shiny_app/</a>) . Email psacovid@gmail.com if you are interested in joining or have questions about joining.</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p><strong>A Chapter on the PSA, QRPS, and Clinical Psych</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>A group of PSA members, led by Julie Beshears, are beginning work on an invited chapter about the PSA and how the PSA's design can affect the presence of questionable research practices (QRPs) in clinical psychology research.&nbsp; Ideally, they are seeking individuals with clinical experience, but other contributions are welcome.&nbsp; If this project interests you, you may join the slack channel (proj_clinical_chapter) or email Julie at <a href="mailto:jebeshears@eagles.usi.edu">jebeshears@eagles.usi.edu</a>.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>Committee Updates</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li><strong>Ethics committee- </strong>We would like to congratulate our newest Assistant Director of the ethics committee!! Mike Mensink was just appointed the position last week and seems very eager to start in his new position. Welcome Mike and we look forward to collaborating with you soon!</li></ul>
<!-- /wp:list -->

<!-- wp:list -->
<ul><li><strong>Translation and Cultural Diversity Committee-</strong> The Translation and Cultural Diversity Committee (TCDC) would like to collect data on the translation capacity of the PSA for future projects: in which countries and for which languages do we have adequate potential translators? This knowledge will help us to determine our potential capacity, or lack-there-of, in many possible data collection languages, and thus make better plans for future projects.&nbsp;Please answer this very short, <a rel="noreferrer noopener" href="https://docs.google.com/forms/d/e/1FAIpQLSfkWhCPl_Zj1o4EhW3jdwGRLo0Wd9h4aMOW9wXk9wt9CLpYiw/viewform" target="_blank">1-minute survey</a>, to help us. Thank you!!</li></ul>
<!-- /wp:list -->

<!-- wp:list -->
<ul><li><strong>Project monitoring Committee-</strong> The member website is receiving an update soon. A big shout out to the fantastic Erin Buchanan for helping the team find a way to manage projects through Canvas. Erin will be going over this update and much more at the conference in September, so make sure you check that out for more information!</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p><strong>Recorded for the Chinese Open Science Network Available Online&nbsp;</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Chris Chartier recently gave a talk to the Chinese Open Science Network. They recorded the presentations and have <a href="https://www.bilibili.com/video/BV1nZ4y1W7Ee?p=4">posted it here</a>, so anyone can watch and reach out with any questions or feedback (<a href="mailto:cchartie@ashland.edu">cchartie@ashland.edu</a>).&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><em>Thank you for all that you have, and continue to do, on behalf of the PSA. Onward!</em></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong><em>Savannah and Chris</em></strong></p>
<!-- /wp:paragraph -->
