---
title: "News from the Accelerator - February 2020"
date: 2020-02-27
---

<h2>Election for Associate Director</h2>
<span style="font-weight:400;">The PSA will soon have an election for the position of Associate Director. Associate Directors serve as a steering body for the PSA as well as functioning as liaisons between the various committees and lead teams on specific studies. We are seeking nominees for that election. If you’d like to nominate yourself or someone else, please fill out the form linked below before March 19th. We’ll reach out to all nominees to confirm whether or not they’d like to run for this office.</span>

<span style="font-weight:400;">The PSA is also seeking members to volunteer as Election Tellers for the upcoming election. The role of a Teller is to provide accountability and ensure fairness in the election process. Tellers will be included on all official election communications and be given access to all election materials, including the final ballots. Tellers will be responsible for ensuring that the Associate Director overseeing the election (in this case, Charlie Ebersole) is following all PSA procedures fairly. They will also certify that the final vote count is accurate. This job should require minimal week-to-week effort distributed over the next three months. </span>

<span style="font-weight:400;">Any member of the PSA is eligible to run for Associate Director or be an Election Teller. The only restriction is that candidates in the election are ineligible to be Tellers (so if you are thinking of running for Associate Director, don’t volunteer to be a Teller). If you’d like to nominate someone for the Associate Director election or volunteer to be a Teller, please fill out </span><a href="https://docs.google.com/forms/d/e/1FAIpQLScZwL9RDFnbwyer-02mxqbPldNWrMiLQPGMxftv7_KyALCAxw/viewform?usp=sf_link" target="_blank" rel="noopener">this form</a><span style="font-weight:400;"> by March 19th. This <a href="https://docs.google.com/document/d/1mYczplmaqAecQHfkmMYI4zrF77I4Vl4zZujipihirtQ/edit" target="_blank" rel="noopener">policy document</a> contains much more info about the timeline and logistical steps of PSA elections. Also, if you have any questions about either position, don’t hesitate to reach out to me (cebersole@virginia.edu). </span>

<span style="font-weight:400;">Thanks!</span>

<span style="font-weight:400;">~Charlie Ebersole</span>
<h2>Studies 001 through 006</h2>
We also have a few exciting updates on our in-progress studies.
<ul>
	<li>001. The lead team is on the verge of submitting a revised version of our Stage 2 manuscript to <em>Nature Human Behaviour</em> and hope to have it officially accepted soon!</li>
	<li>002. We are very close to finishing data collection and will quickly turn our attention to data analysis and Stage 2 manuscript drafting when collection wraps up.</li>
	<li>003. This project is bundled with 002 for data collection, and is thus also close to wrapping up. We did not follow a registered report model for this study, so we will begin drafting a traditional manuscript for it in the near future. Target journal tbd.</li>
	<li>004. Data collection will close for this study in June, so now is the time to jump on board if you'd like to contribute! Email us for more info about joining!</li>
	<li>005. The lead team is working hard to finish up a second round of "revise and resubmit" with <em>Nature Human Behaviour</em>. Stay tuned for data collection commencement timeline and plans after we get that IPA :)</li>
	<li>006. The stage 1 RR manuscript for this study was accepted in principle at <em>Nature Human Behaviour</em> this month! Congrats to all our co-authors!! The team is now working hard on translations and finalizing materials to commence data collection very soon.</li>
</ul>
<h2>Coming soon</h2>
Lastly, be on the lookout for action and opportunities in the following areas in March.
<ul>
	<li>Study Selection provisional decisions will be sent this coming month. We can't wait to inform submitting authors and then share the news within the network (wider public announcements will come after some initial preparation and eventual official acceptances are extended).</li>
	<li>Related to the point above, the Project Monitoring Committee will be looking for new project monitors to serve on these new projects (likely 2-3 new studies). You can reach out to Hannah Moshontz and/or Jordan Wagge on Slack for more info!</li>
	<li><span style="font-weight:400;">The Community Building and Network Expansion Community is planning some cool new recruitment and community building activities for 2020. They could really use some additional committee members to help plan and execute these. Please reach out to Crystal Steltenpohl and/or Natalia Dutra if you are interested.</span></li>
	<li>Crystal is also leading the organization of a global engagement task force for the Society for the Improvement of Psychological Science. She welcomes other PSA members to join in that effort if they are so inclined!</li>
</ul>
