---
title: "Associate Director Election Candidate Statements Available"
author: "Chris Chartier"
date: 2020-07-14
categories:
  - mailchimp backup
---

Accelerators,

The two candidates in our election for an open Associate Director position, Peter Mallik and John Protzko, have provided written statements describing why they've chosen to run, and describing what they'd like to achieve in the Associate Director role if elected.

You can read each statement by clicking the candidate's name here: Mallik (https://mcusercontent.com/f8bacf294e5a46e350b638374/files/11e272b7-117a-4629-908d-5780fa4c204d/Mallik_Statement.pdf) and Protzko (https://mcusercontent.com/f8bacf294e5a46e350b638374/files/1dc19722-c622-47da-b43d-567445cfa7d9/Protzko_Statement.pdf). Additionally, we have posted each statement in dedicated slack channels. I encourage all members to read them, consider them carefully, and ask any questions you have for the candidates! You can ask questions by joining the PSA slack workspace at this link (https://join.slack.com/t/psych-sci-accelerator/shared_invite/zt-6xdadc02-JKn5bEPNMN8vliJlAJBU5w) , and then joining the #associatedirectorelection_protzko and #associatedirectorelection_mallik channels. The discussion will continue until July 24th, at which point we will close the channels and proceed with the vote via email to all members.

Let me know if you have any questions about the election process!
