---
title: "Register now to reserve your “seat” for the 2020 Virtual Meeting of the Psychological Science Accelerator"
author: "Chris Chartier"
date: 2020-06-02
categories:
  - mailchimp backup
---

Register now to reserve your “seat” for the 2020 Virtual Meeting of the Psychological Science Accelerator

Accelerators,

The dates are set for the 2020 Virtual Meeting of the Psychological Science Accelerator (https://psysciacc.org/the-2020-virtual-meeting-of-the-psychological-science-accelerator/) ! We welcome you to join the PSA community on September 8-10 for three days of presentations, discussions, hack-a-thons, and informal social sessions. We are planning an interactive conference to allow our members to meet each other, network, share ideas, and collaborate. Each day of the conference will feature programming over a 12 hour period (starting at 12:00 UTC) to allow attendance by folks from all time zones and to give ample opportunities for attendees to pop in and out as their schedule allows.

For now, we have the capacity to accommodate 300 total attendees, so be sure to fill out the form linked below to reserve your seat. If demand far exceeds this cap, we will explore ways to expand the size and scope of conference. The registration fee is set at $60, BUT, for every fees-paying registered attendee we will reserve two completely free spots. All attendees can request a letter of participation from us if this will help with reimbursement from your institution. We hope this allows attendees who can be reimbursed by their institutions to pay for registration, while still allowing those without such funding to attend and participate in our conference.

You can register at the link here: https://psysciacc.org/the-2020-virtual-meeting-of-the-psychological-science-accelerator/

We will release details of the conference as they develop further, but you can expect a full program for the conference in early August. We will be sure to reserve ample time in the schedule for discussions and sessions that organically develop during the meeting.

We can’t wait to see you in September!
