---
title: "Conference updates. 53 days to go!"
author: "Chris Chartier"
date: 2020-07-16
categories:
  - mailchimp backup
---

Conference updates. 53 days to go!

Accelerators,

The PSA conference is only 53 days away and we have some updates for y'all.

First, approximately half of the available seats are full, so make sure to register now (https://psysciacc.org/the-2020-virtual-meeting-of-the-psychological-science-accelerator/) to claim your spot if you’d like to attend. Thus far, the ratio of ⅓ paying attendees to ⅔ free seats is working out relatively well, so we’ve been able to honor almost all requests for free attendance.

Second, the program is also filling up slowly but surely. We’ve now created a submission form (https://psysciacc.org/the-2020-virtual-meeting-of-the-psychological-science-accelerator/psa-vc-2020-call-for-presenters/) , so you can suggest additional full sessions or single presentations. We have 4 suggested session/presentation types listed on the form, but the online conference format allows a lot of flexibility, so feel free to submit an idea that doesn’t quite “fit the mold” :).

Lastly, we’ve started a general info page (https://psysciacc.org/psa-2020-conference/) that highlights a few presentations already set and links out to the current draft program. We hope to have the full program set in late August and will share an update with the full network when it is ready to go!

We can’t wait to virtually gather soon!
