---
title: "Upcoming PSA Elections"
author: "Heather Urry"
date: 2021-02-04
categories:
  - mailchimp backup
---

Upcoming PSA Elections

* Accelerators,


The Psychological Science Accelerator (PSA; https://psysciacc.org) will soon have an election for two leadership positions in the organization, Director and Associate Director.

The Director works with the Associate Directors as a steering body for the PSA. Together they make decisions as well as function as liaisons between the various committees. As described in Moshontz et al. (2018) (https://journals.sagepub.com/doi/10.1177/2515245918797607) , the Director additionally “oversees day-to-day operations and evaluates the functioning and policies of the PSA with respect to the core principles” (p. 505) of diversity and inclusion, decentralized authority, transparency, rigor, and openness to criticism.

Any member of the PSA is eligible to run for Director or Associate Director. The only restriction is that candidates in the election are ineligible to be Tellers. (We have already identified three volunteers to serve as Tellers; they will ensure the integrity of the election process and outcome.)

If you’d like to nominate yourself or someone else for the Director or Associate Director election, please fill out this form (https://docs.google.com/forms/d/e/1FAIpQLScZwL9RDFnbwyer-02mxqbPldNWrMiLQPGMxftv7_KyALCAxw/viewform?usp=sf_link) on or before Monday, February 15, 2021. We’ll reach out to all nominees to confirm whether or not they’d like to run for office.

If you have any questions about either position, feel free to email me (heather.urry@tufts.edu).


Thanks!
