---
title: ""
date: 2021-09-30
---

<!-- wp:heading {"level":3} -->
<h3><strong>Elections</strong></h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>The Psychological Science Accelerator (PSA) is accepting self-nominations for Assistant Directors of our Project Monitoring, Data &amp; Methods, Study Selection, and Funding Committees! Assistant Directors directly shape the direction of the PSA any many ways, including (a) helping establish committee-specific vision plans to help the PSA achieve its mission and adhere to its core principles, (b) overseeing day-to-day committee-specific operations, and (c) providing regular updates to the PSA Director and Associate Directors about progress and problems. They are elected by majority vote by the PSA Board of Directors and serve 3 year terms. All who are interested are encouraged to apply here: https://forms.gle/ZNyhZCz4GenazbYG6</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3><strong>Study updates:</strong></h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul><li><strong>PSA-002 (Object Orientation): </strong>The lead team has submitted the manuscript to PBR and is now awaiting feedback.</li><li><strong>PSA-003 (Gendered Prejudice): </strong>The lead team is finalizing translation and preparing for data analysis. Thanks to all who reached out following the last newsletter's request for help with translation!</li><li><strong>PSA-004 (Accelerated CREP):</strong> The lead team is currently working on data processing, data analysis, and authorship credit tracking. They are also looking for people to code open ended responses for Chinese, Russian, and Greek.&nbsp;</li><li><strong>PSA-005 (Stereotype Threat): </strong>Data collection will resume on October 11, 2021. The lead team has created a checklist on Canvas to guide labs in preparations for data collection. Each collaborator should have been added to the Canvas course. If you have not please email <a href="mailto:psa005stero@gmail.com">psa005stero@gmail.com</a>!</li><li><strong>PSA-006 (Trolley Problem):</strong> The lead team has submitted the Stage II submission to <em>Nature Human Behavior.</em></li><li><strong>PSA-007 (SPAM-L):</strong> SPAML is still recruiting collaborators, with contribution opportunities available through the <a href="https://docs.google.com/document/d/1VKR-7csBlL-lGOTbRTnlmaYkqi8bj2FhYtvbzEN25Wk/edit?usp=sharing">Words2Many</a> and <a href="https://docs.google.com/document/d/1xslViVFZrapUG75mwsF2eijFoQqm5GABoOf9ekIweH4/edit?usp=sharing">Subs2Strudel</a> pre-projects. The lead team has begun the first rounds of the registered report and will soon be sending these out to contributor for feedback. If you are interested in becoming a collaborator or want to learn more about 007 please email <a href="mailto:007spaml@gmail.com">007spaml@gmail.com</a></li><li><strong>PSA-COVID Rapid Bundle (001/002/003)-</strong>&nbsp;<ul><li>PSACR001 has been submitted to Affective Science.</li><li>PSACR002 has been&nbsp; <a href="https://doi.org/10.1038/s41562-021-01173-x">published in Nature Human Behavior</a>.</li><li>PSACR003 was resubmitted to PNAS.</li></ul></li></ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3><strong>PSACON</strong></h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong>Today is the last day to submit a </strong><a href="https://psysciacc.org/psa-conference-2021-call-for-presenters/"><strong>presentation</strong></a> to the second annual PSA CON!! October 27th is the deadline for <a href="https://psysciacc.org/the-2021-meeting-of-the-psychological-science-accelerator/">registration</a>. See you all there!</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3><strong>Canvas</strong></h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>The PSA is slowly integrating our new membership website to Canvas. We will be starting to add in every member in the next couple of months. Be sure to check your inbox for your invitation.&nbsp;</p>
<!-- /wp:paragraph -->
