---
title: "PSA Voting Instructions"
author: "Heather Urry"
date: 2021-04-05
categories:
  - mailchimp backup
---

Accelerators,

The two-week voting period for the current PSA election will begin as of Monday, April 5, 2021 at 12:00 PM UTC. At that time, members may vote by logging in to the PSA Member Website (https://member.psysciacc.org/login.php). The ballot will appear as one of Your Tasks on the home page. Please vote directly from that home page.

Here is a list of the candidates with links to their statements and the names of their Slack workspace channels. I will archive the Slack channels when the voting period begins; this will signal the end of campaigning. (Candidate statements will remain available during the voting period.)

Associate Director (rank candidates; two positions to fill)

Erin Buchanan (https://drive.google.com/file/d/1r4RGEngabbdsVusQxxJQZCixuPY_3Upz/view?usp=sharing) (#candidate-ad-buchanan)

Lisa DeBruine (https://drive.google.com/file/d/1gSrhTWiNS-xFEFb4FOfeE3K0S7iofDQZ/view?usp=sharing) (#candidate-ad-debruine)

Jessica Flake (https://drive.google.com/file/d/1fkCXklQW50Gtgn-ZH5RuNG6iJ184MGYw/view?usp=sharing) (#candidate-ad-flake)

Hans IJzerman (https://drive.google.com/file/d/1MNUq3tlVnfLRwzpiPo37vH2jn9KdMp7T/view?usp=sharing) (#candidate-ad-ijzerman)

Sandy Onie (https://drive.google.com/file/d/1vlhA_3YmJs3QQTKWNPeIjclEmb-s5gwy/view?usp=sharing) (#candidate-ad-onie)

Gerit Pfuhl (https://drive.google.com/file/d/1FWBU2igrt1Gyk_A-YyDlMKEIC-x28eco/view?usp=sharing) (#candidate-ad-pfuhl)

Rima-Maria Rahal (https://drive.google.com/file/d/1c0KNSN-2r0N7DkotoFWjsflKMmPA2Jst/view?usp=sharing) (#candidate-ad-rahal)


Director (vote of confidence)

Nicholas Coles (https://drive.google.com/file/d/1S_zFoBy2brNNi78plm5771eftvlM7pcW/view?usp=sharing) (#candidate-d-coles)


Best,
