---
title: "News from the Accelerator- January 2021"
date: 2021-02-01
---

<!-- wp:paragraph -->
<p>The first month of 2021 is over and we have had quite a month! We kicked off 2021 with our first published study and we enter into some new and exciting transitions ahead of us. We look forward to seeing what else this year will bring.&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":4} -->
<h4><strong>Study updates:</strong></h4>
<!-- /wp:heading -->

<!-- wp:list -->
<ul><li><strong>PSA 001- </strong>This project is now officially <a href="https://www.nature.com/articles/s41562-020-01007-2">online</a> at Nature Human Behaviour! This puts a bow on the PSA’s first empirical project. Congratulations to the whole study team for this enormous accomplishment. You can read some reflections from the leadership team of the project on the <a href="https://socialsciences.nature.com/posts/promises-and-challenges-of-big-team-psychology">Nature blog</a>.&nbsp;</li><li><strong>PSA 002/003- </strong>The leadership team for the 002/003 bundle of studies has been hard at work, creating an online version of the 002 study protocol that will not rely on in-person data collection. This new protocol was recently approved by the editors of the Psychonomic Bulletin and Review. We are now testing the 002 online link.&nbsp;</li><li><strong>PSA 004-</strong> 004 is wrapping up data collection at a few sites but are no longer taking any new labs. We'll be reaching out to contributors in February or March.</li><li><strong>PSA 005- </strong>We’re waiting on vaccine distribution to get to a place that allows in-person data collection again. This summer, we’ll evaluate whether in-person data collection is likely to be feasible in fall 2021.</li><li><strong>PSA 006-</strong> Final analyses are being completed and the manuscript is being written.</li><li><strong>PSA 007- </strong>We are putting together the website for people to get started on this project. As soon as that is finished we will send out the onboarding email. If you would like to be a part of the pre-projects, please email <a href="buchananlab@gmail.com">Erin Buchanan</a>!</li><li><strong>PSACR Bundle- </strong>The submitting author teams are hard at work analyzing data and writing their manuscript drafts! Meanwhile, we (the admin team) are developing a data management plan (figuring out exactly how and when we will share the data). We also, on an ongoing basis, are working to make sure that everyone’s contributions are accurately documented.</li></ul>
<!-- /wp:list -->

<!-- wp:heading {"level":4} -->
<h4><strong>Chris Farewell:</strong></h4>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>This past month we received news that Chris Chartier has resigned from his role as PSA Director. Chris guided the PSA from an idea to a vibrant organization with more than 1400 members. Although he will no longer be the PSA’s director, he may yet transition into a different PSA role. In the meantime, Charlie Ebersole will serve as acting Director of the PSA and we will begin the process of holding an election for a new Director.&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Below you will find Chris’s farewell message to the PSA.&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“I can’t wait to watch, and support, the PSA through this transition and into the next chapter of it’s growth. I'm a bit sad to step away from this role, because it has been such a personal joy to serve in this way, but I'm also very excited to see all the amazing things the PSA will accomplish with a new Director who can give the organization the energy, attention, and care it deserves.&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>I've enjoyed working with each and every one of you immensely. Thank you from the bottom of my heart for making these last 3 and a half years of my life so special and meaningful. It's a period of my life that I will always cherish and look back on fondly. I won't be disappearing from the PSA of course, but I'm not yet sure what my next role/type of contribution will be.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>As for the practical matters of this transition, <a href="https://psych-sci-accelerator.slack.com/team/U7DD99J4D">Charlie Ebersole</a> will serve as Interim Director until the Associate Directors group can complete an election process for the new Director (thank you, Charlie!!).</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Onward!”</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":4} -->
<h4><strong>Appointments and Elections:</strong></h4>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>The PSA will be replacing several of its leadership positions in the coming months.&nbsp; Below is a quick rundown of each.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":5} -->
<h5><strong>Assistant Directors</strong></h5>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>The Assistant Director positions are replaced by appointment of the Associate Directors. We have openings for positions in the following six committees:</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>Funding</li><li>Ethics</li><li>Community Building and Network Expansion</li><li>Data and Methods</li><li>Training</li><li>Translation and Cultural Diversity</li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>After January 30th, the Acting Director and the Associate Directors will select the new Assistant Directors from among the nominees.. If you have any questions about this application or this process, contact the Acting Director, Charlie Ebersole, at <a href="mailto:cebersole@virginia.edu">cebersole@virginia.edu</a>. .</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":5} -->
<h5><strong>Director and Associate Director</strong></h5>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>This Spring, the PSA will be electing a new Director and one Associate Director. These positions will be filled by a direct election from the PSA network. Any PSA member may run for these positions.&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Later this month, the PSA leadership will solicit nominations (self or others) for these roles and we plan to conduct the election process over the next two months. If you have any questions about the election process or what’s involved in the positions, contact the Acting Director, Charlie Ebersole, at <a href="mailto:cebersole@virginia.edu">cebersole@virginia.edu</a>.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":4} -->
<h4><strong>Reflections on funding the PSA</strong></h4>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Funding lead Patrick Forscher and Associate Director Hans IJzerman published <a href="https://psysciacc.org/2021/01/11/how-should-we-fund-the-psa/">a blog</a> reflecting on how to fund the PSA. This blog follows up on two previous blogs, one that reflects on the <a href="https://psysciacc.org/2020/12/04/how-many-resources-does-the-psa-possess/">PSA’s resources for running studies</a>, and a second that reflects on the <a href="https://psysciacc.org/2020/12/11/the-financial-cost-of-the-psas-vision/">financial cost of the PSA’s vision for itself</a>.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The new blog lays out the makings of a funding strategy for the PSA. It lays out four possible sources of future funding: grant writing, charitable giving, fees-for-service, and membership fees, and weighs the strengths and weaknesses of each possibility. The blog also contains two surveys to solicit member feedback about the ideas within the blog.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>This is an important post, as it concerns the future of the PSA. If you are interested in shaping the PSA’s strategy for financial sustainability, please give it a read.</p>
<!-- /wp:paragraph -->
