---
title: "PSA Elections - Candidate Statements"
author: "Heather Urry"
date: 2021-03-23
categories:
  - mailchimp backup
---

Accelerators,

Our PSA election process continues. Today I’m sharing the names of candidates and their statements describing why they've chosen to run and what they'd like to achieve if elected. There are seven candidates for Associate Director and one for Director. All statements are linked by position and name in alphabetical order below.

Associate Director

Erin Buchanan (https://drive.google.com/file/d/1r4RGEngabbdsVusQxxJQZCixuPY_3Upz/view?usp=sharing) (#candidate-ad-buchanan)

Lisa DeBruine (https://drive.google.com/file/d/1gSrhTWiNS-xFEFb4FOfeE3K0S7iofDQZ/view?usp=sharing) (#candidate-ad-debruine)

Jessica Flake (https://drive.google.com/file/d/1fkCXklQW50Gtgn-ZH5RuNG6iJ184MGYw/view?usp=sharing) (#candidate-ad-flake)

Hans IJzerman (https://drive.google.com/file/d/1MNUq3tlVnfLRwzpiPo37vH2jn9KdMp7T/view?usp=sharing) (#candidate-ad-ijzerman)

Sandy Onie (https://drive.google.com/file/d/1vlhA_3YmJs3QQTKWNPeIjclEmb-s5gwy/view?usp=sharing) (#candidate-ad-onie)

Gerit Pfuhl (https://drive.google.com/file/d/1FWBU2igrt1Gyk_A-YyDlMKEIC-x28eco/view?usp=sharing) (#candidate-ad-pfuhl)

Rima-Maria Rahal (https://drive.google.com/file/d/1c0KNSN-2r0N7DkotoFWjsflKMmPA2Jst/view?usp=sharing) (#candidate-ad-rahal)

Director

Nicholas Coles (https://drive.google.com/file/d/1S_zFoBy2brNNi78plm5771eftvlM7pcW/view?usp=sharing) (#candidate-d-coles)


We will be seating two Associate Directors and one Director based on this election. Because there is just one candidate for Director, that race will effectively be a vote of confidence. (Two additional candidates planned to run but both decided to support Nick Coles’ candidacy.)

I’ve set up a channel for each candidate in the PSA Slack workspace (channel names are noted in parentheses above). Feel free to use these channels to ask candidates questions to support your decision making. To join these channels, click “Add channels” in the PSA Slack navigation panel on the left side of the workspace. If you haven’t yet joined the PSA Slack workspace, you may do so here (https://join.slack.com/t/psych-sci-accelerator/shared_invite/zt-6xdadc02-JKn5bEPNMN8vliJlAJBU5w). The Slack channels will be available until the voting period begins.

The two-week voting period will begin on Monday, April 5, 2021 and end on Monday, April 19, 2021. We will provide information about how to vote on or before Monday, April 5. We expect to certify the results within a week after the voting period ends; those who are elected will take office in late April 2021.

Thank you to the candidates for their willingness to run and to the election tellers for continuing to monitor the process!

Best
