---
title: "Seeking Applicants for PSA Leadership Positions"
author: "Charlie Ebersole"
date: 2021-01-22
categories:
  - mailchimp backup
---

Accelerators,

Just wanted to send a reminder about this!

In the coming months, we'll be seeking to fill several leadership positions in the PSA. Below is a quick run down of those positions and how we will fill them.

Assistant Directors
We are currently looking to fill six Assistant Director positions, one for each of the following committees:
-Funding
-Ethics
-Community Building and Network Expansion
-Data and Methods
-Training
-Translation and Cultural Diversity

If you'd like to apply for any of these positions, please fill out this form (https://forms.gle/7KWuEy31vTXvzXi87)  before January 30th. At that point, the Director and Associate Directors will select a candidate for each position. If you have any questions about this application or this process, don't hesitate to reach out to me (via email, slack, or raven).

Director and Associate Director

This Spring, we will also be electing a new Director and Associate Director for the PSA. These positions will be filled by a direct election from the PSA network. Any PSA member may run for these positions. Later this month, we will solicit nominations (self or others) for these roles and we plan to conduct the election process over the next two months. We wanted to let you all know in advance so you could think about whether or not you'd like to run for one of these positions. Again, if you have any questions about these roles or the election process, don't hesitate to reach out.
