---
title: "PSA Election Results"
author: "Heather Urry"
date: 2021-04-22
categories:
  - mailchimp backup
---

Accelerators,
I'm pleased to announce that the election has come to its conclusion. With 187 completed ballots cast, the PSA expressed confidence in Nicholas Coles to serve as director, and selected Erin Buchanan and Lisa DeBruine to serve as associate directors. All three have accepted the positions and will start this Friday, April 23. Congratulations and THANK YOU, Nick, Erin, and Lisa.

It's always tough when there are many more wonderful candidates than there are positions to fill. As we collectively wish Nick, Erin, and Lisa well in their new roles, let's also offer our thanks and kudos to all the candidates for their willingness to throw their hats into the ring. I’m sure I’m not alone in appreciating the great ideas and thought that went into the statements and conversations on Slack. THANK YOU, Hans IJzerman, Jessica Flake, Sandy Onie, Gerit Pfuhl, and Rima-Maria Rahal.

Let's also please offer our thanks and kudos to our election tellers, Ilker Dalgar, Max Primbs, and Crystal Steltenpohl. They were on the receiving end of a LOT of emails and did their due diligence to ensure a fair and accurate process. THANK YOU, Crystal, Ilker, and Max.

We're all very lucky that we get to work and think with bright people the world over!
