---
title: "News from the Accelerator- September 2021"
author: "Savannah Lewis"
date: 2021-09-30
categories:
  - mailchimp backup
---

Accelerators,

Quick read:
* We are now taking self-nomination for assistant director positions for our Project Monitoring, Data & Methods, Study Selection, and Funding Committee.
* October 1 is the last day for presentation (https://psysciacc.org/psa-conference-2021-call-for-presenters/) submissions.
* There is a social event tonight on Gathertown (https://gather.town/app/mX8GlTQ4uGSdFBLg/PSA%20Social%20Hour) at 8 am CST, 8 pm EDT, 12 am UTC, and 7 pm CDT. (password is psysciacc)

Elections

The Psychological Science Accelerator (PSA) is accepting self-nominations for Assistant Directors of our Project Monitoring, Data & Methods, Study Selection, and Funding Committees! Assistant Directors directly shape the direction of the PSA any many ways, including (a) helping establish committee-specific vision plans to help the PSA achieve its mission and adhere to its core principles, (b) overseeing day-to-day committee-specific operations, and (c) providing regular updates to the PSA Director and Associate Directors about progress and problems. They are elected by majority vote by the PSA Board of Directors and serve 3-year terms. All who are interested are encouraged to apply here: https://forms.gle/ZNyhZCz4GenazbYG6

Study updates:
* PSA-002 (Object Orientation): (https://psysciacc.org/002-object-orientation/) The lead team has submitted the manuscript to PBR and is now awaiting feedback.
* PSA-003 (Gendered Prejudice) (https://psysciacc.org/003-gendered-prejudice/) : The lead team is finalizing translation and preparing for data analysis. Thanks to all who reached out following the last newsletter's request for help with translation!
* PSA-004(Accelerated CREP) (https://psysciacc.org/004-true-belief/) : The lead team is currently working on data processing, data analysis, and authorship credit tracking. They are also looking for people to code open-ended responses for Chinese, Russian, and Greek. Contact Savannah to help with coding (slewis16@ashland.edu).
* PSA-005 (Stereotype Threat) (https://psysciacc.org/005-stereotype-threat/) : (https://psysciacc.org/005-stereotype-threat/) Data collection will resume on October 11, 2021. The lead team has created a checklist on Canvas to guide labs in preparations for data collection. Each collaborator should have been added to the Canvas course. If you have not please email psa005stero@gmail.com (mailto:psa005stero@gmail.com) !
* PSA-006 (Trolley Problem): (https://psysciacc.org/006-trolley-problem/) The lead team has submitted the Stage II submission to Nature Human Behavior.
* PSA-007(SPAM-L): (https://psysciacc.org/psa-007-spam-l/) SPAML is still recruiting collaborators, with contribution opportunities available through the Words2Many (https://docs.google.com/document/d/1VKR-7csBlL-lGOTbRTnlmaYkqi8bj2FhYtvbzEN25Wk/edit?usp=sharing) and Subs2Strudel (https://docs.google.com/document/d/1xslViVFZrapUG75mwsF2eijFoQqm5GABoOf9ekIweH4/edit?usp=sharing) pre-projects. The lead team has begun the first rounds of the registered report and will soon be sending these out to contributors for feedback. If you are interested in becoming a collaborator or want to learn more about 007 please email 007spaml@gmail.com (mailto:007spaml@gmail.com)
* PSA-COVID Rapid Bundle (001/002/003)- (https://psysciacc.org/studies/psacr-1-2-3/)
+ PSACR001 (Loss Gain) has been submitted to Affective Science.
+ PSACR002 (Cognitive Reappraisal) has been published in Nature Human Behavior (https://doi.org/10.1038/s41562-021-01173-x) .
+ PSACR003 (Self Determination) was resubmitted to PNAS.

PSACON

Tomorrow is the last day to submit a presentation (https://psysciacc.org/psa-conference-2021-call-for-presenters/) to the second annual PSA CON!! October 27th is the deadline for registration (https://psysciacc.org/the-2021-meeting-of-the-psychological-science-accelerator/). See you all there!

Canvas

The PSA is slowly integrating our new membership website to Canvas. We will be starting to add in every member in the next couple of months. Be sure to check your inbox for your invitation.
