---
title: "PSA Election Updates"
author: "Heather Urry"
date: 2021-03-16
categories:
  - mailchimp backup
---

Accelerators,

I'm writing with a brief update about the election for Director and Associate Director of the PSA. As you know, the process is underway. At this stage, we're receiving statements from the candidates. We originally planned to receive statements by today but we've given candidates an extra week until Mon, Mar 22 to submit them. The one-week delay enables us to give everyone advance notice that we will fill two Associate Director (AD) seats during this election instead of one.** As a result, you'll see statements from candidates in the PSA Slack as of Tues, Mar 23., and the two-week voting period will now take place between Monday, April 5 and Monday, April 19, 2021. We expect to certify the results within a week thereafter. Those who are elected will likely still take office in late April 2021.

If you have any questions, feel free to ask.

Best,

Heather Urry
Associate Director

By way of explanation, my position as AD is up for election this July 2021. However, I'm stepping down early and don't plan to run for re-election, partially because it's a good idea to make way for new voices/perspectives and partially because I need some relief from too many commitments. I'll leave the position when a newly-elected AD steps in and look forward to continuing to contribute to the PSA in other ways.
