---
title: "News from the Accelerator- June 2022"
author: "The Psychological Science Accelerator"
date: 2022-06-01
categories:
  - mailchimp backup
---

quick read
- Our COVID-19 Self Determination study is published (https://www.pnas.org/doi/full/10.1073/pnas.2111091119) at PNAS.

- Our COVID-19 Message Framing study has been accepted for publication at Affective Science.
- Our Semantic Priming Study has been accepted in-principle at Nature Human Behaviour.

- We are still accepting submissions for our funded call for studies (https://psysciacc.org/news/2022-04-20_special-call-for-studies-studying-generalizability-with-global-samples.html) that meet John Templeton Foundation funding strategies.


special call for studies

We are soliciting study proposals that test the generalizability of phenomena related to John Templeton Foundation (JTF) strategic priorities, including: the dynamics of religious change, intellectual humility, religious cognition, and/or the science of character virtue, health, religion, and spirituality.

Each accepted study will:
* Be supported with $40,000 of direct funding for data collection.
* Receive additional support from 3 full time and 2 part time research staff.
* Be advertised to prospective collaborators (e.g., data collection sites) in the PSA network.

For more information, see the full call for studies (https://psysciacc.org/news/2022-04-20_special-call-for-studies-studying-generalizability-with-global-samples.html) .


project updates
https://manybabies.github.io/MB2/


Object Orientation (https://psysciacc.org/002-object-orientation/) Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The lead team is finalizing analysis changes requested by reviewers and updating the manuscript discussion section.

https://manybabies.github.io/MB3/


Gendered Prejudice Study (https://psysciacc.org/003-gendered-prejudice/) (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The lead team has completed an initial draft of the manuscript, which they will circulate to collaborators soon.
https://manybabies.github.io/MB3/


Justified True Belief Study (https://psysciacc.org/004-true-belief/) (PSA-004) (https://psysciacc.org/003-gendered-prejudice/)

The lead team is finalizing the manuscript and will share with collaborators soon, along with further information about authorship.

https://manybabies.github.io/MB3/


Stereotype Threat Study (https://psysciacc.org/005-stereotype-threat/) (PSA-005) (https://psysciacc.org/003-gendered-prejudice/)

Data collection will continue through the end of the year. As of May 02, the team has collected 797 participants across 32 sites!
https://manybabies.github.io/MB3/


Semantic Priming Study (https://psysciacc.org/psa-007-spam-l/) (PSA-007) (https://psysciacc.org/003-gendered-prejudice/)

The Stage 1 Registered Report has been accepted at Nature Human Behaviour. The lead team team is now working on pilot testing, translation, and a how-to guide for data collection collaborators.

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

The Stage 1 Registered Report is under review at Nature Human Behaviour. Potential collaborators who filled out the interest survey should have received an onboarding message on May 19. Please contact Kathleen (mailto:kathleenschmidt1@gmail.com) if you did not receive this message and would like to join the project.
https://manybabies.github.io/MB3/


COVID (https://psysciacc.org/studies/psacr-1-2-3/) Studies (PSA-CR) (https://psysciacc.org/003-gendered-prejudice/)
The COVID-19 Self Determination paper (https://www.pnas.org/doi/full/10.1073/pnas.2111091119) is now published at
PNAS.

The COVID-19 Message Framing project has been accepted for publication at Affective Science. They are working on updating the pre-print (https://psyarxiv.com/sevkf/) , and hope to receive page proofs soon.


big team science
The benefits, barriers, and risk of big team science. PsyArXiv (https://psyarxiv.com/2mdxh)

Build up team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)
