---
title: "News from the Accelerator- November 2022"
author: "The Psychological Science Accelerator"
date: 2022-10-31
categories:
  - mailchimp backup
---

quick read
- The PSA has several new Assistant and Associate Directors!

- Over 450 people attended the inaugural 2022 Big Team Science Conference, co-hosted by the PSA, ManyBabies, and ManyPrimates consortia.

- The PSA-Covid dataset paper has been accepted at Nature Scientific Data.


project updates
https://manybabies.github.io/MB2/


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The lead team has finalized the analyses and is in the process of updating the manuscript.

https://manybabies.github.io/MB3/


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The lead team is integrating the network's feedback and is planning on sharing a new version soon.
https://manybabies.github.io/MB3/


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The lead team has resubmitted the manuscript and is waiting on reviewer feedback.

https://manybabies.github.io/MB3/


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

The PSA-005 team is continuing to collect data (n = 982 so far!)
https://manybabies.github.io/MB3/


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

The PSA-007 team is working on translations and programming while simultaneously collecting data. Thus far, over 6,000 participants have completed the study. Erin also presented the project at the Psyhonomics conference. If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (http://007spaml@gmail.com) .

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

The lead team is almost done revising the Stage 1 Registered Report manuscript in response to the reviews from Nature Human Behaviour. They will share the revision with collaborators for feedback soon
https://manybabies.github.io/MB3/


COVID Studies (PSA-CR) (https://psysciacc.org/studies/psacr-1-2-3/)

The PSA-CR data paper (https://osf.io/byqha) has been accepted! Co-authors will receive an email containing proofs to review soon.

https://manybabies.github.io/MB2/


2022 Big Team Science Conference (https://bigteamscienceconference.github.io/index)

Huge thanks to all who presented and attended the inaugural 2022 Big Team Science conference. It was a jam packed event, with over 450 registrants, 50 sessions, and lots of big team science!


Welcome new members of PSA leadership
We have hosted two elections for PSA leadership positions over the past few months, and we are happy to announce the current lineup:

Associate directors:
* Erin Buchanan, Harrisburg University of Science and Technology
* Lisa DeBruine, University of Glasgow
* John Protzko, Central Connecticut State University
* Miguel Silan, Annecy Behavioral Science Lab and Université Lumière Lyon 2
* Kathleen Schmidt, Ashland University

Assistant directors:
* Chris Chartier (Project Monitoring)
* David Vaidi (Project Monitoring)
* Biljana Gjoneska (Ethics)
* Maja Becker (Ethics)
* Jessica Flake (Data and Methods)
* Marton Kovacs (Data and Methods)
* Maximillion Primbs (Translation)
* Cristina Salvador (Translation)
* Aishwarya Iyer (Community Building)
* Nadia S. Corral-Frias (Community Building)
* Hans IJzerman (Funding)
* Suzanne Stewart (Study Selection)


big team science
The benefits, barriers, and risk of big team science. PsyArXiv (https://psyarxiv.com/2mdxh)

Build up team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. PsyArXiv (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries (https://link.springer.com/article/10.1007/s42761-022-00128-3)
