---
title: "Ethics Committee Survey!"
author: "Savannah Lewis"
date: 2022-01-18
categories:
  - mailchimp backup
---

Accelerators,

The Ethics Committee has set up a survey and invites each PSA member to take active participation. We aim to gain a better understanding of the ethical and legal frameworks that affect the collection of data in PSA projects around the world so that we can help improve the processes of study selection and execution at PSA.

The survey entails questions about ethics procedures in your location, including how long it typically takes to get approval, the factors that can slow it down, and the characteristics of studies that are considered risky or sensitive. This whole survey is pretty short and straightforward, so it should not take more than 10 minutes to be completed.

Your participation is greatly appreciated, as it might facilitate the work on the next PSA projects that are in the pipeline. Please help us improve PSA processes by filling out this survey (https://uqpsych.qualtrics.com/jfe/form/SV_0cuHpOvWRrq7pie) at your earliest possible convenience.

Survey link: https://uqpsych.qualtrics.com/jfe/form/SV_0cuHpOvWRrq7pie


Thanks in advance on behalf of the Ethics Committee


(Kim Peters, Mike Mensink, Biljana Gjoneska, Gerith Pfuhl, Anna van ‘t Veer)
