---
title: "News from the Accelerator- December 2022"
author: "The Psychological Science Accelerator"
date: 2022-12-07
categories:
  - mailchimp backup
---

quick read
- The PSA has released a second special call for studies related to JTF strategic priorities.

- The PSA is the recipient of the €200,000 Einstein Foundation Institutional Award.


Second Special Call for Studies – Studying Generalizability with Global Samples (https://psysciacc.org/news/2022-12-06_second-special-call-for-studies-studying-generalizability-with-global-samples.html)

The PSA, supported by the John Templeton Foundation (JTF), welcomes study proposals to test the generalizability of phenomena related to JTF strategic priorities with large, global samples. Optional initial proposals are due by February 15 and required full proposals are due by May 15.

To be eligible for this call, projects must investigate research questions related to one or more of the strategic priorities of JTF in university and community samples across the globe. These priorities include the dynamics of religious change, intellectual humility, religious cognition, character virtues, health, religion, and spirituality.

Selected projects will be carried out through the PSA network and supported by grant staff and funds for data collection.

Please see the official call announcement (https://psysciacc.org/news/2022-12-06_second-special-call-for-studies-studying-generalizability-with-global-samples.html) for details about proposal requirements, grant support, and the project selection process and timeline.


PSA receives the Einstein Foundation Award (https://www.einsteinfoundation.de/index.php?id=2342&L=1)

The PSA is the recipient of the €200,000 Einstein Foundation Institutional Award! An article describing our work and the award is available here (https://www.einsteinfoundation.de/index.php?id=2342&L=1) !


project updates
https://manybabies.github.io/MB2/


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The 002 team has completed a draft of the new results section and is revising the discussion section. The lead team should have full drafts ready to share with the network soon.

https://manybabies.github.io/MB3/


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The 003 team has nearly completed a draft of the manuscript that incorporates the network's feedback. The lead team should have full drafts ready to share with the network soon.
https://manybabies.github.io/MB3/


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The manuscript has received an R&R, and the lead team is working on revisions.

https://manybabies.github.io/MB3/


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

The 005 team is continuing to collect data.
https://manybabies.github.io/MB3/


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

The 007 team continues to collect data. Most languages will be available soon and the lead team anticipates having additional labs joining us next semester. If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (http://007spaml@gmail.com) .

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

Collaborators have been asked to review the revised version of the Stage 1 Registered Report manuscript and fill out an authorship survey by December 6. The lead team plans to integrate this feedback and resubmit the manuscript to Nature Human Behaviour by the end of the month.
https://manybabies.github.io/MB3/


COVID Studies (PSA-CR) (https://psysciacc.org/studies/psacr-1-2-3/)

The PSA-CR data paper (https://osf.io/byqha) has been accepted! Co-authors will receive an email containing proofs to review soon.


big team science
The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)
