---
title: "News from the Accelerator- October 2022"
author: "The Psychological Science Accelerator"
date: 2022-10-03
categories:
  - mailchimp backup
---

quick read
- The PSA-COVID message framing paper (https://link.springer.com/article/10.1007/s42761-022-00128-3) is now published at Affective Science.

- The chapter “Psychological Science Accelerator: A promising resource for clinical psychological science” (https://psyarxiv.com/qwy4k/) is now available via preprint.

- The PSA Study Capacity Report (https://psyarxiv.com/7krhn/) 2022-2023 is available as a preprint on PsyArXiv.

- We are accepting nominations for Assistant Directors of the Study Selection, Funding, Community Building, and Data & Methods Committees.


project updates
https://manybabies.github.io/MB2/


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The lead team is continuing to work through the feedback from the journal. The lead team has generated new analyses and has posted the code in the project Slack channel for review.

https://manybabies.github.io/MB3/


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The lead team has completed a manuscript draft. The manuscript will be distributed for feedback to all collaborators soon with the goal of submitting to Psychological Science.
https://manybabies.github.io/MB3/


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The Stage 2 manuscript was submitted to AMPPS on July 16th. Collaborators will be notified when the reviews are returned.

https://manybabies.github.io/MB3/


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

All sites running PSA-005 are beginning data collection again! If you are interested in working on this project, or would like more information, you can fill out this form (https://forms.gle/siifAutYT2oKsf3s8) .
https://manybabies.github.io/MB3/


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

Data collection is underway for a few languages. The admin team is continuing to refine and program experimental stimuli for labs collecting data in other languages, and these labs should be able to begin data collection soon. If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (http://007spaml@gmail.com) .

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

The lead team is working through revisions of the Stage 1 Registered Report at Nature Human Behavior. They hope to have a revised version ready for collaborator feedback within the next few weeks.
https://manybabies.github.io/MB3/


COVID Studies (PSA-CR) (https://psysciacc.org/studies/psacr-1-2-3/)

The PSA-CR message framing paper (https://link.springer.com/article/10.1007/s42761-022-00128-3) is now published at Affective Science. We have discovered that the copyeditor made a few errors in the list of affiliations during the final typesetting and will soon reach out and request a publisher's correction.

The PSA-CR data paper (https://osf.io/byqha) will soon be resubmitted to Nature Scientific Data.

https://manybabies.github.io/MB3/


JTF Studies (https://psysciacc.org/news/2022-07-28_special-call-for-studies-studying-generalizability-with-global-samples-deadline-extended.html)

Project proposal submissions to the PSA’s special call for studies (https://psysciacc.org/news/2022-07-28_special-call-for-studies-studying-generalizability-with-global-samples-deadline-extended.html) that have passed the initial phase of study selection are available for network evaluations though October 10th. PSA members can read and provide feedback on the proposals in a survey on the Canvas membership site (https://canvas.psysciacc.org/courses/1/quizzes/89) .
https://manybabies.github.io/MB2/


2022 Big Team Science Conference (https://bigteamscienceconference.github.io/index)

The BTS-CON (co-hosted by the PSA) program (https://docs.google.com/document/d/17m6t7or53uvFErIW_WHvegwlwV2Cq_rvG5ny-4cBkpM) is now available. Registration (https://docs.google.com/document/d/17m6t7or53uvFErIW_WHvegwlwV2Cq_rvG5ny-4cBkpM) is also open. To maximize inclusivity, conference registration fees are optional.


Assistant Director nominations
We are accepting nominations for Assistant Directors of the Study Selection, Funding, Community Building, and Data & Methods Committees.

Assistant Directors co-lead these committees for 3-year terms and are elected by vote by the Board of Directors. The positions are open to all members of the PSA–and current non-members are also eligible if they sign-up for a [free] PSA membership. Members can either nominate themselves or others for each role. There are no term limits.

To nominate yourself of someone else, please fill out the Election Nominations (October 2022) form (https://canvas.psysciacc.org/courses/1/quizzes/90) on the PSA canvas page.


new regional hubs
The Community Building and Network Expansion Committee is launching a “regional hubs” initiative, wherein people can speak with fellow PSA members about culture sensitive research topics, set up regional meetings, plan for collaborations, and much more. To join any of the current regional hubs, or to get more information, you can use this link (https://psych-sci-accelerator.slack.com/archives/C7D9CRWCC/p1662569873051809) to the original Slack message.


big team science
The benefits, barriers, and risk of big team science. PsyArXiv (https://psyarxiv.com/2mdxh)

Build up team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. PsyArXiv (https://psyarxiv.com/qwy4k/)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries (https://link.springer.com/article/10.1007/s42761-022-00128-3)
