---
title: "REMINDER: Ethics Survey"
author: "Savannah Lewis"
date: 2022-02-02
categories:
  - mailchimp backup
---

Accelerators,

On behalf of the PSA Ethics Committee, we would like to remind each member of our PSA community to take active participation in our PSA Ethics Survey, designed to help us gain a better understanding of the ethical and legal frameworks that affect the collection of data in PSA projects around the world.

Your participation will be greatly appreciated since it will facilitate the work on the next PSA projects that are in the pipeline. Please help us improve PSA processes of study selection and execution by filling out the following survey at your earliest possible convenience:
https://uqpsych.qualtrics.com/jfe/form/SV_0cuHpOvWRrq7pie

Researchers who reside in less-represented countries (from Asia, Africa, Latin America, Australia, and Oceania) are especially encouraged to take part in our survey. To get a glimpse of whether your country or region is sufficiently represented in our survey, please consult the map. (https://public.flourish.studio/visualisation/8496325/) If you reside in a country that is not densely covered in dots (representing individual responses), you are very welcome to increase the visibility and our understanding of your local ethical procedures.

The whole survey is pretty short (takes around 10 minutes) and straightforward (includes questions about ethics procedures in your location). We would appreciate it if you find some time to fill out the survey by 7 February.
Thanks in advance on behalf of the Ethics Committee,


Kim Peters, Mike Mensink, Biljana Gjoneska, Gerith Pfuhl, Anna van ‘t Veer
