---
title: "Using crowdfunding to finish the largest stereotype threat project with Black American participants ever"
date: 2022-10-31
---

<!-- wp:paragraph -->
<p>(Donate to the project <a href="https://opencollective.com/psysciacc/projects/psa-005/donate"><strong>here</strong></a>)</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>In 2018, the Psychological Science Accelerator <a href="https://psysciacc.org/2018/10/19/a-large-scale-multi-site-examination-of-stereotype-threat-across-varying-operationalizations-a-newly-selected-accelerator-study/">selected</a> an unusual study to conduct. Instead of using the PSA network to achieve an international sample, this study focused on a hard-to-reach study population: Black American college students. Compared to previous studies, the project was also unusually applied-facing, as it focused on a theory that was developed to understand, and hopefully address, performance gaps in settings like college where strong performance could affect a person’s life trajectory. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The proposed project aimed to address potential weaknesses in the evidence for the theory while simultaneously demonstrating how we can use big team science to achieve the sample sizes needed for informative quantitative tests of theories about hard-to-reach populations. The budding PSA network saw merit in this project, and at least one journal has agreed, as the project was accepted in principle as a Registered Report at <a href="https://springernature.figshare.com/articles/journal_contribution/Stereotype_Threat_in_Black_College_Students_Across_Many_Operationalizations_Registered_Report_Stage_1_Protocol_/13122617"><em>Nature Human Behaviour</em></a><em>.</em></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Four years later and data collection is going strong. As of October 31, 2022, we have recruited 1025 Black college students into our project. This is a stunning accomplishment, and already puts our project among the largest ever studies of stereotype threat among Black American college students. This accomplishment has only been possible due to financial contributions from the project leadership team, which we have redistributed to data collection labs to defray the costs of participant recruitment.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>However, 1025 is still short of our goal of a minimum of 2000 participants. We now believe we need <strong>crowdfunding</strong> to reach our data collection goal.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>You can donate to this project <a href="https://opencollective.com/psysciacc/projects/psa-005/donate">here</a>. Any donations we receive that exceed our financial need will be donated to the PSA at project’s end, as we have relied heavily on PSA resources to make this project happen.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Help us finish an amazing – and, for psychology, historic – project, further demonstrating the potential of <a href="https://psyarxiv.com/2mdxh/">big team science</a> for solving some of behavioral science’s most pressing problems.<br><br>- The PSA Stereotype Thread administrative team</p>
<!-- /wp:paragraph -->
