---
title: "Special Call for Studies - Studying Generalizability with Global Samples"
author: "The Psychological Science Accelerator"
date: 2022-04-20
categories:
  - mailchimp backup
---

Special Call for Studies – Studying Generalizability with Global Samples (https://psysciacc.org/news/2022-04-20_special-call-for-studies-studying-generalizability-with-global-samples.html)

The Psychological Science Accelerator (PSA), supported by the John Templeton Foundation (JTF), welcomes study proposals to test the generalizability of phenomena related to JTF strategic priorities with large, global samples.

To be eligible for this call, projects must investigate questions related to one or more of the strategic priorities of JTF: the dynamics of religious change, intellectual humility, religious cognition, the science of character virtue, and health, religion, and spirituality.

Projects selected through this special call will be advertised to members of the PSA network in collaboration with the proposing authors. Each study will be supported by $40,000 of direct funding for data collection. The proposing author teams will also be collectively supported by 3 full-time scientific staff members (a Research Coordinator, a Postdoctoral Researcher, and a Research Scientist), an additional ⅓ time senior staff member (Dr. Christopher R. Chartier), a ½ time staff member equivalent team of undergraduate research assistants, several members of PSA committees (at their discretion), and members of the network at large (at their discretion).


Selection Process and Timeline
* Submission deadline:  July 20, 2022.
* Initial feasibility and quality review: July 20- July 27, 2022.
* Reviewer selection: July 27- August 3, 2022.
* Network rating solicitation: August 3, 2022.
* Review submission deadline: August 17, 2022.
* Network rating deadline: August 17, 2022
* Study selection decision deadline: August 31, 2022.

Possible submission outcomes include “desk rejection” upon initial review, rejection upon full review, provisional acceptance, or an invitation to revise and resubmit for next year’s call.

Following a successful period of needs assessment, preparation, personnel identification, lab recruitment, and pre-registration, provisionally selected studies will commence data collection in early 2023 and end data collection in late 2023.

Please use this form to submit your proposal. (https://docs.google.com/forms/d/e/1FAIpQLSdY5m5rxkQ1zrt-84Q5e5wLyfuQft56HN47FqzeTvzX6l9CBA/viewform?usp=sf_link)

For pre-submission inquiries, please email Chris Chartier at cchartie@ashland.edu (mailto:cchartie@ashland.edu). He is happy to meet with proposing authors and/or answer questions about what is likely to make for a strong submission. To learn more information about submission details and formatting, please visit the official call. (https://docs.google.com/document/d/1hSiOt45jbgB8j_OkhktEqLNP9_apHYmkpAvz7Mwfkqo/edit?usp=sharing)

