---
title: "News from the Accelerator- February 2022"
date: 2022-03-07
---

<!-- wp:heading {"textAlign":"left","level":3} -->
<h3 class="has-text-align-left">Quick Read&nbsp;</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul><li>PSA-006 (Trolley Problem) has been accepted at Nature Human Behaviour!</li><li>Job recruitment for three PSA positions at Ashland University (<strong><a href="https://www.indeed.com/viewjob?cmp=Ashland-University---Ashland,-OH&amp;t=Research+Scientist&amp;jk=c143333997a2447b&amp;q=Ashland+University&amp;vjs=3s=3">Research Scientist</a>, <a href="https://www.indeed.com/viewjob?cmp=Ashland-University---Ashland,-OH&amp;t=Post+Doctoral+Researcher&amp;jk=5547b4ff5de1e201&amp;q=Ashland+University&amp;vjs=3">Post-doctoral Researcher</a> &amp; <a href="https://www.indeed.com/viewjob?cmp=Ashland-University---Ashland,-OH&amp;t=Research+Coordinator&amp;jk=2b8aa4a2d28de65e&amp;q=Ashland+University&amp;vj">Research Coordinator</a></strong>) will close soon! Make sure to apply before March 14 to receive priority consideration.&nbsp;</li><li>The PSA <strong><a href="https://docs.google.com/document/d/13MQxrgs54eUz2iS9o_L_Ca_PjKUdT81T4xF3X5LLEGk/edit?usp=sharing">three year vision plan</a> </strong>is available for review and<strong> <a href="https://forms.gle/CPRAdnzJfLR7m8BN9">f</a></strong><a href="https://forms.gle/CPRAdnzJfLR7m8BN9"><strong>eedback</strong></a>.</li><li>The funding and finance committee is<a href="https://docs.google.com/document/d/1WqIqi6gs9PzAu3SE2XrjsOhtxnxls2iyvUaqtfu064A/edit"> </a><strong><a href="https://docs.google.com/document/d/1WqIqi6gs9PzAu3SE2XrjsOhtxnxls2iyvUaqtfu064A/edit">recruiting new members</a> </strong>to serve in multiple roles that are vital for sustaining the PSA.</li><li><a href="https://docs.google.com/document/d/15l4UKNRROuFcc1QFVbcOIhMHKPVRg3dXoasZAPbeGEw/edit"><strong>New call </strong></a>for PSA studies with rare populations.</li><li>Community Building and Network Expansion Committee (CBNEC) is looking for<a href="https://docs.google.com/document/d/1fAggRl9oimmyLdF4vGim7JE-AWLiz2fV/edit"><strong> two interns</strong> </a>through the Université Grenoble Alpes!</li></ul>
<!-- /wp:list -->

<!-- wp:heading {"textAlign":"center","level":3} -->
<h3 class="has-text-align-center">Study updates</h3>
<!-- /wp:heading -->

<!-- wp:list -->
<ul><li><strong>PSA-002 (Object Orientation): </strong>The lead team is working through extensive feedback on the Stage 2 Registered Report submission from Psychonomic Bulletin and Review.</li><li><strong>PSA-003 (Gendered Prejudice): </strong>The lead team has completed initial data analyses and is working on drafting a manuscript describing the results.</li><li><strong>PSA-004 (Accelerated CREP):</strong> The lead team is working on data processing, data analysis, and authorship credit tracking. A group of collaborators were emailed the current version of the manuscript a few weeks ago.&nbsp;</li><li><strong>PSA-005 (Stereotype Threat):</strong> Data collection continues. As of last week, the team has collected 571 participants across 29 sites!&nbsp;</li><li><strong>PSA-006 (Trolley Problem):</strong> The manuscript has final acceptance at Nature Human Behaviour. The lead team is waiting to receive the final paper proofs.&nbsp;</li><li><strong>PSA-007 (SPAM-L):</strong> The team received a favorable revise-and-resubmit on the Stage 1 registered report submitted to Nature Human Behaviour! The project team is now working on (a) addressing reviewer comments, (b) finalizing the experimental materials in lab.js, and (c) establishing a system for material translations. The project team will be sending updates in the near future regarding other ways to contribute. If you are interested in becoming a collaborator or want to learn more, <strong><a href="mailto:007spaml@gmail.com">e-mail the lead team</a>.</strong></li><li><strong>PSA- 008 (Minimal Groups): </strong>The lead team thanks everyone who filled out the interest survey and will contact those who responded with onboarding instructions in early April. In the meantime, the lead team is working on a pilot study and a Stage 1 registered report. They aim to submit the manuscript to Nature Human Behaviour by the end of March. If you are interested in becoming a collaborator (and did <em>not </em>fill out the interest survey) or want to learn more about the project, <strong><a href="mailto:kathleenschmidt1@gmail.com">e-mail Kathleen</a>.</strong></li><li><strong>PSA-COVID Rapid Bundle (001/003)-</strong>&nbsp;<ul><li>The PSACR-001 lead team is working on revising the manuscript at Affective Science. Collaborators have already submitted feedback and approved resubmission, so the paper will be resubmitting once those revisions are complete.</li><li>PSACR-003 has been accepted at PNAS, but there are still some details being worked out with the journal (particularly regarding payment). Once those details are finalized, collaborators will be notified.</li></ul></li></ul>
<!-- /wp:list -->

<!-- wp:heading {"level":3} -->
<h3><strong>Reminder to apply for the PSA positions at Ashland University.</strong></h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Christopher Chartier at Ashland University will begin looking at applications for three full-time positions on March 14, 2022. The three positions include a Research Scientist, a Postdoctoral Researcher, and a Research Coordinator that will work with the PSA and Chris on a three-year funded by the John Templeton Foundation. Applicants who submit before on or before March 14 will receive priority when it comes to filling the positions.&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>All positions will begin on July 1, 2022 on 1-year contracts through Ashland University with the potential to renew for up to two additional years through the end of the project on June 30, 2025. You can read more about the project <a href="https://docs.google.com/document/d/1S2h0CuBlN9V9TFus3qfmRAwKXkiMoyAf/edit">here</a>.&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>If you have questions feel free to slack, message or email Chris (cchartie@ashland.edu).&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Links to application and job description:&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong><a href="https://www.indeed.com/viewjob?cmp=Ashland-University---Ashland,-OH&amp;t=Research+Scientist&amp;jk=c143333997a2447b&amp;q=Ashland+University&amp;vjs=3s=3">Research Scientist</a><br><a href="https://www.indeed.com/viewjob?cmp=Ashland-University---Ashland,-OH&amp;t=Post+Doctoral+Researcher&amp;jk=5547b4ff5de1e201&amp;q=Ashland+University&amp;vjs=3">Post-doctoral Researcher&nbsp;</a><br><a href="https://www.indeed.com/viewjob?cmp=Ashland-University---Ashland,-OH&amp;t=Research+Coordinator&amp;jk=2b8aa4a2d28de65e&amp;q=Ashland+University&amp;vj">Research Coordinator&nbsp;</a></strong></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3><strong>2022-2025 Vision Plan</strong>&nbsp;</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Several members of PSA leadership have drafted a vision plan that reviews the history, guiding principles, and recent accomplishments of the PSA. This document also focuses on 6 priorities the network can focus on over the next three years.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>To view the document in its entirety, view this <a href="https://docs.google.com/document/d/13MQxrgs54eUz2iS9o_L_Ca_PjKUdT81T4xF3X5LLEGk/edit?usp=sharing"><strong>link</strong></a>. If&nbsp; you would like to submit feedback, please use this <strong><a href="https://forms.gle/CPRAdnzJfLR7m8BN9">form</a>.</strong></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3><strong>Recruiting members for the funding and finance committee</strong></h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>The funding and finance committee is recruiting new members to serve in multiple roles that are vital for sustaining the PSA. The general purpose of the funding and finance committee is to serve as an advisory board for the PSA’s Director and Associate Directors on all matters related to finance and funding. To learn more information, please read this <strong><a href="https://docs.google.com/document/d/1WqIqi6gs9PzAu3SE2XrjsOhtxnxls2iyvUaqtfu064A/edit">document</a>!</strong>&nbsp;</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3><strong>Call for Proposals: Rare populations!</strong></h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>The PSA is releasing a call for proposed studies with rare populations. To learn more, please read this <a href="https://docs.google.com/document/d/15l4UKNRROuFcc1QFVbcOIhMHKPVRg3dXoasZAPbeGEw/edit?usp=sharing"><strong>document</strong>!</a></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3><strong>Community Building and Network Expansion Committee Interns!&nbsp;&nbsp;</strong></h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>The Community Building and Network Expansion Committee (CBNEC) is a committee of the PSA that is tasked with engaging, expanding and assessing the network. This year, among its many other initiatives, the CBNEC is more purposively and systematically recruiting scholars from developing nations. To help in these initiatives, the CBNEC will be recruiting two (2) interns through the&nbsp;Université Grenoble Alpes.. To learn more, please read<strong> </strong>this <strong><a href="https://docs.google.com/document/d/1fAggRl9oimmyLdF4vGim7JE-AWLiz2fV/edit">document</a></strong>! </p>
<!-- /wp:paragraph -->
