---
title: "News from the Accelerator- August 2022"
author: "The Psychological Science Accelerator"
date: 2022-08-02
categories:
  - mailchimp backup
---

quick read
- The deadline for the John Templeton Foundation Call for Studies (https://psysciacc.org/news/2022-04-20_special-call-for-studies-studying-generalizability-with-global-samples.html) has been extended to August 31st.

- The deadline for submitting to the 2022 Big Team Science Conference (https://bigteamscienceconference.github.io)  has been extended to August 5th.
Extended Deadline: JTF Call for Studies (https://psysciacc.org/news/2022-07-28_special-call-for-studies-studying-generalizability-with-global-samples-deadline-extended.html)

The deadline for the John Templeton Foundation Special Call for Studies (Studying Generalizability with Global Samples) has been extended to August 31st! Projects must meet call requirements and, if accepted, will be heavily supported by the PSA. Please submit your proposals here (https://docs.google.com/forms/d/e/1FAIpQLSdY5m5rxkQ1zrt-84Q5e5wLyfuQft56HN47FqzeTvzX6l9CBA/viewform) .
https://manybabies.github.io/MB2/


2022 Big Team Science Conference (https://bigteamscienceconference.github.io/index)

The deadline for submitting to 2022 BTS-CON has been extended to August 5th. We encourage you to submit any and all work related to big team science. More information here (https://docs.google.com/forms/d/e/1FAIpQLScIciauSbdMx7Es0Wnmp9ulOHGZtWlvaXinBm6mkLrd32WZyA/viewform) .


project updates
https://manybabies.github.io/MB2/


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The paper draft is currently being finalized and will be distributed to collaborators for feedback in the near future.

https://manybabies.github.io/MB3/


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The paper draft is currently being finalized and will be distributed to collaborators for feedback in the near future.
https://manybabies.github.io/MB3/


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The Stage 2 manuscript was officially submitted to AMPPS on July 16th! Collaborators will be notified when the reviews are returned.

https://manybabies.github.io/MB3/


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

The project leads are recruiting new data collection collaborators. For more information and/or to confirm interest, please fill out this form (https://docs.google.com/forms/d/e/1FAIpQLSe-515X8JqXCWCHVtza5jLRPDec_vApgosX21lPfFZH9YSYzw/viewform)  or you can contact Patrick Forscher (mailto:patrick.forscher@busaracenter.org). Data collection should be finished by Spring 2023.
https://manybabies.github.io/MB3/


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

PSA-007 now has the ability to recruit additional languages! Updates regarding ways to collect data for this project will be coming soon.

If you are interested in collaborating on this project, or want to learn more, please e-mail the project leads (http://007spaml@gmail.com) .

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

The lead team is awaiting feedback on the Stage 1 submission at Nature Human Behaviour. In the meantime, they request that collaborators review and accept the Collaboration Agreement (see Canvas site for details).

If you are interested in joining the project and have not been added to the Canvas page, please contact Kathleen Schmidt (http://kathleenschmidt1@gmail.com) .
https://manybabies.github.io/MB3/


COVID Studies (PSA-CR) (https://psysciacc.org/studies/psacr-1-2-3/)

PSA-CR-001 is in-press at Affective Science. Project leads hope to receive page proofs soon!

The PSA-CR data paper (https://osf.io/byqha) is still under review at Nature Scientific Data.


big team science
The benefits, barriers, and risk of big team science. PsyArXiv (https://psyarxiv.com/2mdxh)

Build up team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)
