---
title: "News from the Accelerator- July 2022"
author: "The Psychological Science Accelerator"
date: 2022-07-05
categories:
  - mailchimp backup
---

quick read
- Submissions are open for the 2022 Big Team Science Conference (https://bigteamscienceconference.github.io) , co-hosted by the PSA virtually on October 27-28.

- We are accepting nominations for two Associate Directors and six Assistant Directors.

- The deadline to submit a proposal for our John Templeton Foundation-funded call for studies (https://psysciacc.org/news/2022-04-20_special-call-for-studies-studying-generalizability-with-global-samples.html) is July 20.

- Thanks to funding from the John Templeton Foundation, we have hired a new Research Scientist (Kathleen  Schmidt) and Research Coordinator (Erin Sievers)!
https://manybabies.github.io/MB2/


2022 Big Team Science Conference (https://bigteamscienceconference.github.io/index)

The goal of this two-day virtual conference is to bring together a multidisciplinary group of researchers, funders, and stakeholders to discuss advancements, challenges, and future opportunities related to big team science.

The conference will feature symposia, panel sessions, hackathons, talks, and social hours. We welcome submissions from groups and individuals who are interested in sharing any work related to Big Team Science.

The deadline to complete the Submission Form (https://docs.google.com/forms/d/e/1FAIpQLScIciauSbdMx7Es0Wnmp9ulOHGZtWlvaXinBm6mkLrd32WZyA/viewform?usp=sf_link)  is July 22.


nominations for leadership positions

We are accepting nominations for two Associate Directors and six Assistant Directors.

Associate Directors serve on the Board of Directors for 4-year terms and will be chosen by a later PSA-wide election. Assistant Directors lead specific committees for 3-year terms and are elected by the Board of Directors.

More information about the roles and how to submit nominations is available here (https://psysciacc.org/news/2022-07-05_nominations-for-psa-leadership-positions.html) .

The Study Selection Committee is seeking new members to aid in selecting projects for the PSA's most recent call for studies. More information is available at this link (https://forms.gle/vJHn9sqgEGPZYGN86) .


new PSA personnel

Thanks to funding from the John Templeton Foundation, we have hired a new Research Scientist (Kathleen  Schmidt, pictured left) and Research Coordinator (Erin Sievers, pictured right). Welcome, Kathleen and Erin!


project updates
https://manybabies.github.io/MB2/


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The lead team is finalizing the manuscript discussion section. The manuscript will be sent to all authors for comment in the next few weeks.

https://manybabies.github.io/MB3/


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The lead team is incorporating feedback from the lead team. The manuscript will be circulated to all authors for comment some time in the next few weeks.
https://manybabies.github.io/MB3/


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The lead team is finalizing the manuscript and will share with collaborators soon, along with further information about authorship.

Contributors have been asked to review a draft of the Stage 2 manuscript, which will be submitted soon!

https://manybabies.github.io/MB3/


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

The leadership is recruiting additional collaborators to help finish data collection! If you are willing and able to recruit Black students at a US-based institution, please fill out this sign-up form (https://forms.gle/siifAutYT2oKsf3s8) .
https://manybabies.github.io/MB3/


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

The English version of the study is ready for pilot testing and data collection. Programming for other languages is in-progress. Current collaborators can fill out forms on Canvas to get started, and people who would like to join can email Erin Buchanan (mailto:buchananlab@gmail.com) .

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

The Stage 1 Registered Report is under review at Nature Human Behaviour. Potential collaborators who filled out the interest survey should have received an onboarding message on May 19. Please contact Kathleen (mailto:kathleenschmidt1@gmail.com) if you did not receive this message and would like to join the project.
https://manybabies.github.io/MB3/


COVID Studies (PSA-CR) (https://psysciacc.org/studies/psacr-1-2-3/)

The COVID-19 Message Framing project has been accepted for publication at Affective Science. We are still in the process of updating the pre-print (https://psyarxiv.com/sevkf/) , and hope to receive updated page proofs soon.

A manuscript (https://osf.io/byqha) describing the datasets for the three PSA COVID studies has been submitted to Nature Scientific Data.


big team science
The benefits, barriers, and risk of big team science. PsyArXiv (https://psyarxiv.com/2mdxh)

Build up team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)
