---
title: "News from the Accelerator- October 2023"
author: "The Psychological Science Accelerator"
date: 2023-10-03
categories:
  - mailchimp backup
---

quick read
- PSA members are invited to participate in a paid metascientific study! Please read below for more information on how to participate.

- The program (https://bigteamscienceconference.github.io/program/) for the 2023 Big Team Science Conference is now live.

- The PSA 007 Semantic Priming study is looking for collaborators who can collect data in Chinese and Portuguese!

- The PSA Moral Experiences study (PSA-JTF1) seeks collaborators in select countries!
https://bigteamscienceconference.github.io/
The PSA is a proud to co-host of the second annual Big Team Science Conference (https://bigteamscienceconference.github.io/) ! The program (https://bigteamscienceconference.github.io/program/) is now live, registration (https://bigteamscienceconference.github.io/registration/) is open, and registration fees will once again be optional!


Calling all PSA members to participate in a metascientific study!
PSA members are invited to participate in a study examining researchers' predictions regarding the generalizability of psychological effects across cultural contexts.

The study should take about 15 minutes to complete, and participants may choose to receive a $10 Visa gift card for their participation.
Who can participate?
The only criteria for participation is being a PSA member. If you’re not yet a PSA member and would like to be one, sign up here (https://member.psysciacc.org/) before participating in the study.

What is involved?
In the study, you will be asked to read a description of an upcoming research project being run by the PSA. Then, you will predict research outcomes from the project. You will also answer a few questions about your predictions and your beliefs about generalizability. Finally, you will answer some questions about yourself.

Interested in participating?
When you are ready to complete the study, simply click on the following link to participate: Study Link (https://research.sc/participant/login/dynamic/5948DA4A-006B-4698-B158-15BB3464AFCC). If you are a collaborator contributing to the PSA-JTF1: Moral Experiences project, please do not use this link to participate (see project email for alternative link).

If you have any questions, please email psajtf1@gmail.com (mailto:psajtf1@gmail.com) .

Thank you for your consideration!


project updates


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The manuscript has been resubmitted to Psychonomic Bulletin and Review and is under review.


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The most current draft was circulated to all coauthors for a final review on September 25. We hope to submit the final manuscript to Psychological Science shortly after the network review window ends on October 9.


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The paper was resubmitted to Advances in Methods and Practices in Psychological Science on May 31 and is still under review.


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

Data collection for the Fall has started, and the lead team hopes to finish this semester. The lead team also recently sent out a letter of interest for one of their commentaries.


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

PSA-007 is actively seeking collaborators to collect data in Chinese (traditional and simplified) and Portuguese (including Brazilian Portuguese). Our current data is over 23,000 participants in 30 languages! If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (mailto:buchananlab@gmail.com?subject=Interest%20in%20PSA-007) .


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

The lead team continues to prepare for data collection. Translation of the study materials has begun for several languages. Another minor revision of the Stage 1 manuscript will be submitted very soon.


PSA-JTF-001: Moral Experiences (https://psysciacc.org/news/2022-04-20_special-call-for-studies-studying-generalizability-with-global-samples.html)

The lead team is preparing to run a pilot study as they finalize the manuscript and materials for preregistration. They are still seeking additional collaborators who can collect data (especially local community samples) in select countries, including: Argentina, Colombia, France, Greece, Indonesia, Japan, Kenya, Malaysia, Morocco, Pakistan, and Saudi Arabia. Please fill out the interest (https://docs.google.com/forms/d/e/1FAIpQLSdR0v-_kRxi0ipLb1YqbVlvhhQ_gOiwMhim_X0r-AVbrjur3w/viewform) survey (https://docs.google.com/forms/d/e/1FAIpQLSdR0v-_kRxi0ipLb1YqbVlvhhQ_gOiwMhim_X0r-AVbrjur3w/viewform) or email psajtf1@gmail.com (mailto:psajtf1@gmail.com) for more information about joining the project.


PSA-AF-001: Partner Preferences (https://psysciacc.org/psa-af-001-partner-preferences/)

The project is accepted in-principle at the Journal of Personality and Social Psychology, and data collection is projected to conclude this year.


big team science
Psychology should generalize from — not just to — Africa. Nature Reviews Psychology (https://www.nature.com/articles/s44159-022-00070-y)

How to build up big team science: a practical guide for large-scale collaborations. Royal Society Open Science. (https://royalsocietypublishing.org/doi/10.1098/rsos.230235)

‘Big team’ science challenges us to reconsider authorship. Nature Human Behaviour (https://www.nature.com/articles/s41562-023-01572-2)

The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up big team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)

The Psychological Science Accelerator’s COVID-19 rapid-response dataset. Nature Scientific Data (https://www.nature.com/articles/s41597-022-01811-7)
