---
title: "News from the Accelerator- June 2023"
author: "The Psychological Science Accelerator"
date: 2023-06-07
categories:
  - mailchimp backup
---

quick read
- Studies that passed the initial phase of study selection for the PSA's second special call for studies (https://psysciacc.org/news/2022-12-06_second-special-call-for-studies-studying-generalizability-with-global-samples.html) are available for evaluation from the entire PSA network.

- The Moral Experiences project (PSA-JTF-001) is seeking collaborators who can collect data in Africa or the Middle East.

- We have two new papers on how to do big-team science (Royal Society Open Science (https://royalsocietypublishing.org/doi/10.1098/rsos.230235) ) and generalizing from (not just to) Africa (Nature Reviews Psychology (https://www.nature.com/articles/s44159-022-00070-y) ).

- The community building committee has launched Regional Hubs for South Asia & Latin America and Caribbean.

- We are now providing updates on two PSA studies: the Partner Preferences (PSA-AF-001) and Moral Experiences (PSA-JTF-001) studies.


project updates
https://manybabies.github.io/MB2/


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The Stage 2 Registered Report has been finalized and sent to all co-authors for final approval. The plan is to submit the paper to Psychonomic Bulletin & Review soon.

https://manybabies.github.io/MB3/


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The lead team is in the process of finalizing edits to the manuscript and will soon be distributing it to all co-authors for final approval.
https://manybabies.github.io/MB3/


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The Stage 2 Registered Report will be re-submitted this week to Advances in Methods and Practices in Psychological Science.

https://manybabies.github.io/MB3/


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

The team has collected data from over 1,500 participants thus far, and they plan to continue collecting data in Fall 2023.
https://manybabies.github.io/MB3/


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

Thus far, we have collected data from over 16,000 participants in 28 languages. For Thai, we have finished translations and should be ready to start data collection soon. Data collection will continue into the Fall. We anticipate to have additional labs joining us next semester. If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (https://psysciacc.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&id=3dab7b4f43&e=2a82fb47c9 ) .

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

Nature Human Behaviour has requested a couple more minor revisions of the Stage 1 Registered Report. The lead team is working on these changes and will resubmit the manuscript very soon. Data collection preparations are ongoing.
https://manybabies.github.io/MB3/


PSA-JTF-001: Moral Experiences (https://psysciacc.org/news/2022-04-20_special-call-for-studies-studying-generalizability-with-global-samples.html)

The lead team thanks those who have expressed interest in joining the project thus far. They will start reaching out to potential collaborators soon.

The team continues to seek collaborators from all world regions, but especially those who can collect data in Africa or the Middle East. They will be choosing approximately 25 countries in which to collect data. This list will likely include Pakistan, Turkey, Japan, India, Indonesia, Australia, Greece, and Poland, so data collection teams in these countries are also encouraged to express interest.

If you would like to learn more about the project and potentially join as a collaborator, please fill out this survey (https://docs.google.com/forms/d/e/1FAIpQLSdR0v-_kRxi0ipLb1YqbVlvhhQ_gOiwMhim_X0r-AVbrjur3w/viewform?usp=sf_link) !

https://manybabies.github.io/MB3/


PSA-AF-001: Partner Preferences (https://psysciacc.org/psa-af-001-partner-preferences/)

The project is accepted in-principle at the Journal of Personality and Social Psychology, and data collection is progressing smoothly. Thus far, we have collected approximately 8,000 participants from 50 sites, and the final 10 sites are nearly ready to launch. We expect to have data collection completed at some point in the Fall.


Help the PSA select our next projects!

Project proposal submissions to the PSA’s special call for studies  (https://psysciacc.org/news/2022-12-06_second-special-call-for-studies-studying-generalizability-with-global-samples.html) that have passed the initial phase of study selection are available for network evaluations through June 20th. PSA members can read and provide feedback on the proposals in a survey on the Canvas membership site (https://canvas.psysciacc.org/courses/1/quizzes/179) .


CBNEC launches Regional Hubs for South Asia & Latin America and Caribbean
The Community Building & Network Expansion committee of the PSA aims to increase the access and reach of the PSA within and outside its network. To better build a community of researchers that is region-specific and focused on discussing community-centered research, we are launching Regional Hubs! We are testing regional hubs in two regions with PSA members: South Asia & Latin America and the Caribbean. For more information, check out this blog post (https://psysciacc.org/news/2023-05-22_cbnec-launches-regional-hubs-for-south-asia-latin-america-and-caribbean.html) .


big team science
Psychology should generalize from — not just to — Africa. Nature Reviews Psychology (https://www.nature.com/articles/s44159-022-00070-y)

How to build up big team science: a practical guide for large-scale collaborations. Royal Society Open Science. (https://royalsocietypublishing.org/doi/10.1098/rsos.230235)

‘Big team’ science challenges us to reconsider authorship. Nature Human Behaviour (https://www.nature.com/articles/s41562-023-01572-2)

The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up big team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)

The Psychological Science Accelerator’s COVID-19 rapid-response dataset. Nature Scientific Data (https://www.nature.com/articles/s41597-022-01811-7)
