---
title: "News from the Accelerator- December 2023"
author: "The Psychological Science Accelerator"
date: 2023-12-04
categories:
  - mailchimp backup
---

quick read

- Thank you for another great year of accelerating science!

-  The PSA Minimal Groups Study (PSA-008) is seeking translators for the following languages: Bulgarian, Swedish, Japanese, and Kiswahili.

- The PSA Moral Experiences study (PSA-JTF1) seeks collaborators in select countries!

- The Love Consortium is accepting submissions for two funding opportunities.


project updates


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The manuscript submitted to Psychonomic Bulletin and Review is still under review.


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The lead team has finalized the manuscript and plans to submit the manuscript to Psychological Science by the end of the week.


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The manuscript will be resubmitted to Advances in Methods and Practices in Psychological Science within the next few weeks.


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

Data collection will continue for another semester so that the thresholds of evidence described in the pre-registration can be reached.


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

Three more languages (Hungarian, French and Italian) have reached data collection requirements, and 12 languages are complete! In total, data has been collected from 26,000 participants in 30 languages! If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (mailto:buchananlab@gmail.com?subject=Interest%20in%20PSA-007) .


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

The lead team has resubmitted the Registered Report to Nature Human Behaviour! Translation of the study materials continues as the lead team makes final preparations to start data collection. They are currently calling for translators in the following languages: Bulgarian, Swedish, Japanese, and Kiswahili. If you are able to help with any of these languages, please email the lead team (mailto:psa-008@googlegroups.com) .


PSA-JTF-001: Moral Experiences (https://psysciacc.org/news/2022-04-20_special-call-for-studies-studying-generalizability-with-global-samples.html)

The lead team has piloted study implementation and will soon begin ethics and translation processes. They are still seeking collaborators who can collect data in Argentina, Colombia, France, Greece, Indonesia, Japan, Kenya, Malaysia, Morocco, Pakistan, or Saudi Arabia; please email the project leads (mailto:psajtf1@gmail.com) for more information about joining the project.


PSA-AF-001: Partner Preferences (https://psysciacc.org/psa-af-001-partner-preferences/)

Data collection for this project is now complete (n > 20,000 from 40 + countries)! The lead team is now working through the analyses and will then turn their attention to the Stage 2 report at the Journal of Personality and Social Psychology!


Other News in Big Team Science
The Love Consortium (TLC) is now accepting submissions (https://shoutout.wix.com/so/6cOgukMvs?languageTag=en) for two funding opportunities to advance the science of gratitude using data described in the Global Gratitude Dataverse. Submission deadline is December 15.
Many of us are reading this new big team science paper (https://www.nature.com/articles/s41562-023-01749-9) in Nature: High replicability of newly discovered social-behavioural findings is achievable!
The 5th Open Innovation in Science Conference (https://ois-research-conference.org/) will be held May 21-23 in London. Submission deadline in January 15.


big team science
High replicability of newly discovered social-behavioural findings is achievable. Nature (https://www.nature.com/articles/s41562-023-01749-9)

Psychology should generalize from — not just to — Africa. Nature Reviews Psychology (https://www.nature.com/articles/s44159-022-00070-y)

How to build up big team science: a practical guide for large-scale collaborations. Royal Society Open Science. (https://royalsocietypublishing.org/doi/10.1098/rsos.230235)

‘Big team’ science challenges us to reconsider authorship. Nature Human Behaviour (https://www.nature.com/articles/s41562-023-01572-2)

The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up big team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)

The Psychological Science Accelerator’s COVID-19 rapid-response dataset. Nature Scientific Data (https://www.nature.com/articles/s41597-022-01811-7)
