---
title: "News from the Accelerator- November 2023"
author: "The Psychological Science Accelerator"
date: 2023-11-06
categories:
  - mailchimp backup
---

quick read

- The PSA is accepting nominations for two Assistant Director positions.

-  The PSA-004 paper was accepted with minor revisions to Advances in Methods and Practices in Psychological Science!

- The PSA Moral Experiences study (PSA-JTF1) seeks collaborators in select countries!

- The Love Consortium is accepting submissions for two funding opportunities.


Assistant Director nominations
The PSA is accepting nominations for Assistant Directors of the Ethics Committee and Data & Methods Committee!

Self-nominations are highly encouraged, and all nominations are due November 17! For more information, please see this link (https://forms.gle/HPDSpnJT5rUDy3Pw7) .


project updates


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The manuscript submitted to Psychonomic Bulletin and Review is still under review.


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The lead team is in the final stages of addressing the network feedback after the last round of internal reviews. They are finalizing the manuscript for submission to Psychological Science.


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

After submission to Advances in Methods and Practices in Psychological Science, the paper was accepted with minor revisions on October 19th, 2023.


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

Data collection is underway, and the lead teams are working on a second commentary that they hope to submit by December. The lead team also hopes to resubmit the first commentary in the Spring semester.


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

PSA-007 has collected over 25,000 participants in 30 languages! If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (mailto:buchananlab@gmail.com?subject=Interest%20in%20PSA-007) .


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

Translation of the study materials continues as the lead team makes final preparations to start data collection.


PSA-JTF-001: Moral Experiences (https://psysciacc.org/news/2022-04-20_special-call-for-studies-studying-generalizability-with-global-samples.html)

The lead team is testing and piloting the study, and the translation and ethics processes will soon begin. They are still seeking collaborators who can collect data in Argentina, Colombia, France, Greece, Indonesia, Japan, Kenya, Malaysia, Morocco, Pakistan, or Saudi Arabia; please email psajtf1@gmail.com (mailto:psajtf1@gmail.com) for more information about joining the project.


PSA-AF-001: Partner Preferences (https://psysciacc.org/psa-af-001-partner-preferences/)

Data from 12,000+ participants from 50+ sites have been collected, and data collection will be ending soon. Afterwards, the project leads will start working on the Stage 2 report at the Journal of Personality and Social Psychology!


Other News in Big Team Science
The Love Consortium (TLC) is now accepting submissions (https://shoutout.wix.com/so/6cOgukMvs?languageTag=en) for two funding opportunities to advance the science of gratitude using data described in the Global Gratitude Dataverse. Submission deadline is December 15.
The 2023 Big Team Science Conference (https://bigteamscienceconference.github.io/)  -- co-organized by the PSA -- is under wraps! There was 50+ presentations, 350+ registrants, and lots of big team science!
The 5th Open Innovation in Science Conference (https://ois-research-conference.org/) will be held May 21-23 in London. Submission deadline in January 15.
The PSA welcomes two interns who will be working with the Ethics Committee: Archana Raghavan and Arushi Srivastava!


big team science
Psychology should generalize from — not just to — Africa. Nature Reviews Psychology (https://www.nature.com/articles/s44159-022-00070-y)

How to build up big team science: a practical guide for large-scale collaborations. Royal Society Open Science. (https://royalsocietypublishing.org/doi/10.1098/rsos.230235)

‘Big team’ science challenges us to reconsider authorship. Nature Human Behaviour (https://www.nature.com/articles/s41562-023-01572-2)

The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up big team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)

The Psychological Science Accelerator’s COVID-19 rapid-response dataset. Nature Scientific Data (https://www.nature.com/articles/s41597-022-01811-7)
