---
title: "News from the Accelerator- March 2023"
author: "The Psychological Science Accelerator"
date: 2023-03-03
categories:
  - mailchimp backup
---

quick read
- The PSA COVID data paper (https://www.nature.com/articles/s41597-022-01811-7) is now published at Nature Scientific Data.

- We want to hear your voice! If you have not done so already, please fill out the PSA Network Motivation Assessment Survey. (https://www.soscisurvey.de/PSA_NMAS/)

- If you have not already done so, please be sure to join the PSA Canvas page (https://canvas.psysciacc.org/) .

- The PSA was highlighted in a new Nature feature (https://www.nature.com/articles/d41586-023-00575-3) on publishing challenges in big team science.


project updates
https://manybabies.github.io/MB2/


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The 002 team continues to revise the manuscript. The lead team should have full drafts ready to share with the network soon.

https://manybabies.github.io/MB3/


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The 003 team has nearly completed a draft of the manuscript that incorporates the network's feedback. The lead team should have full drafts ready to share with the network soon.
https://manybabies.github.io/MB3/


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The manuscript has received an R&R, and the lead team is working on revisions.

https://manybabies.github.io/MB3/


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

The PSA-005 continues to collect data, but has collected data from over 1,400 participants thus far!
https://manybabies.github.io/MB3/


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

37 teams have met the minimum data collection requirements. Additional progress has been made in terms of translation and most languages should be available soon (Hindi, Thai, Slovakian, and Slovenian). We anticipate to have additional labs joining us next semester. If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (http://007spaml@gmail.com) .

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

The Stage 1 Registered Report has received another Revise & Resubmit decision from Nature Human Behaviour. The lead team intends to complete the minor revisions quickly and then turn to data collection preparations.
https://manybabies.github.io/MB3/


COVID Studies (PSA-CR) (https://psysciacc.org/studies/psacr-1-2-3/)

The PSA-CR data paper (https://www.nature.com/articles/s41597-022-01811-7) is now published at Nature Scientific Data. This concludes the PSA COVID studies!


Canvas
The PSA is using Canvas (https://canvas.psysciacc.org/) to manage our activities. If you have participated in PSA projects, you should already have an account and received an invite to register and view your information. If you have not yet done so, please register so you can fill out your member profile, keep this information up to date, and join current PSA projects.

If you need the invite resent, please send a request to psa.membersite@gmail.com (http:// psa.membersite@gmail.com)  or you can simply go to the Canvas site (https://canvas.psysciacc.org/) , click "forgot password," and enter the email you signed up with. (Note that emails come from psa.canvas, which may go to spam.)


Membership survey
We want to hear from you! To plan for the future of the PSA, we have launched a Network Motivation Assessment Survey (https://www.soscisurvey.de/PSA_NMAS/). This survey will take 15-20 minutes to complete, but will help shape the future of the PSA.

Results will be shared with the network. If you have any questions about the survey, please contact Hasan Sharifian at hasan.sharifian@ut.ac.ir or in Slack.


big team science
The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)

The Psychological Science Accelerator’s COVID-19 rapid-response dataset. Nature Scientific Data. (https://www.nature.com/articles/s41597-022-01811-7)
