---
title: "News from the Accelerator- April 2023"
author: "The Psychological Science Accelerator"
date: 2023-04-03
categories:
  - mailchimp backup
---

quick read
- Reminder: Proposals for the John Templeton Foundation Special Call for Studies (https://psysciacc.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&id=08199acd5a&e=b1ca4b77d9) are due May 15.

- Members of the PSA, ManyBabies, and FORRT have published a new paper (https://www.nature.com/articles/s41562-023-01572-2) in Nature Human Behaviour detailing how big team science challenges conventional notions of scientific authorship.

- On April 5th, the International Network for the Science of Team Science will be hosting a free webinar (https://www.eventbrite.com/x/linking-scits-and-big-team-science-to-advance-complex-collaborations-tickets-600943737897?utm_source=eventbrite&utm_medium=email&utm_campaign=reminder_attendees_48hour_email&utm_term=eventname&ref=eemaileventremind) on authorship challenges in big team science.


project updates
https://manybabies.github.io/MB2/


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The 002 team is continuing to revise the project manuscript.

https://manybabies.github.io/MB3/


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The 003 team has nearly completed a draft of the manuscript that incorporates the network's feedback.
https://manybabies.github.io/MB3/


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The manuscript has received an R&R, and the lead team is working on revisions.

https://manybabies.github.io/MB3/


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

PSA-005 has collected data from over 1,500 participants thus far, and will continue to collect data into Fall 2023.
https://manybabies.github.io/MB3/


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

We have 27 languages translated and collecting data. 8 languages have completed the data collection goal and are now exceeding expectations! We anticipate to have additional labs joining us next semester. If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (https://psysciacc.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&id=3dab7b4f43&e=2a82fb47c9 ) .

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

The lead team is wrapping up minor revisions to the Stage 1 manuscript and will resubmit soon. Collaborators have been asked to complete a data collection survey on Canvas.


Reminder: Special Call for Studies
The PSA, supported by the John Templeton Foundation (JTF), welcomes study proposals to test the generalizability of phenomena related to JTF strategic priorities with large, global samples. Full proposals are due by May 15.

Please see the official call announcement (https://psysciacc.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&id=08199acd5a&e=b1ca4b77d9) for details about proposal requirements, grant support, and the project selection process and timeline.


big team science
‘Big team’ science challenges us to reconsider authorship. Nature Human Behaviour (https://www.nature.com/articles/s41562-023-01572-2)

The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up big team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)

The Psychological Science Accelerator’s COVID-19 rapid-response dataset. Nature Scientific Data. (https://www.nature.com/articles/s41597-022-01811-7)
