---
title: "News from the Accelerator- May 2023"
author: "The Psychological Science Accelerator"
date: 2023-05-08
categories:
  - mailchimp backup
---

quick read
- Announcing a new PSA study: Moral experiences across cultures (PSA-JTF1)
- Ashland University is hiring a full-time Research Coordinator to support the PSA
- The PSA Study Selection Committee is seeking new members


project updates
https://manybabies.github.io/MB2/


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The 002 team is continuing to revise the project manuscript!

https://manybabies.github.io/MB3/


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The 003 team is continuing to refine the manuscript based on the network's feedback.
https://manybabies.github.io/MB3/


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The manuscript has received a revise-and-resubmit, and the lead team is working on revisions!

https://manybabies.github.io/MB3/


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

The 005 team collected data from over 1,500 participants thus far, and they plan to continue collecting data into Fall 2023.
https://manybabies.github.io/MB3/


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

The 007 team has collected data from 14,000 participants and 28 languages (with three more in the works). They anticipate having additional labs join next semester. If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (https://psysciacc.us18.list-manage.com/track/click?u=f8bacf294e5a46e350b638374&id=3dab7b4f43&e=2a82fb47c9 ) .

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

The lead team has submitted the minor revision of the Stage 1 manuscript and is now beginning to make preparations for data collection.


Announcing PSA-JTF1: Moral Experiences!

How do people experience morality in everyday life? And how might these experiences vary cross-culturally? PSA-JTF1 will use experience sampling methods to examine the nature of moral experiences in countries around the world. We will investigate the types of moral experiences people have, the relationships between moral experiences and cultural and individual factors, and the impact of moral experiences on emotion and behavior.

Interested in learning more and potentially joining the project? Fill out this survey (https://docs.google.com/forms/d/e/1FAIpQLSdR0v-_kRxi0ipLb1YqbVlvhhQ_gOiwMhim_X0r-AVbrjur3w/viewform?usp=sf_link) !


Research Coordinator position

A new full-time position as Research Coordinator for the PSA is available at Ashland University to work with us on our JTF funded project, “Examining the Big Questions in Big Samples: Using the Psychological Science Accelerator to investigate JTF priorities''. This position is a unique opportunity for someone who is excited about a career in research and looking to build their experience (and CV!) at the post-bacc level while being centrally involved in PSA projects. Click on this link (https://jobs.ashland.edu/postings/4157) to see the ad and submission portal.

Review of applications will begin immediately, with a final deadline for submission of May 31st. If you have any questions, you can email Chris Chartier at cchartie@ashland.edu.


Study Selection Committee is recruiting new members

The Study Selection Committee is seeking new members to aid in selecting projects, beginning with the PSA's most recent call for studies. This is a great opportunity to play an important role in the process that determines the very studies that the PSA carries out! If you are interested, more information can be found here (https://forms.gle/wLtXHAhxjZFfsM6z8). Please apply by May 11th (wherever you are). Small stipends will likely be available for members who contribute to reviewing submissions to the JTF call! Certificates of recognition for reviewing work can also be given to members who would find this helpful for their CVs.


big team science
‘Big team’ science challenges us to reconsider authorship. Nature Human Behaviour (https://www.nature.com/articles/s41562-023-01572-2)

The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up big team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)

The Psychological Science Accelerator’s COVID-19 rapid-response dataset. Nature Scientific Data. (https://www.nature.com/articles/s41597-022-01811-7)
