---
title: "PSA Membership Survey"
author: "The Psychological Science Accelerator"
date: 2023-02-06
categories:
  - mailchimp backup
---

Why do people join big team science?

Dear PSA Colleague,

We are excited to launch the Network Motivation Assessment Survey (https://www.soscisurvey.de/PSA_NMAS/). We want to understand the various reasons people join, and stay, in the PSA.

The survey is a little long (15-20 mins) as it contains questions of interest from the associate directors, community building, and funding & finance committees, but we hope you can take the time to answer it as the information you provide will be very important in the various decisions moving forward.

Results will be shared with the network. If you have any questions about the survey, please contact Hasan Sharifian at hasan.sharifian@ut.ac.ir (mailto:hasan.sharifian@ut.ac.ir)  or in Slack.

We truly hope to hear from you!

Yours,
Hasan Sharifian on behalf of the Community Building and Network Expansion Committee and the Funding and Finance Committee
