---
title: "News from the Accelerator- January 2023"
author: "The Psychological Science Accelerator"
date: 2023-01-16
categories:
  - mailchimp backup
---

quick read
- The PSA-Affiliated Global Gratitude Project is seeking collaborators. More information can be found in this flyer (https://docs.google.com/document/d/1bnjI7w9OmP7WggdSx302dC-FJGPFUjK3asrZs3UDB18/edit?usp=sharing) .

- Reminder: the PSA has released a second special call for studies related to John Templeton Foundation strategic priorities.

- The PSA has publicly posted an end-of-year financial report.


Seeking collaborators for the Global Gratitude Project (https://docs.google.com/document/d/1bnjI7w9OmP7WggdSx302dC-FJGPFUjK3asrZs3UDB18/edit?usp=sharing)
With funding from the John Templeton Foundation (https://www.templeton.org/news/is-gratitude-universal) , Shige Oishi, Nicholas Coles, and Michael McCullough are seeking potential collaborators for a PSA-Affiliated cross-cultural examination of online, 30-minute, single-session gratitude interventions on subjective well-being. This will include both (1) standardized gratitude interventions traditionally developed and validated in WEIRD samples, and (2) localized (e.g., culturally tailored) gratitude interventions that collaborators might design if they so choose.

More information can be found in this flyer (https://docs.google.com/document/d/1bnjI7w9OmP7WggdSx302dC-FJGPFUjK3asrZs3UDB18/edit?usp=sharing) , and potential collaborators can express interesting using this form (https://docs.google.com/forms/d/e/1FAIpQLSd5vc37gpw1tvTfdrPgADDkvXv9caD4L-eQ66deUL0UsMcrPA/viewform) .


project updates
https://manybabies.github.io/MB2/


Object Orientation Study (PSA-002) (https://psysciacc.org/002-object-orientation/)

The 002 team continues to revise the manuscript. The lead team should have full drafts ready to share with the network soon.

https://manybabies.github.io/MB3/


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/003-gendered-prejudice/)

The 003 team has nearly completed a draft of the manuscript that incorporates the network's feedback. The lead team should have full drafts ready to share with the network soon.
https://manybabies.github.io/MB3/


Justified True Belief Study (PSA-004) (https://psysciacc.org/004-true-belief/)

The manuscript has received an R&R, and the lead team is working on revisions.

https://manybabies.github.io/MB3/


Stereotype Threat (PSA-005) (https://psysciacc.org/005-stereotype-threat/)

The 005 team is continuing to collect data.
https://manybabies.github.io/MB3/


Semantic Priming Study (PSA-007) (https://psysciacc.org/psa-007-spam-l/)

The 007 team continues to collect data. Most languages will be available soon and the lead team anticipates having additional labs joining us next semester. If you are interested in becoming a collaborator, or want to learn more about 007, please e-mail the project leads (http://007spaml@gmail.com) .

https://manybabies.github.io/MB3/


Minimal Groups Study (PSA-008) (https://psysciacc.org/psa-008-project-information/)

A revision of the Stage 1 Registered Report manuscript was recently submitted to Nature Human Behaviour.
https://manybabies.github.io/MB3/


COVID Studies (PSA-CR) (https://psysciacc.org/studies/psacr-1-2-3/)

The PSA-CR data paper (https://osf.io/byqha) proofs have been received and were sent out to all collaborators.


Reminder: Special call for studies on John Templeton Foundation strategic priorities (https://psysciacc.org/news/2022-12-06_second-special-call-for-studies-studying-generalizability-with-global-samples.html)

The PSA, supported by the John Templeton Foundation (JTF), welcomes study proposals to test the generalizability of phenomena related to JTF strategic priorities with large, global samples. Optional initial proposals are due by February 15 and required full proposals are due by May 15.

Please see the official call announcement (https://psysciacc.org/news/2022-12-06_second-special-call-for-studies-studying-generalizability-with-global-samples.html) for details about proposal requirements, grant support, and the project selection process and timeline.


End of year financial report (https://opencollective.com/psysciacc/updates/2022-end-of-year-update)

A copy of the PSA's end of year financial report is publicly available available here (https://opencollective.com/psysciacc/updates/2022-end-of-year-update). This report provides information about (a) the financial infrastructure we developed this year, (b) a selective list of 2022 accomplishments, and (c) some ideas for what 2023 might look like.


big team science
The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)
