---
title: "News from the Accelerator- May 2024"
author: "The Psychological Science Accelerator"
date: 2024-05-01
categories:
  - mailchimp backup
---

quick read

- We've added a new section to the newsletter! Check out the member highlights to read more about PSA member achievements!

- PSA-008 has started data collection!

- Co-directors Erin and Savannah are hosting weekly office hours!


directorship transitions
In this past month, we have fully transitioned directorship, and we want to make sure we pay tribute to our past director. Nicholas Coles has been guiding our community for the last three years, and in those three years, his guidance of the PSA has provided financial and administrative stability. The organization transformed into an astounding presence in the Big Team Science field with nearly 100 geopolitical regions and more than 2000 researchers, changing the landscape of team collaborations within social sciences. During this time, the PSA received funding, encouragement, and recognition from top institutions, and the current administrative team has provided stability to continue smooth operations. We are sad to see him step down from directorship but are stoked to continue to collaborate and support him in his new transitions. Please make sure to give Nicholas some kind words as he transitions to his new role as a tenure track professor!

Erinnah (Erin and Savannah) are also hosting weekly office hours on Mondays at 10 am CDT/ 3pm UTC. These are times when members can drop in and chat with the directors about anything. We hope to see you drop in soon! The zoom link and PSA calendar can be found here (https://calendar.google.com/calendar/u/0?cid=c25sbjM1bDJpNm8xcG4zdXVicmd2M3FkMTBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) .


member highlights
PSA member Lusine Grigoryan received the APS Rising Star (https://www.psychologicalscience.org/members/awards-and-honors/aps-rising-stars/news-rising-stars) award this year! Congratulations Lucy!
PSA member Ekaterina Pronzius received FSR Incoming Post-doc fellowship granted by the UCLouvain University, Belgium to study social cognition in Borderline Personality Disorder.

Ekaterina is deeply passionate about the BTS in the clinical domain and is going to probe this idea during their fellowship. Please feel free to reach out to them (mailto:ekaterina.pronizius@univie.ac.at) anytime if you share similar interests.


news in big team science
PSA member Patrick Forscher's team at Busara is hosting this year's annual meeting for the Society for the Improvement of Psychological Science. You can still register for the conference here (https://www.improvingpsych.org/SIPS2024/) !

In addition, they will be launching an edited book at the conference focused on a new subdiscipline we are calling "developmental meta-research", or the intersection of global development and meta-research. The book features 20 pieces focused on this topic. Stay tuned if you'd like to learn more!
If you haven't read this paper (https://www.nature.com/articles/s44271-023-00003-2) that several PSA collaborators were involved in, make sure to give it a read!


project updates


Object Orientation Study (PSA-002) (https://psysciacc.org/projects/psa002.html)

The lead team has completed the process of revising the paper for submission to a new journal. In response to feedback from the network they are exploring journal options and anticipate a new submission of the manuscript in the coming weeks.


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/projects/psa003.html)

The lead team is reformatting the paper with the goal of submitting to PLOS-One.


Justified True Belief Study (PSA-004) (https://psysciacc.org/projects/psa004.html)

The manuscript was accepted for publication at Advances in Methods and Practices in Psychological Science!


Stereotype Threat (PSA-005) (https://psysciacc.org/projects/psa005.html)

Data collection will continue through the rest of the semester so that the thresholds of evidence described in the pre-registration can be reached.


Semantic Priming Study (PSA-007) (https://psysciacc.org/projects/psa007.html)

The lead team is currently finishing writing up the results and discussion. Collaborators should expect a manuscript this month. Thank you to all that have contributed to this expansive dataset!


Minimal Groups Study (PSA-008) (https://psysciacc.org/projects/psa008.html)

Data collection has started at a couple of sites and will soon be expanding to more!


PSA-JTF-001: Moral Experiences (https://psysciacc.org/news/2022-12-06_second-special-call-for-studies-studying-generalizability-with-global-samples.html)

Data collection is ongoing at a few sites, and translations have been completed in several languages. For more information about the project please see the preprint (https://osf.io/preprints/psyarxiv/jktnv) or email the project leads (mailto:psajtf1@gmail.com) .


PSA-JTF-002: Dignity Honor Face (https://psysciacc.org/projects/psajtf002.html)

The lead team is currently soliciting feedback from collaborators on the Stage 1 style manuscript (the introduction and methods to the eventual paper). This project welcomes interested collaborators who can collect data. Interested in learning more and potentially joining? Fill out this survey! (https://docs.google.com/forms/d/e/1FAIpQLSfifQfg-HQdZ-AIoSACu2yeI5bR_DA6nqexmjI0S8GdRaaVWA/viewform)


PSA-JTF-003: Error Correction (https://psysciacc.org/projects/psajtf003.html)

The lead team has now pretested several possible manipulation wordings and has settled on a final version. Over 150 collaborators have been onboarded to the project and will have the opportunity to provide feedback on an updated draft of the manuscript very soon!

This project still welcomes interested collaborators who can collect data. Interested in learning more and potentially joining the project? Fill out this survey! (https://docs.google.com/forms/d/e/1FAIpQLSdEqUp0cOb-duJXvd3C1-DBX8dTZOksDyV-3fh4KFeKyCYrOg/viewform)


PSA-AF-001: Partner Preferences (https://psysciacc.org/affiliated/af001.html)

The Stage 2 Registered Report has been submitted to Journal of Personality and Social Psychology!


big team science
Psychology should generalize from — not just to — Africa. Nature Reviews Psychology (https://www.nature.com/articles/s44159-022-00070-y)

How to build up big team science: a practical guide for large-scale collaborations. Royal Society Open Science. (https://royalsocietypublishing.org/doi/10.1098/rsos.230235)

‘Big team’ science challenges us to reconsider authorship. Nature Human Behaviour (https://www.nature.com/articles/s41562-023-01572-2)

The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up big team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)
.

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)

The Psychological Science Accelerator’s COVID-19 rapid-response dataset. Nature Scientific Data (https://www.nature.com/articles/s41597-022-01811-7)
