---
title: "Journal Opportunities and Options"
author: "Erin Buchanan"
date: 2024-06-03
categories:
  - welcome
---

PSA member Biljana Gjoneska has recently become an Editorial Board member for the following journals: Journal of Behavioural Addictions, BMC Psychology, PloS ONE, and Discover Psychology. Here's her message:

Hence, I would like to use the opportunity and extend invitation to all PSA members to consider these journals as potential venues to: a) Submit a paper (in a role of an author) b) Evaluate a paper (become a reviewer) In both cases, the scope of the journal should be aligned with the research interests of the interested candidates. For the latter case, there are some tangible benefits to becoming a reviewer (aside from the opportunity to be updated on the latest research and to sharpen the critical thought), including: public recognition of reviewing services via the reviewer hub (on Web of Science) or/and sometimes via the journal (in annually published lists), possible discounts for publishing in the journal, possible invitations to become a member of the Editorial Board etc.

Therefore, I would be very grateful if you could publish my Call for Reviewers for the appointed journals along with the update regarding my academic advancement, and invite all interested candidates to express interest by compiling the following form: https://forms.gle/UE9MGmQkEbAjFbbH8 Looking forward to the prospects for extended collaboration with as many PSA members as possible.

Warmly, Biljana Gjoneska