---
title: "PSA Associate and Assistant Director Elections!"
author: "Savannah Lewis"
date: 2024-08-15
categories:
  - elections
---

Accelerators,

In the coming months, we'll be seeking to fill several leadership positions in the PSA. Below is a quick run down of those positions and how we will fill them.

Assistant Directors 
We are currently looking to fill two Assistant Director positions, one for each of the following committees:
- Project Monitoring
- Translation and Cultural Diversity

If you'd like to apply for assistant director positions, please fill out the call for Assistant Directors on Canvas (Log into Canvas > PSA Membership > Modules > Elections or use direct link https://canvas.psysciacc.org/courses/1/quizzes/270). Submissions due October 1st. The Director and Associate Directors will select a candidate for each position. If you have any questions about this application or this process, don't hesitate to reach out to the directors (via email psysciac...@gmail.com, slack, or by pigeon). If you need a PSA account or how-to complete tasks on Canvas, check here: https://member.psysciacc.org/.

Associate Directors

We are currently looking to fill two Associate Director positions! Any member of the PSA is eligible to run for Associate Director. If you’d like to nominate yourself or someone else for one of the Associate Director positions, please fill out the call for Associate Directors on Canvas (Log into Canvas > PSA Membership > Modules > Elections or use direct link https://canvas.psysciacc.org/courses/1/quizzes/271). Submissions due September 15th. We’ll reach out to all nominees to confirm whether or not they’d like to run for office. Once accepted, nominees will submit their 1,000 word statement by September 30th, 2024. The Network will have until October 15th to submit their votes. If you need a PSA account or how-to complete tasks on Canvas, check here: https://member.psysciacc.org/.

To see the full version of how these positions work and their roles, see the full call here: ELECTION CALL FOR 2024

If you have any questions about either position, feel free to email the directors (psysciac...@gmail.com).