---
title: "December News from the Accelerator"
author: "Erin Buchanan"
date: 2024-12-04
categories:
  - newsletter
---

December Newsletter from the PSA

## Quick Read

- Our project PSA004 Justified True Belief has been published!
- Reminder: Proposals are due tomorrow
- See our Call for Assistant Directors for the Data & Methods Committee!

## *PSA News*

*Call for Assistant Directors!
* We are currently looking to fill two Assistant Director positions both within the Data and Methods Committee.

*Submissions due December 9th.* The Directors and Associate Directors will select a candidate for each position. If you have any questions about this application or this process, don't hesitate to email the directors at [psysciaccelerator@gmail.com](mailto:psysciaccelerator).

For details about these positions, see: Assist Dir. [DM ELECTION CALL 24]( https://docs.google.com/document/d/14OP6n6IjSRrt8yEGPRt7W8HNOoe4Oc65W0A1kS3T5xo/edit?usp=sharing )

*The* *PSA Call for Studies 2024.* *Submit your proposal by* December 5th *for full consideration*. [Read our Call for Studies]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV8q49l1MuXni4Bd1VAqQDqAGNPBDrUus68eduRHuyLxAiY7G-2BR9m4I3LdELkcl-2BiMfVW933lNmQrUUt2mI1xfHIiWQSwVUkeMcfRgSFWKY2eRvp1eq85NKMIIWcpksSJG0CJKrg1h6rBFlhZSQhiDLM-3D852-_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtZs73eT4U8oOxLQxTfgUoMtPXVd9LnND6qw7n7TLri5r3LrWnw20FMn5xUdR6QcjBkKu8yPRkZA0VUeoW6PaQXIn5kHFczqSF4kUnOaguvGO9gX4vvbqH-2BhmyrV9TABCnyfWWrbXdzRmeeC1-2FTG5FD05zYJ-2BUeLweYSAj2lp25sCQ-3D-3D ) document, or watch the video-recordings of our workshops on [Youtube]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV6LFIOi1LYUj5vdL0VrAklATLUoD2TVtnu5U00dgsY3Y6z0Z6OuvpqU73ynFev7rJB-2B4Y6chqimpszEA24Qs6dY-3DUJw-_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtYD-2BE5WaOfwX8hREt-2BREcYH03xmdUXKpyd4RWl3ZQjh0sFw-2FGoUoOhVO5Fx996vE2f2uSXkjB-2F0qcQE3A-2FK8gMtkaSnY2BUmOjnEn8dQy6iBtnYN7wve6ZcLPVA7TMOxmCAs4BGqICWjLyUU9n21VVhSy9410JC6LWogJ6SsSOO3g-3D-3D ). For inquiries, email psysciaccelerator@gmail.com with subject line "Call for Studies Questions".

Drop in at our directors' weekly office hour on Mondays, or email psysciaccelerator@gmail.com with questions. Find the Zoom link in the calendar [here]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV05Vza73M-2BiiiiuJM2iuDWgeka8Gb95BCrmV3AvbS4oEWt-2FlC1XWhc0vfgji6AGhyl-2FG6E8vCq0s0HRzBVoe4Hri6dvbH61QO55MI09EoXVRAlrLtdHoeTJJThjDy-2BojpfkiEKckwtgarsDbgoLIzhM-3Dpkkw_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtZ6ONc3veQdN3DY6nW6oteHquU2CQmskuP6sVdn2oRTBmPjMaNoJ8SihIN2jeZEBf5xzGQIOAyd9EnWAyhgM44v6j28EXO9QoQlgVY0b5Rj6k7iDyTmsOAoMLVI2yrV1tbW22sPlLyw0n5vMV0ZJl0f-2BA735ZUvkbD7c7tWaML4qw-3D-3D ).

## *News from Big* Team Science

### COS updates policy framework for transparency and openness

The Center for Open Science (COS) has introduced a major update to the Transparency and Openness Promotion (TOP) Guidelines, dubbed TOP 2025. For 10 years, TOP has been an influential policy framework designed to enhance the verifiability of empirical research claims in research. The revisions streamline the framework and improve conceptual clarity surrounding research practices and levels of implementations of those practices. The revisions are the result of an extensive consultation process with the TOP Advisory Board, co-chaired in 2024 (and chaired in 2025) by Suzanne Stewart. [Read more]( https://www.cos.io/blog/new-preprint-introduces-major-update-to-the-top-guidelines )

### Call for Submissions to SIPS 2025

The Call for Submissions to SIPS 2025 is now open! Please see the submission portal, powered by Pretalx: [online event]( https://pretalx.com/sips2025-online/ ) & [in-person event]( https://pretalx.com/sips2025-budapest/ ).

## Project Updates

* [Object Orientation Study (PSA-002)]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV0vycgPaSBdgfWuGDFXryaUpK-2BxNNEGJbQoHmmm3OuCsZQTsrSkBPt1vOGJ4iuvCuw-3D-3D3wds_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtbNDhDWRbSU9Obj5oep2osHBALQecMdYRHKM4Nt-2FXlT-2B0VE4MLAbMGFlPMlIh6U0b1WNFh6YDfhWabo9ZJD4bukQQLQJ2AygEuwMeogcdJf-2Fh6p3Ch5bnnqetN5tinBAnbrtTUpKIwFMrdbh9NXhQNg4w6XiXhOEMMBg9xL8kMvlg-3D-3D ): The manuscript is under review at Current Psychology.
* [Gendered Prejudice Study (PSA-003)]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV0vycgPaSBdgfWuGDFXryaV7qL6Iqi6KcBo9LwOb-2BH5gUfC5DxAOlp8OgohZnZxPHg-3D-3DpgwF_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtZoDaKkUCsWb6UKrCRh4kISoj37ByitoWc-2Fnl1B7J4JIrYac02OOCYMDrHiJnegqbCUbPVnnessVvjYGOZKWmRAESsYfZceBMSDaQsbAgq22ZiBes1menHWTWeYcuN3XzZW02P2eAVvutPF6zZ35EkKj8NMb9pHDHSx5irC-2BbjONw-3D-3D ): The manuscript is under review at PLOS ONE.
* [Justified True Belief Study (PSA-004)]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV0vycgPaSBdgfWuGDFXryaVtPB-2BcRxYBGMPuP1jCb1-2FDfye-2Bq-2FpsQCPdLda2-2FRS8rA-3D-3DrNC6_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtb8jyBicTtvcAkFhlGp3ZsCKG3nAU-2B11w33YUBytfCIDtFWusCumg3YP6Goc0KenBySFpxCWqEpJPCIPud9IMQ9tw0aJmIIRjTZr0CFxlGPn67jDyMFFHquiTZW4B8PKh4VtmSWPG2o2Aaj8zTFQnVu9A607XmYGE-2F2x58uLwgHxQ-3D-3D ): The paper has been published in [AMPPS]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeVxOpSa2h3g6Wf7po-2By-2B5WnXBCVcQZhnr9Z-2BOiReHyCQmA76usER1QrlIkv6rmU6rXn9vSTGTOLnIiceO3hZdCio-3DEMjq_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtZ6yeJoHYZOGXgxOIEEK13C-2BIAIbAqHvIoW-2FGTL5XZ6vzLoSHEGONS1XyM1-2BGL5eZ1jUBeNX84XPcJY7xf-2FYiOH36G2YIOTrcSRNCxV2H2cw3Yzr94hfzJ5tm0a7ARY-2BD0SvlR0aXWHrcPPT9RYIf8fCgujI7SBaD9qcbRgYC8qPA-3D-3D ).
* [Stereotype Threat Study (PSA-005)]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV0vycgPaSBdgfWuGDFXryaV1KT2rJs1c6EbWWFIgLOgA12bgcWj344jfxQld4j-2B04A-3D-3D1Ir8_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtYdbMMFFIDeGbxoj8ZsMpyFVyxp9gy0Ia43zDtDltAApRkJBpufohHgJwIeNa-2FB3Y6pGJ36JozyxFoGd-2BAFjDIDZEgoj5nNmy9F8SXmuxOzlIjeVQ-2BEbS3-2B7Zc8SYnSeVN2IiBMmuPMjuc2TQGo8GhPtFSOGPb-2FZzApcymSLEcaFw-3D-3D ): We are working on the final analyses and robustness checks.
* [Semantic Priming Study (PSA-007)]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV0vycgPaSBdgfWuGDFXryaV73p2pHUxhshoH2BacTBVJJ5m4ppUCuUocfRUhXpNQqw-3D-3Dwvhj_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPta8Q2qOCCqYc1XRbCh4uq-2FeIqsk9o4Av5iGTVO4IYl8g0OychxWvafIf-2FTI-2FU65bh10oRpHSddcgz84N7PY4MscC78omcWm2vOhh-2BFWsQkLNrbJnw1qCBtOtC0ID282J7UtsFfOgOjSWqJRkVk-2Bhq188vG-2FDYkrLZ66G4vx4kK2Yg-3D-3D ): The manuscript is under review at Nature Human Behaviour.
* [Minimal Groups Study (PSA-008)]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV0vycgPaSBdgfWuGDFXryaXFM3OfkqJ5MBGI34Fa2zDuDOpBPAih9VM1XtI3-2FbLYXw-3D-3Dp2dX_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtaj5RGclMRMOVOoNEeAUDFBHe5Mht6qp-2FLwmeqIfek4KDpZo4x63KU7mM0XXYMH2covJY7NbBJwzECtcZyHymIzPHP592xzGNpPZoPQy4vmFHZUOFVPpvBi-2BKc1aE3lGF-2F3Iw5L3zOd-2FQUEtNaAhlXIWHLjkG-2BEtUJbmDEWzCNCbQ-3D-3D ): Data Collection is ongoing in 20 countries, and the project has collected data from over 6500 participants. More sites and countries will soon begin their recruitment as translations become available.
* [Gendered Leader (PSA-009)]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV0vycgPaSBdgfWuGDFXryaWPS09wV8OEdZgt0nlck7vDEEBWxg7XjuSDYunMwbIkWw-3D-3DxRVc_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtZN6FuBajMVroit7FmGlfo8vBtqytqM4bdRxarC3JXVcPPxra-2FOTI0YWzAG3iRO2iEfqLW0mW3-2F-2FU4NWKu2eQfUyACllN8y2dwcS7e-2B4ago-2FY8gaZV7AKvxoXiKKEwnjuixrQOJuRxpXXaT-2BW2t-2BWGANfcTgKnKactMei8nm4DVlw-3D-3D ): The second phase of collaborator recruitment has gone smoothly.
* [Moral Experiences (PSA-JTF-001)]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV0vycgPaSBdgfWuGDFXryaUt1bFZFaXtpQjfS-2FcbZPQyyfs1snnRYCgd2Q5f85LsSw-3D-3D6U5i_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtbY7a2NLyFXlY59xU8FBJ5Vv-2FpXty9OAKGpSXNwzLwuzgAfw3jg2IfVI8ILSl7IvMutzK9A7eXl1jwsCUeTkQxIz3SIcWHiBoxSqU3wAgZBLXx0znmCedGqRzh5F0TNtF6cY1kxtXmGfm4VFUXD4BDjpkcfwQgg6hNcdk8GSffq-2FQ-3D-3D ): Data collection has now started in all countries included in the project and will be complete in several countries by the end of the year.
* [Dignity Honor Face (PSA-JTF-002)]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV0vycgPaSBdgfWuGDFXryaUt1bFZFaXtpQjfS-2FcbZPQyA9wdDgcZluV1h-2F-2BIl5r3AQ-3D-3D5wtr_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtZAe9LWhhFQujFMgfnx-2FOoqMNvTtA1YeSbcn0-2FqZxm5n9kBQAY9EURsn3VqR8YXpelBsiQf7MU3bnTP85QlIQvFxBN-2BS5zufDnDzYIZiuf-2BOX7BqJSFS9-2BugPKNspkobr9aNWlaVUilnBz4Otf6U9i8orS47MdwMIRa-2BeEQ-2F4NmRA-3D-3D ): We’ve collected data from over 1000 participants in English, and implemented our first translations! We are still looking for translators in Dutch. If you would like to join the project to help with translation in Dutch, even if you are unable to collect data, please email us (psajtf2@gmail.com).
* [Error Correction (PSA-JTF-003)]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV0vycgPaSBdgfWuGDFXryaUt1bFZFaXtpQjfS-2FcbZPQy-2BWVIQioC5yypd-2Bu2y40MMw-3D-3DGJ2-_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtaX9570Xay9P6LqcP1dw6rexo84bj1rZMToSpVojShERtP7fL-2BzEmbAjaNyxXEvnU7IC1OLq3XhwRuzkSyfMoUEhSEkxO-2BHF5m24T21C5NDMMVA5ScO6tbVi27UVQnoVeVl3-2Bar6-2Fv6vbgsfMnSqYdDBOV6VllDRreyWKK6HjjkCw-3D-3D ): We are preparing to start data collection! The translation process will also start soon. Interested? [Fill out this interest survey.]( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV8q49l1MuXni4Bd1VAqQDqC6-2FusfAcx1hi5aN1YbjPsXyM4Do-2BuYK1X3l4Q4-2FG3KhiFm-2B9yl1ft1MJi757-2B6UoVe0y-2BUf27HfmD4iiXY6rFD5ehXn8uKQhN4Fd2-2F3Xv3bQ-3D-3D-Pu0_Rcb23OIlvHN4FvPSWf8hhMFb-2FZ-2FVLGaZUI4ArPjur3vFZZU-2BJbm-2FeCSYMWicUzaHNgk5-2BUcwMAhm9Y9RqIXWDEDvPo5arqIywIdtXB2IwvkSxcLi29o3qgmTa-2FbvycefHOL-2BIxO3CjpNkhSVWRUiCXbe-2BKuuqNznsazYRItaRP7vRM0AC2Ca3pXAqpQ7SPWysx3UDY35HLB5qx3Sd35Vp0ppq389OJOWGDKrSP4DnR24fVzfq47wTsKAp7zMuwVALBGuTr1383DVyQxZTptxGIay0-2FuRj-2Bt9XndSVpbEgNq74Hst1fDUHF-2BDwQkKL1tCx5AWx2Q6-2BkZnQ9nQIVlgxWeqB8HoV1MI9EPo0giOunL80hmnKPmwo0QITehJPJHDLrPG7qGLqzCjePCymOpQUnbp5xYKDVCRWbO6uET6PPklBa76P4RYMGMIgWowSTXd7Q5ujp8UmA7a7zupOuXKJ-2BQmwQS6z5rsGjlI6zHF3TDGJA3cl-2BvUCpjGZs1zw7bVR4f19BQ89BMrhvTr3kW3fb9kQ5dFq-2F2zOrsgD02ieWfsnvvST0VTf5qLdBmzghIYSEjYNO5HlhowjnOKHrlbJ0BPHUY-2BQn041iajtklEbpTjpRcieq0v4fsf0tiYpOp4oucKWfCz3wI70AtKAtmyUJbUO453i7DFCLuOjQmqjA2usUqfy4XzHk8-2FRjYy5FrJ5TjHgB2gZqqwC-2FPrx8gB2o9GqVSQT-2B69kMHgQtZvPtaw8zIaKhq-2BjRyi7693l28o-2Ba4AqUgC7RRE1QW91ee9Xsj8sHjX2YIS3P7DKTPgIbnLXsyb8x6iQgUQre9UsKItQq1yyexeFX-2FOcmkEFiSUZbjTyFxvDb9kc2pqf4Hr1VauFF84eGY9pPRfVXS2fjBK6ZDsp82TtylORyV-2BPR2E2w-3D-3D )