---
title: "Elections September"
author: "Savannah Lewis"
date: 2024-09-30
categories:
  - elections
---

Accelerants,

Our PSA election process continues. Today I’m sharing the names of candidates and their statements describing why they've chosen to run and what they'd like to achieve if elected. There are three candidates for Associate Director. All statements are linked by position and name in alphabetical order below. 

Associate Director

Ekaterina Pronizius (#pronizius-ad-election) (Statement)

John Protzko (#protzko-ad-election) (Statement)

David Vaidis (#vaidis-ad-election) (Statement)


We will be seating two Associate Directors. 

I’ve set up a channel for each candidate in the PSA Slack workspace (channel names are noted in parentheses above). Feel free to use these channels to ask candidates questions to support your decision making. To join these channels, click “Add channels” in the PSA Slack navigation panel on the left side of the workspace. If you haven’t yet joined the PSA Slack workspace, you may do so here. The Slack channels will be available until the voting period ends. 

The two-week voting period will begin on October 1, 2024 and end on October 15, 2025. Voting is currently housed on Canvas and can be found in your membership course. The link to the quiz is here (please make sure to login before navigating to the link). We expect to certify the results within a week after the voting period ends; those who are elected will take office in November 2024.

Thank you to the candidates for their willingness to run and to the election tellers for continuing to monitor the process!