---
title: "September Newsletter"
author: "Savannah Lewis"
date: 2024-09-01
categories:
  - newsletter
---

Dear everyone: we apologize for having to add you to another google group. Our mailing list group is somehow broken, and we cannot send email to it. After trying for several days and going through google support, we decided to make a new group. Remember, there’s a link at the bottom of all our newsletters to unsubscribe if you would like to not receive these updates. 

quick read

- The PSA is looking for Associate Directors and Assistant Directors! 


- Submit your proposals to the PSA Call for Studies. If you missed the workshops, video-recordings are on Youtube.


Announcing PSA-009!


PSA-009 aims to investigate the impact of women’s political representation on people’s tendency to think of political leaders as male. Despite very little (if any) evidence that men are more effective leaders, beliefs persist around the world that men make better political leaders than women. 

PSA-009 will conduct a multi-country test of gender-fair language intervention for stereotype bias. We expect that the completed project will be published in The Leadership Quarterly, where we have in-principle acceptance.

Currently, we are looking for labs that can recruit a minimum of 100 local participants in the following languages (and locations): Armenian (Armenia), Chinese (PRC), Czech (Czech Republic), Danish (Denmark), Dutch (Netherlands), English (UK), Filipino (Philippines), Finnish (Finland), French (France), German (Germany), Hungarian (Hungary), Italian (Italy), Japanese (Japan), Korean (South Korea), Norwegian (Norway), Persian (Iran), Polish (Poland), Portuguese (Portugal), Slovak (Slovakia), Spanish (Spain), Swedish (Sweden), Thai (Thailand), Turkish (Turkey), and Vietnamese (Vietnam).

If you are interested, please complete this survey by 15 September!



The PSA is currently looking to fill two Assistant Director positions, one on each of the following committees: Project Monitoring; Translation and Cultural Diversity. To apply, please fill out the call for Assistant Directors on Canvas by October 1st. The Director and Associate Directors will select a candidate for each position. If you have any questions about this application process, please reach out to the directors (via email psysciac...@gmail.com, Slack, or by pigeon).


We will also be holding elections for two Associate Director positions! Any member of the PSA is eligible to run for Associate Director. To nominate yourself or someone else, please fill out the call for Associate Directors on Canvas by September 15th. We’ll reach out to all nominees to confirm whether or not they’d like to run for office. Once accepted, nominees will submit their 1,000 word statement by September 30th, 2024. The PSA Network will have until October 15th to vote.


Reminder you can see the roles and the full call here - ELECTION CALL FOR 2024.


Submit your proposal to the PSA Call for Studies! The first deadline for full consideration is September 15th. Video-recordings of our workshops are available on Youtube. Please see the official call announcement for details about proposal requirements and the project selection process and timeline. For inquiries, email psysciac...@gmail.com with the subject "Call for Studies Questions".


Drop in to the directors’ weekly office hours on Mondays 1pm UTC. Come and chat about anything! Find the Zoom link and PSA calendar here.


news from big team science

Registration is open for the first doctoral training course in Open and Credible Science in Norway. The course is part of a PhD programme at Østfold University College, Norway, but is open to anyone and will take place in Fredrikstad (1-3 October) and Halden (5-7 November). A hybrid format is also available for online participation.

The course will be delivered in English. Participants who complete the assignments and an exam will obtain 5 ECTS credits. 

See this page for more information about the course, or this page to join. 

project updates

Object Orientation Study (PSA-002)

The manuscript is under review at Current Psychology.

Gendered Prejudice Study (PSA-003)

The lead team is working on uploading author information into PLOS ONE.


Justified True Belief Study (PSA-004)

The lead team is still waiting on manuscript proofs from AMPPS.

Stereotype Threat Study (PSA-005)

Data collection is complete and we are analyzing the data for the final submission. We are also working on a resubmission of a commentary on the challenges and payoffs of big team science.

Semantic Priming Study (PSA-007)

The manuscript is under review at Nature Human Behaviour!

Minimal Groups Study (PSA-008)

The project has reached more countries and languages as new sites start and complete their data collection. Please see the preprint or email psa...@googlegroups.com for more information.


PSA-JTF-001: Moral Experiences

Data collection has started at more sites and in more countries! For more information about the project, please see the preprint or email psa...@gmail.com.

PSA-JTF-002: Dignity Honor Face

Data collection in English and the translation process will start soon! Interested in potentially joining us? Email psa...@gmail.com.

PSA-JTF-003: Error Correction

The manuscript is under review as a Stage 1 Registered Report at Nature Human Behaviour. We are making preparations to start data collection. The project still welcomes collaborators who can collect data. Interested? Fill out this survey!

If you need a PSA account or a guide on how to use Canvas, 

please visit https://member.psysciacc.org/.