---
title: "Reminder: Director Nominations due Feb 15"
author: "The Psychological Science Accelerator"
date: 2024-02-07
categories:
  - mailchimp backup
---

Reminder: PSA director nominations due February 15
The Psychological Science Accelerator (https://psysciacc.org/) (PSA) will soon have an election for a major leadership position: Director!

The Director works with the Associate Directors as a steering body for the PSA. Together they make decisions as well as function as liaisons between the various committees. As described in Moshontz et al. (2018), the Director additionally “oversees day-to-day operations and evaluates the functioning and policies of the PSA with respect to the core principles” of diversity and inclusion, decentralized authority, transparency, rigor, and openness to criticism (p. 505).

Any member of the PSA is eligible to run for this position, which is elected by the PSA community to serve a 3-5 year term. If you’d like to nominate yourself or someone else, please fill out this form (https://forms.gle/D55151yyxzoDsr2XA) on or before Monday, February 15, 2024.

Although Director has historically been a volunteer role, candidates can optionally propose in their candidacy statement to use PSA funds (https://opencollective.com/psysciacc) to support the role. This could be in the form of course buyout, summer funding, postgraduate supplemental stipend etc. and would be subject to approval from the Associate Directors. If you have any questions about the position, feel free to email Miguel Silan (mailto:miguelsilan@gmail.com) (Associate Director overseeing the election) and/or Nicholas Coles (mailto:ncoles@stanford.edu) (outgoing Director).

Stay tuned for an end-of-term reflection from outgoing Director, Nicholas Coles, who says:

“Directing the PSA has been the most interesting, important, and exciting role I’ve taken on in my career thus far. I am extremely proud of what the PSA has achieved, and I’m beyond excited to see what the network accomplishes over the next few years. My term as Director may be coming to an end, but I will be continuing to dedicate a substantial portion of my energies to building up big team science!"
