---
title: "2024 Call for Studies"
author: "Savannah Lewis"
date: 2024-07-18
categories:
  - newsletter
---

## PSA Call for Studies- 2024

The Psychological Science Accelerator (PSA), welcomes study proposals for new PSA studies! Two rounds of proposal review will occur in Fall 2024. We will also host workshops and incubation for those who wish to submit and want guidance and help preparing their proposal  Please see the official call announcement for details about proposal requirements and the project selection process and timeline. For general inquiries, email psysciaccelerator@gmail.com (mailto:psysciaccelerator@gmail.com) with the subject as Call for Studies Questions. If you need a PSA account or instructions on how to complete tasks on Canvas, check [here](https://member.psysciacc.org/).

[Link to Call for Studies](https://docs.google.com/document/d/1WVXRZD117YWXEDiYONvfzFZgICKG3bYQhQHG7MqHE_g/edit?usp=sharing)


## Study Selection is also looking for reviewers and committee members!

The Study Selection Committee is looking for reviewers and new committee members to aid in selecting projects for the PSA's most recent call for studies. If you are interested, more information can be found [here](https://forms.gle/iddN61stQc7S2PE79). Please submit before September 10, 2024.

Upcoming changes to PSA News: We use MailChimp to send newsletters and PSA wide announcements. Unfortunately, MailChimp has become very expensive. We will be moving to a Google Group for PSA newsletters and announcements. You will receive an email indicating you were enrolled in a Google Group. You can remove yourself or mute notifications.
