---
title: "News from the Accelerator- January 2024"
author: "The Psychological Science Accelerator"
date: 2024-01-15
categories:
  - mailchimp backup
---

quick read

- A new PSA project, JTF-002: Dignity Honor Face, is looking for collaborators! Read below for more information.

- The PSA Moral Experiences study (PSA-JTF-001) seeks collaborators in select countries!


project updates


PSA-JTF-002: Dignity Honor Face (https://psysciacc.org/news/2022-12-06_second-special-call-for-studies-studying-generalizability-with-global-samples.html)

The cultural logics of dignity, honor, and face (DHF) describe different grounds for evaluating a person’s worth and ensuring cooperation that vary in prevalence across cultures. This is the first comprehensive study of DHF cultural logics worldwide. We will clarify the conceptualization and validating measurement of DHF logics across cultures, map world cultures on the prevalence of DHF logics, and identify both country-level and individual level correlates and behavioral manifestations of these cultural logics.

Interested in learning more and potentially joining the project? Fill out this survey! (https://docs.google.com/forms/d/e/1FAIpQLSfifQfg-HQdZ-AIoSACu2yeI5bR_DA6nqexmjI0S8GdRaaVWA/viewform)


Object Orientation Study (PSA-002) (https://psysciacc.org/projects/psa002.html)

The lead team received reviews from PBR and unfortunately the manuscript was rejected. The full reviews are available on the Slack channel. The lead team is working on addressing issues raised by the reviewers and repackaging the paper for another journal.


Gendered Prejudice Study (PSA-003) (https://psysciacc.org/projects/psa003.html)

The manuscript is under review at Psychological Science.


Justified True Belief Study (PSA-004) (https://psysciacc.org/projects/psa004.html)

The manuscript will be resubmitted to Advances in Methods and Practices in Psychological Science within the next few weeks.


Stereotype Threat (PSA-005) (https://psysciacc.org/projects/psa005.html)

Data collection will continue for another semester so that the thresholds of evidence described in the pre-registration can be reached.


Semantic Priming Study (PSA-007) (https://psysciacc.org/projects/psa007.html)

Three more languages (Portuguese, Simplified Chinese, and Greek) have reached data collection requirements, and 15 languages are complete! In total, data has been collected from 29,000 participants in 30 languages! Data collected by the end of the month will be used in the analysis for the NHB manuscript. Data collection beyond this point (especially for languages that did not meet the minimum) will be published in subsequent papers. In February, we will begin the final stages of the project.


Minimal Groups Study (PSA-008) (https://psysciacc.org/projects/psa008.html)

The lead team is still waiting to hear back on the Registered Report at Nature Human Behaviour. Translation of the study materials continues as the lead team makes final preparations to start data collection. Collaborators should look for a lab guide and Canvas survey being sent soon.


PSA-JTF-001: Moral Experiences (https://psysciacc.org/news/2022-12-06_second-special-call-for-studies-studying-generalizability-with-global-samples.html)

The lead team is on the verge of preregistering the study and posting a stage-1 style preprint by the end of the week! The ethics and translation processes have begun, and data collection is set to begin in at least some labs very soon. This project is still welcoming interested collaborators who can collect data in Argentina, Colombia, France, Greece, Indonesia, Japan, Kenya, Malaysia, Morocco, Pakistan, or Saudi Arabia; please email the project leads (mailto:psajtf1@gmail.com) for more information about joining the project.


PSA-AF-001: Partner Preferences (https://psysciacc.org/affiliated/af001.html)

Data collection for this project is now complete (n > 20,000 from 40 + countries)! The lead team is now working through the analyses and will then turn their attention to the Stage 2 report at the Journal of Personality and Social Psychology!


big team science

Psychology should generalize from — not just to — Africa. Nature Reviews Psychology (https://www.nature.com/articles/s44159-022-00070-y)

How to build up big team science: a practical guide for large-scale collaborations. Royal Society Open Science. (https://royalsocietypublishing.org/doi/10.1098/rsos.230235)

‘Big team’ science challenges us to reconsider authorship. Nature Human Behaviour (https://www.nature.com/articles/s41562-023-01572-2)

The benefits, barriers, and risk of big team science. Perspective on Psychological Science (https://psyarxiv.com/2mdxh)

Build up big team science. Nature (https://www.nature.com/articles/d41586-022-00150-2)

High replicability of newly discovered social-behavioural findings is achievable. Nature (https://www.nature.com/articles/s41562-023-01749-9)

The Psychological Science Accelerator: Advancing psychology through a distributed collaborative network. AMPPS (https://journals.sagepub.com/doi/full/10.1177/2515245918797607)

Psychological Science Accelerator: A promising resource for clinical psychological science. Avoiding Questionable Research Practices in Applied Psychology (https://link.springer.com/chapter/10.1007/978-3-031-04968-2_19)



completed studies
To which world regions does the valence–dominance model of social perception apply? Nature Human Behaviour (https://www.nature.com/articles/s41562-020-01007-2)

Situational factors shape moral judgements in the trolley dilemma in Eastern, Southern and Western countries in a culturally diverse sample. Nature Human Behaviour (https://www.nature.com/articles/s41562-022-01319-5)

A multi-country test of brief reappraisal interventions on emotions during the COVID-19 pandemic. Nature Human Behaviour (https://www.nature.com/articles/s41562-021-01173-x)

A global experiment on motivating social distancing during the COVID-19 pandemic. PNAS (https://www.pnas.org/doi/full/10.1073/pnas.2111091119)

In COVID-19 health messaging, loss framing increases anxiety with little-to-no concomitant benefits: Experimental evidence from 84 countries. Affective Science (https://link.springer.com/article/10.1007/s42761-022-00128-3)

The Psychological Science Accelerator’s COVID-19 rapid-response dataset. Nature Scientific Data (https://www.nature.com/articles/s41597-022-01811-7)
