---
title: "PSA Announcement"
author: "Savannah Lewis"
date: 2025-12-01
categories:
  - elections
---

Accelerators,  

We are excited to share several important updates about PSA leadership roles and recent elections.

Assistant Directorship Appointments
The PSA Directorial Board reviewed this cycle’s applications for Assistant Directorships and unanimously voted to approve the nominations. Please join us in congratulating our newest Assistant Directors:

    Project Monitoring: Melinna Mei 
    Translation and Cultural Diversity: Michele Habbaki 
    Community Building and Network Expansion: Ambre Naija and Anthony Ebuka 

These individuals will help guide their respective committees, shape committee vision plans, support day-to-day operations, and provide regular updates to PSA leadership.

Associate Director Election Results
We are also thrilled to announce the conclusion of our Associate Director election.
Congratulations to David Vaidis, who has been elected as our newest Associate Director! He will officially begin his term December 1st.

We extend our sincere gratitude to all candidates. It is never easy when we have more exceptional applicants than positions available. Your dedication, thoughtful statements, and willingness to serve are truly appreciated.

We feel incredibly fortunate to work alongside such a dedicated and talented international community. Thank you all for your ongoing engagement, enthusiasm, and commitment to the mission of the PSA.

We are excited for the year ahead and look forward to all that we will accomplish together!

If you want a quick reminder of the current PSA leadership and roles descriptions, you can check out this policy: https://docs.google.com/document/d/1aXjXwouFc6wvcyy7IFmEKGL0j2yxzYukyI_YFf6sZtM/edit?tab=t.0

