---
title: "September News from the Accelerator"
author: "Savannah Lewis"
date: 2025-09-06
categories:
  - newsletter
---

----------
Quick read
----------

* SIPS Award: received by PSA-team paper “A manifesto for globally diverse, equitable, and inclusive open science” in Communications Psychology.
* Festival Follow-Up (Oct 13, 2025, 10:00 CET / 08:00 UTC): Open to researchers, students, and support staff. Session 1 covers Open Science without burnout; Session 2 offers community discussions on collaborative research culture. Free.
* External Collaboration Call: Funded multi-site study Building Resilience Across Socioeconomic Contexts seeks sites to recruit 40–60 English-fluent participants. Sites handle ethics approval; central team manages logistics. Co-authorship and IRB support provided.

*PSA Member Highlights*

Several fellow PSA members received a SIPS award for their paper “A manifesto for globally diverse, equitable, and inclusive open science” in Communications Psychology. Check out the paper here ( https://www.nature.com/articles/s44271-024-00179-1 ) or read the list of awards on the SIPS website ( https://improvingpsych.org/mission/awards/ ).

Our fellow PSA member Patrick Forscher is giving a talk ** on “Tracking Epistemic Inequality: The Missing Majority Dashboard for Global Authorship in Behavioral Science” at the NYU Meta-Research Symposium 2025, Oct 20. Tickets and details available on Eventbrite ( https://www.eventbrite.com/e/meta-research-symposium-2025-tickets-1608088037609 ).

We also have several PSA members who are presenting at the MIT Workshop on Polarization, Social Norms & Trust, Dec 5–6, Boston. For details and to sign up, click here ( https://sites.google.com/view/polarization-workshop/2025-workshop ). If you see a fellow Accelerator, be sure to say hello!

*PSA Highlighted Opportunities*
-------------------------------

Festival Follow-Up (Oct 13, 2025, 10:00 CET / 08:00 UTC)
--------------------------------------------------------

Join several PSA members online for our *Festival Follow-Up* for reflection, practical skills, and community conversation. This session is for everyone: researchers, students, and support staff alike!

* *Session 1*. *Open Science Without Burnout* : Building Healthier Research Culture. Join burnout coach and data steward, *Özgün Ünver* , to explore how to engage with openness and transparency without overextending yourself. We’ll discuss setting boundaries, fostering sustainable practices, and building a healthier research culture for everyone. You'll leave with practical insights and a reminder that Open Science can be both impactful and sustainable.
* *Session 2*. *Community Conversations* : Exchanging fresh perspectives and engaging in open discussion on how we can build a more connected, collaborative research culture— together.

Participation is free, registration ( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeVzJR7SPJzlVsNZKbBift0TX4GjNl-2Fji70qKp1RTQaHHxT1Mk5beduBk-2BGquPaRVpPAmusEJjmy2uR2drJGMYyMg-3DQFFc_SNv0RkS-2BTKJPVFDyMUK2BbWwGCi7bVKXk4c4cXwniRT6ljrbKX06gnkMNxSWrnKI8tUCFNM7LAX6oPnRf2Te4PjCWCL5lmQoQtdShn0zspQrF5-2Bf-2FTnCgYiuvDgRHRm4W0Yo04YkFZLKlII29NqY40cHbWuGhic-2FHrJuoAJtg0XaKXmYMK-2FcE9Mw9F7FWd6VOlkCp2u8vIrXrMPQ5pCcQxvfCv4Tp23CCeZ8QA-2FMJ5DdPqkuY9L3itsOPgIF4jLcpcyfPu9MxEQZm-2FGhtE56X8oIfbb5PG9sKxRFkLn1C0GdeiVhCuUKURC0Sr-2BCbQdGDSZdWc0Y9xVdW6OOM3al40c6-2FkP1vtdkmPrky2otEfpE1S7m6lVsUDuI5Ifkp-2FZRPgYNczGfuUFlKsgYqjV3GPVTbKPByYMrKulZxVtu1uo-2FYI766-2B-2Fj5IWcDVO4dBIiXvwt554ICXOHH4l2-2FAebcxoy73jCdgieqIxWad31USO24dt-2BaGnfes-2BFZNrjyNUuosyv6ciWmL2xwDPi-2BNcL9lQXzI5qQ-2F9SfQv4eX-2B-2BMLFj-2FTlBWH7aPCFLIQnaYmeaXoyU2FsUj9tpnvvoYNmGhZF0D6DcjqQGdhyjHoOcxk2RkHdS0UHFz90S2DAy-2BVES0M47PqJs2OH4VNSR2gUQv9CktcNX5I9GYJi8-2BMCg6RosHZw9ve0qJD0QCS-2FTmyF7 ) is required, and all are welcome!

BTS Study Seeking Collaborators

Alessandro Sparacio is seeking international collaborators for a funded, multi-site study on the effectiveness of self-administered mindfulness meditation for stress reduction that you might be interested in joining.

What's involved?

* Site requirements: local ethics approval, recruit 40–60 English-fluent participants; preference for predominantly English-speaking countries.
* Benefits: co-authorship, IRB support, central logistics, no site costs.

If you're passionate about contributing to high-impact, equitable science, they would love to hear from you. Find all the details and the collaborator interest form here ( http://url4342.psysciacc.org/ls/click?upn=u001.jVIDZ82VDQjJkpS3fDCeV9VatV4dDapEXlyF99o6C3z6tx6ryvT3rNrpbmmCDxeqlJdW_SNv0RkS-2BTKJPVFDyMUK2BbWwGCi7bVKXk4c4cXwniRT6ljrbKX06gnkMNxSWrnKI8tUCFNM7LAX6oPnRf2Te4PjCWCL5lmQoQtdShn0zspQrF5-2Bf-2FTnCgYiuvDgRHRm4W0Yo04YkFZLKlII29NqY40cHbWuGhic-2FHrJuoAJtg0XaKXmYMK-2FcE9Mw9F7FWd6VOlkCp2u8vIrXrMPQ5pCcQxvfCv4Tp23CCeZ8QA-2FMJ5DdPqkuY9L3itsOPgIF4jLcpcyfPu9MxEQZm-2FGhtE56X8oIfbb5PG9sKxRFkLn1C0GdeiVhCuUKURC0Sr-2BCbQdGDSZdWc0Y9xVdW6OOM3al40c6-2FkP1vtdkmPrky2otEfpE1S7m6lVsUDuI5Ifkp-2FZRPgYNczGfuUFlKsgYqjV3GPVTbKPByYMrKulZxVtu1uo-2FYI766-2B-2Fj5IWcDVO4dBIiXvwt554ICXOHH4l2-2FAebcxoy73jCdgieqIxWad31USO24dt-2BaGnfes-2BFZNrjyNUuosyv6ciWmL2xwDPi-2BNcL9sUG96kbW1yML82oLKSeIu7vz-2BSxrSO9xZCYQW4dF3ykVroxkNCfTopS1BkOcJJcNfAsOrpbaVbO2-2Ff6XAT-2BTUo1saRnHw46L38gwEpzlqLjLot1ZMCTh908Q1uIgGtzD6Wsixp3ushMtX09-2BC0i-2FeuzmFJn0s0T0LPCyJxZTsTB ).

*PSA PROJECT UPDATES*

*002 Object Orientation*

PSA 002 has been accepted for publication in Current Psychology. The lead team is satisfied to see this project come to fruition after so many twists and turns along the path. Thanks to all who contributed to this project and congratulations!
Read more in our preprint >> ( https://osf.io/preprints/osf/2qf6w_v1 )

*003 Gendered Prejudice*

The manuscript has officially been published PLOS ONE. ( https://doi.org/10.1371/journal.pone.0323938 )
Read more in our preprint >> ( https://osf.io/preprints/psyarxiv/nkbjc_v1 )

*005 Stereotype Threat*

The PSA 005 admin team is working on the final paper write-up. The team has also received a revise and resubmit from Social and Personality Psychology Compass on the challenges and payoffs of in-person big team science.
Read more in our preprint >> ( https://osf.io/preprints/psyarxiv/6hju9_v1 )

*007 Semantic Priming*

The manuscript has officially been accepted for print at Nature Human Behaviour. The lead team has submitted approval for the final publication proof.
Read more in our preprint >> ( https://osf.io/preprints/osf/q4fjy_v3 )

*008 Minimal Groups*

Data collection continues until October. So far, this collaboration has gathered data from over 18000 participants across 38 countries.
Read more in our preprint >> ( https://osf.io/preprints/psyarxiv/5gpr4_v1 )

*009 Gendered Leadership*

The project has completed 38 countries (N>20,000, after cleaning) and is chasing the final 6 countries for the end of September. They are aiming to have the draft paper written by the end of October for circulating around the group.
Read more in our Registered Report >> ( https://docs.google.com/document/d/1eRZmprM3_fyOE8DgPSN0EQaMMOQdYkoP/edit?usp=sharing&ouid=114736564429721617256&rtpof=true&sd=true )

JTF1 Moral Experiences

The lead team is wrapping up data coding and validation and will soon have a draft of the manuscript to share with collaborators.
Read more in our preprint >> ( https://osf.io/preprints/psyarxiv/jktnv_v2 )

JTF2 Dignity Honor Face

Data collection is wrapping up for the project; the final deadline is the end of July. This project has now collected data from over 31,000 participants from over 60 countries!
Read more in our preprint >> ( https://osf.io/preprints/psyarxiv/9hb8k_v1 )

JTF3 Error Correction

The lead team have collected data from over 10,000 participants across 35 countries thus far! Almost all translations are complete (with only 2 languages remaining), so all teams can dive into data collection quite soon, if not already.
Read more in our preprint >> ( https://osf.io/wn4vx/ )