---
title: "June 2025 Newsletter from the Accelerator"
author: "Savannah Lewis"
date: 2025-06-06
categories:
  - newsletter
---
PSA Newsletter June 2025

## *Quick read*

-   Four new projects to enter the next phase in the PSA study pipeline!

-   The Directors announce the winners of the Gorilla & PSA Grant Initiative!

-   Two PSA projects have been officially accepted for publication! Great work to all collaborators of the Semantic Priming (PSA 007) and Gendered Prejudice (PSA 003) projects!

## New PSA Studies in Progress!!

We’re excited to announce that the following studies are now entering the next phase in the PSA’s study pipeline:

-   [Global Crises](https://docs.google.com/document/d/1J5gp5s7xiDj6uLGch4E4n3Mqyi-voPmy/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

-   [Emotion Differentiation](https://docs.google.com/document/d/1XfVPxElTtVSmB3i3AVaPMeZmlJtJ8y4s/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

-   [AWE](https://docs.google.com/document/d/1kjcZB23CSLv83juGdiXQnES6BvJloxlQ/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

-   [Social Evaluation](https://docs.google.com/document/d/1LXkRYa8AkcMA-D396oWn3lvZdJUMoimf/edit?usp=drive_link&ouid=103542693559626876995&rtpof=true&sd=true)

Now the proposing authors have **six months** to complete their revisions and submit the study for final approval. They will then enter into a collaborative planning process with the directors to identifies the logistical, methodological, and recruitment needs of their study needs from our network before starting recruitment. This process is called the PSA Needs Assessment phase and ensures that each project is ready to succeed as a global collaboration by matching them with the right resources and support.

Stay tuned for updates on these exciting new studies! 🚀

### Join the PSA’s Community Building & Network Expansion Committee!

Are you interested in helping grow a global, collaborative scientific community? The Psychological Science Accelerator (PSA) is looking for new members to join our Community Building and Network Expansion Committee!

This committee focuses on strengthening connections within the PSA and expanding our network around the world. Whether you’re excited about outreach, welcoming new members, organizing events, or building partnerships, this is a great opportunity to get involved. No prior committee experience required, just enthusiasm and a willingness to help. To express interest, simply [email Nadia Sarai Corral Frías](nadia.corral@unison.mx) (Assistant Director).

Help us build bridges and expand the reach of psychological science!

### Announcing the Winners of the Gorilla & PSA Grant Initiative

The PSA directors are thrilled to announce the recipients of the **Gorilla x PSA Grant Initiative**! These five outstanding researchers impressed our panel with their innovative research ideas and dedication to advancing behavioral science.

🎉 Congratulations to:

-   Brendan Schuetze

-   Sophie Gerdel

-   Piotr

-   Ilaria Colpizzi

-   Adrianne J. R. Galang

The PSA is incredibly proud to support their work and can’t wait to see the exciting studies they create using Gorilla’s powerful experiment builder.

Thank you to everyone who applied, Erin and Savannah really enjoyed reading the cool work happening in our network, and look forward to supporting even more researchers in the future.

## PSA PROJECT UPDATES

### *002 Object Orientation*

The lead team has resubmitted the manuscript after making some revisions to *Current Psychology*.

[Read more in our preprint](https://osf.io/preprints/osf/2qf6w_v1)

### *003 Gendered Prejudice*

The manuscript has officially been accepted for print at *PLOS ONE*! Congratulations to all for your continued patience and perseverance in the past 7 years! Be on the lookout for the final version soon.

[Read more in our preprint](https://osf.io/preprints/psyarxiv/nkbjc_v1)

### *005 Stereotype Threat*

The PSA 005 lead team has finished final analyses and robustness checks. All authors should also now be listed on the preprint on PsyArXiv.

[Read more in our preprint](https://osf.io/preprints/psyarxiv/6hju9_v1)

### *007 Semantic Priming*

The manuscript has officially been accepted for print at *Nature Human Behaviour!* Congratulations to all and thank you for the putting in the time and effort to get this project across the finish line! Be on the lookout for the final version soon.

[Read more in our preprint](https://osf.io/preprints/osf/q4fjy_v3)

### *008 Minimal Groups*

Data collection continues! We have gathered data from over 16500 participants across 37 countries, 25 of which have met the within country sample size goal of 200.

[Read more in our preprint](https://osf.io/preprints/psyarxiv/5gpr4_v1)

### *009 Gendered Leadership*

The project has been developing smoothly. Data have been collected in 20 countries (15 languages). At the moment, we collected data from over 30000 participants. We are working towards 26 countries (31 languages).

[Read more in our preprint](https://osf.io/preprints/psyarxiv/xjkcv_v1)

### *JTF1 Moral Experiences*

Primary data collection is complete! Data coding is nearly done, secondary data collection is progressing quickly, and the manuscript update is coming along nicely.

[Read more in our preprint](https://doi.org/10.31234/osf.io/jktnv_v1)

### *JTF2 Dignity Honor Face*

JTF2 has now collected data from over 22000 participants! Thanks to everyone for their collaboration thus far.

[Read more in our preprint](http://doi.org/10.31234/osf.io/9hb8k)

### *JTF3 Error Correction*

Early data collection is going well, with over 3,600 participants across 15 countries thus far! Great effort to those who have collaborated so far.

[Read more in our preprint](https://osf.io/preprints/psyarxiv/wegc5_v1)

## *Get involved in the PSA*

Join us on [*Slack*](https://join.slack.com/t/psych-sci-accelerator/shared_invite/zt-2xanhh3n8-1IPQMNi6BEvRbOEgCTvDUw), or drop by our Directors' Office Hours (Mondays at 2pm UTC, [*Zoom link*](https://ua-edu.zoom.us/my/slewis20).
