---
title: "2026-April: News from the Accelerator"
author: "Sara Eftekhari"
date: 2026-04-06
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: right
categories:
  - Newsletter
  - PSA005 Stereotype Threat
  - PSA008 Minimal Groups
  - PSA009 Gendered Leader
  - PSA010 Social Evaluation
  - PSA011 Emotion Differentiation
  - PSA012 Aesthetic Well-being Evaluation
  - PSA013 Global Crises
  - PSA-JTF1 Moral Experiences
  - PSA-JTF2 Dignity Honor Face
  - PSA-JTF3 Error Correction
---

## Quick read

- **PSA Newsletter Translations:** Coming soon!
- **Publication Call:** CDEMP seeks submissions on open science in multicultural research. [Submit letter of Intent](https://docs.google.com/document/d/10nMV34zgRtxmNp8FDcI4S2Q4tvJFePi-REklH0pxzkY/edit?tab=t.0) by **15 May 2026**.
- **Rater Vacancy:** Seeking 21 preregistration‑knowledgeable researchers to help validate an AI preregistration review tool. [Apply](https://goldpsych.eu.qualtrics.com/jfe/form/SV_39mTrl3rixswp2m).

## Translations of PSA Newsletter

Translations of the PSA Newsletter will be available soon.
**Watch this space** in upcoming newsletters!

## Opportunities for PSA Members

### Publication Opportunity

*Cultural Diversity & Ethnic Minority Psychology* (CDEMP) invites submissions for a special section on “**Transparency, Credibility, and Accountability in Context: Open Science as Psychological Inquiry in Ethnic Minority and Multicultural Psychology Research**". Letters of Intent are due **15 May 2026**. [See full details](https://docs.google.com/document/d/10nMV34zgRtxmNp8FDcI4S2Q4tvJFePi-REklH0pxzkY/edit?tab=t.0).

### Vacancy: Raters for Tool Validation

**21 knowledgeable preregistration researchers** sought to help validate an AI tool for assessing preregistrations.
Raters will evaluate preregistrations using a rubric, then meet with two other raters to discuss and optionally adjust their ratings (similar to the IDEA protocol from RepliCATS).

- The full task involves **12–14 preregistrations** and takes **\~18–36 hours**, to be completed within **6 weeks** (by **end of May**).
- Participants will receive **£330** (**\~412€** , **\~\$485**) for 12 preregistrations (double that for 22) and have the opportunity to **join the authorship team**.

[See full details](https://goldpsych.eu.qualtrics.com/jfe/form/SV_39mTrl3rixswp2m).

## PSA Project Updates

### 005 Stereotype Threat

The team is finishing up the final draft of the manuscript to circulate to co-authors by 10 April.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/6hju9_v1)

### 008 Minimal Groups

Data collection has ended, and analysis has begun.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/5gpr4_v1)

### 009 Gendered Leadership

The Stage 2 Registered Report is under review at *The Leadership Quarterly*.

[Read more in our registered report \>\>](https://docs.google.com/document/d/1eRZmprM3_fyOE8DgPSN0EQaMMOQdYkoP/edit?usp=sharing&ouid=114736564429721617256&rtpof=true&sd=truehttps://docs.google.com/document/d/1eRZmprM3_fyOE8DgPSN0EQaMMOQdYkoP/edit?usp=sharing&ouid=114736564429721617256&rtpof=true&sd=true)

### 010 Social Evaluation

The lead team has received positive comments from *Psychological Science* on their Stage 1 Registered Report and are awaiting reviews.

[Read more in our proposal \>\>](https://docs.google.com/document/d/1zo_MwwsDVIKh4m6UlaI0XgPN4hS07Abf)

### 011 Emotion Differentiation (NEW PROJECT!)

PSA 011 addresses the lack of cross‑cultural research by recruiting participants from over 20 countries using the PSA network to examine associations between emotion differentiation, emotion regulation, and internalising symptoms (depression and anxiety), to test whether these associations differ across countries using a multimethod approach, and to offer insights for developing mental health interventions that are sensitive to regional differences.

PSA 011 has received its acceptance letter.
The team are drafting registered reports.
PSA 011 is **not ready for collaboration inquiries yet, but stay tuned!**

[Read more in our proposal \>\>](https://docs.google.com/document/d/1YybzqaASMx5wQVcf9Y7Ewi7Hjw4cIJmz/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

### 012 Aesthetic Well-being Evaluation (NEW PROJECT!)

PSA 012 tests whether greater art involvement is associated with higher well‑being, whether this relationship is moderated by cultural context, and whether different modes of engagement (creating vs. observing; in‑person vs. digital) differentially impact well‑being, using a large‑scale study assessing diverse forms of art engagement and PERMA well‑being outcomes to clarify how art contributes to well‑being.

PSA 012 has received its acceptance letter.
The team are drafting registered reports.
PSA 012 is **not ready for collaboration inquiries yet, but stay tuned!**

[Read more in our proposal \>\>](https://docs.google.com/document/d/1KNtN1sl0FuDsdHZI8t2rRcfq2yeORSit/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=truehttps://docs.google.com/document/d/1KNtN1sl0FuDsdHZI8t2rRcfq2yeORSit/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

### 013 Global Crises (NEW PROJECT!)

PSA 013 investigates how people perceive global crises (e.g. climate change, pandemics, war and violence) and how these perceptions relate to motivation to act across cultural contexts, by examining perceived importance (Want) and efficacy beliefs (Expectancy) within Motivational Readiness Theory by recruiting participants from over 60 countries, with the goal of mapping perception–reality gaps, testing cross‑cultural differences, and informing culturally tailored policy strategies to enhance public engagement.

PSA 013 has received its acceptance letter.
The team are drafting registered reports.
PSA 013 is **not ready for collaboration inquiries yet, but stay tuned!**

[Read more in our proposal \>\>](https://docs.google.com/document/d/1t63IiQpDhDEMnz3VOaxT6-i-rMuzSNGg/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=truehttps://docs.google.com/document/d/1t63IiQpDhDEMnz3VOaxT6-i-rMuzSNGg/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

### JTF1 Moral Experiences

Collaborators can anticipate seeing a manuscript in April.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/jktnv_v2)

### JTF2 Dignity Honor Face

The team has been working hard on data cleaning and analysis, and will soon move onto refining the writing.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/9hb8k_v1)

### JTF3 Error Correction

Data collection continues until approximately April.

[Read more in our preprint \>\>](https://osf.io/wn4vx/)
