---
title: "2026-September: News from the Accelerator"
author: "Sara Eftekhari"
date: 2026-09-06
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: right
categories:
  - Newsletter
  - Elections
  - PSA005 Stereotype Threat
  - PSA008 Minimal Groups
  - PSA009 Gendered Leader
  - PSA010 Social Evaluation
  - PSA011 Emotion Differentiation
  - PSA012 Aesthetic Well-being Evaluation
  - PSA013 Global Crises
  - PSA-JTF1 Moral Experiences
  - PSA-JTF2 Dignity Honor Face
  - PSA-JTF3 Error Correction
---

## Quick read

- **PSA Highlights:** [Apply](https://docs.google.com/document/d/1DKEyNSKwVeDp0hPEVgofeEnUF98Hu4fzUbOjRzbvbyo/edit?usp=sharing) for an Associate Director position in the PSA by **15 September**; join the Translation & Cultural Diversity Committee.
- **Opportunities for PSA Members:** [Register](https://bigteamscienceconference.github.io/) for the virtual BTS Con happening **6–8 October** live on Zoom; [collaborate with REFORM](https://psy-sci-accelerator.slack.com/archives/C7D9CRWCC/p1787046697561389) in recruiting English-speaking low-SES participants for a mindfulness RCT.
- **PSA Project Updates:** [Express interest](https://globalcrisesproject.net/collaborate/) in collaborating with PSA013 Global Crises by **31 October**.

View [translations of this month’s newsletter](https://docs.google.com/document/d/1InZdbZY7W8c1UUWWp22xRyQfKcwfRtd5afMVqr7zqlU/edit?tab=t.0).

## PSA Highlights

### Election Call for 2026

[Apply](https://docs.google.com/document/d/1DKEyNSKwVeDp0hPEVgofeEnUF98Hu4fzUbOjRzbvbyo/edit?usp=sharing) by **15 September** to be an Associate Director in the PSA.

### TCDC Seeking New Members

The Translation & Cultural Diversity Committee (TCDC) are seeking new members.
Join and help coordinate translations of new upcoming projects and monthly meetings with TCDC.

Contact David Vaidis (david.vaidis\@univ-tlse2.fr) and Julija Kos (julijaakos\@gmail.com) for more information.

## Opportunities for PSA Members

### Big Team Science Conference

[Register](https://bigteamscienceconference.github.io/) for the virtual Big Team Science Conference (BTS Con), happening **6–8 October** live on Zoom.

Join a multidisciplinary group of researchers, funders, and stakeholders to discuss advancements, challenges, and future opportunities related to big team science.
Attend featured presentations by leaders of the Center for Open Science’s SCORE (Systematizing Confidence in Open Research and Evidence) initiative, CREP (the Collaborative Replication and Education Project), a live recording of the “Research as it Happens” podcast, and more.

### Collaborators Sought: REFORM

REFORM is seeking collaborators from sites with access to English-speaking participants of low socioeconomic status (SES) background (target is ≥33% low-SES participants).
REFORM is a four-arm Bayesian Randomized Controlled Trial (RCT) testing whether formally delivered versus informally embedded mindfulness practice works differently across socioeconomic contexts.

The study is fully remote, with the Agency for Science Technology and Research (A\*STAR) centrally managing Qualtrics infrastructure, study materials, data coordination, participant monitoring, and reimbursement.
Participating sites primarily handle ethics, recruitment/pre-screening, and light participant follow-up during the one-month study.

For more information contact **Alessandro Sparacio** at Alessandro_Sparacio\@a-star.edu.sg.

[See full details](https://psy-sci-accelerator.slack.com/archives/C7D9CRWCC/p1787046697561389).

## PSA Project Updates

### 005 Stereotype Threat

The team was finishing up the final draft of the manuscript to circulate to collaborators soon.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/6hju9_v1)

### 008 Minimal Groups

The team are currently writing the manuscript.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/5gpr4_v1)

### 009 Gendered Leadership

The team are delighted to announce their manuscript has been accepted for publication in *The Leadership Quarterly*.
Congratulations and thank you to our Accelerators that contributed to this successful project.

[Read more in our registered report \>\>](https://docs.google.com/document/d/1eRZmprM3_fyOE8DgPSN0EQaMMOQdYkoP/edit?usp=sharing&ouid=114736564429721617256&rtpof=true&sd=true)

### 010 Social Evaluation

The team have addressed publisher feedback and have requested fresh sets of eyes from their collaborators on the revised Stage 1 Registered Report.

[Read more in our proposal \>\>](https://drive.google.com/file/d/1K6NCI7h68WXbSBQESDxOBq61jnreODF4/view?usp=sharing)

### 011 Emotion Differentiation

PSA 011 has received its acceptance letter.
The team are drafting registered reports.
PSA 011 is **not ready for collaboration enquiries yet, but stay tuned!**

[Read more in our proposal \>\>](https://docs.google.com/document/d/1YybzqaASMx5wQVcf9Y7Ewi7Hjw4cIJmz/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

### 012 Aesthetic Well-being Evaluation

PSA 012 has received its acceptance letter.
The team are drafting registered reports.
PSA 012 is **not ready for collaboration enquiries yet, but stay tuned!**

[Read more in our proposal \>\>](https://docs.google.com/document/d/1KNtN1sl0FuDsdHZI8t2rRcfq2yeORSit/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

### 013 Global Crises

The team want to submit a Registered Report with *Nature Human Behaviour* for the main study.
They will shortly start drafting the Stage 1 Registered Report, and will soon announce a defined timeline for submission.
The aim being to submit by the end of 2026, start of 2027.

PSA 013 is **now open for collaboration enquiries**!
[See full details and express your interest](https://globalcrisesproject.net/collaborate/) in collaborating by **31 October**.

[Read more in our proposal \>\>](https://docs.google.com/document/d/1t63IiQpDhDEMnz3VOaxT6-i-rMuzSNGg/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

### JTF1 Moral Experiences

The team have produced a manuscript.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/jktnv_v2)

### JTF2 Dignity Honor Face

Final edits are being made to the manuscript before it is sent to collaborators for review.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/9hb8k_v1)

### JTF3 Error Correction

The team are running analyses.

[Read more in our preprint \>\>](https://osf.io/wn4vx/)

## PSA Newsletter Translations

View [translations of this month’s newsletter](https://docs.google.com/document/d/1InZdbZY7W8c1UUWWp22xRyQfKcwfRtd5afMVqr7zqlU/edit?usp=sharing), provided by the Translation & Cultural Diversity Committee (TCDC).
Stay tuned, as the TCDC is working on publishing the translations on the website in the near future for easier access.

## Thank you for reading!

Can you think of ways to improve the newsletter to be more accessible, useful, and relevant?
Fill this anonymous 2–3 minute [survey](https://formr.thedoomlab.online/PSA-newsletter-feedback-survey) to share your feedback.

The responses to this survey will be reviewed regularly on an ongoing basis.
If you have immediate or urgent feedback, please directly [contact me via Slack](https://psy-sci-accelerator.slack.com/team/U092DUE45GA).

Until next month,

Sara Eftekhari\
PSA Newsletter Coordinator\
Find me on: [Slack](https://psy-sci-accelerator.slack.com/team/U092DUE45GA), [LinkedIn](https://www.linkedin.com/in/sara-eftekhari-787112322/), and [Bluesky](https://bsky.app/profile/sara-eftekhari.bsky.social)

## Get Involved in the PSA

Join us on [Slack](https://join.slack.com/t/psych-sci-accelerator/shared_invite/zt-2xanhh3n8-1IPQMNi6BEvRbOEgCTvDUw), or drop by our Directors’ Office Hours (Friday at 14:00 UTC, [Zoom link](https://ua-edu.zoom.us/my/slewis20)).
