---
title: "2026-October: News from the Accelerator"
author: "Sara Eftekhari"
date: 2026-10-06
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: right
categories:
  - Newsletter
  - PSA005 Stereotype Threat
  - PSA008 Minimal Groups
  - PSA009 Gendered Leader
  - PSA010 Social Evaluation
  - PSA011 Emotion Differentiation
  - PSA012 Aesthetic Well-being Evaluation
  - PSA013 Global Crises
  - PSA-JTF1 Moral Experiences
  - PSA-JTF2 Dignity Honor Face
  - PSA-JTF3 Error Correction
---

## Quick read

- **PSA Highlights:** [Apply](https://psy-sci-accelerator.slack.com/archives/C7D9CRWCC/p1791063159706139) for Project Manager vacancies for PSA010 Social Evaluation and PSA011 Emotion Differentiation by **30 December**. [Apply](https://canvas.psysciacc.org/courses/1/discussion_topics/527) for Research & Organisational Fellow vacancy (\$10,000 CAD, 150–200 hours) by **25 October**. Congratulations to [Biljana Gjoneska](https://psy-sci-accelerator.slack.com/team/U0123QS57HS) for being appointed [Fellow Commissioner](https://www.worldhealthsummit.org/about/whs-academic-alliance/working-group-concepts) for the World Health Summit Academic Alliance-Lancet Commission.
- **Opportunities for PSA Members:** [Register](https://www.theloveconsortium.org/tlc-events) for The Love Consortium Virtual Conference happening **13 October**, featuring global research on love and social connection and an [early-career funding opportunity](https://www.theloveconsortium.org/grants). Participate as a SAS user and author in a many-analysts study on computational reproducibility.
- **PSA Project Updates:** Congratulations to PSA009 for publishing their [paper in the Leadership Quarterly](https://doi.org/10.1016/j.leaqua.2026.101991)! [Express interest](https://globalcrisesproject.net/collaborate/) in collaborating with PSA013 Global Crises by **31 October**.

View [translations of this month’s newsletter](https://docs.google.com/document/d/1InZdbZY7W8c1UUWWp22xRyQfKcwfRtd5afMVqr7zqlU/edit?tab=t.0).

[Submit content](https://docs.google.com/forms/d/e/1FAIpQLScNpHiaa0uilRMDkAHuSzx_Og6XBZy623-swhNhkObJ91qX9Q/viewform) for the PSA newsletter **by the last day of each month**, to be published **by the 6th of the following month**.

## PSA Highlights

### Vacancies: Project Manager (PSA010 and PSA011)

Project Managers sought for PSA010 (Social Evaluation) and PSA011 (Emotion Differentiation).
Learn more about the projects by reading the proposals in the PSA Project Updates section of this newsletter.

Project Managers will help coordinate timelines, teams, and communication across multiple groups, making this a great opportunity to gain leadership and big team science experience.
No prior project management experience is required, and support will be provided.
Expected commitment is approximately 2–4 hours per week, though workload may vary during different stages.

[See full details on Slack](https://psy-sci-accelerator.slack.com/archives/C7D9CRWCC/p1791063159706139).
Applications are open **until 30 December** or **until the positions are filled**, so apply quickly!

Contact John Protzko (Protzko\@gmail.com), Sergio Barbosa De La Torre (PSA010 lead author; sergio.barbosad\@urosario.edu.co), or Claire Whiting (PSA011 lead author; claire.whiting\@princeton.edu).

### Vacancy: Research & Organisational Fellow

The [CONNECT Partnership](https://connect-btss.github.io/) and PSA are recruiting a Research & Organisational Fellow from current graduate students or recent bachelor's graduates in psychology, behavioural science, metascience, or a related field to help us build and improve the infrastructure that supports global, collaborative science.

The Fellow will work closely with the PSA Co-Directors to help organise PSA’s systems, develop documentation and tutorials, and co-create a Massive Open Online Course (MOOC) on big team science.

- **Contract**: \$10,000 CAD (\~\$7,825 USD)
- **Time**: Approximately 150–200 hours over 6–12 months
- **Location**: Remote

Read full details, and apply **by** **25 October** via the [Canvas advert](https://canvas.psysciacc.org/courses/1/discussion_topics/527), or [Slack advert](https://psy-sci-accelerator.slack.com/archives/C7D9CRWCC/p1790950083800569).
Applications will be reviewed on a **rolling basis**, so apply quickly!

### Biljana Gjoneska Appointed Fellow Commissioner

Congratulations to our accelerator [Biljana Gjoneska](https://psy-sci-accelerator.slack.com/team/U0123QS57HS) for being appointed as Fellow Commissioner for the World Health Summit Academic Alliance-Lancet Commission on [Academic Responsibility for Trust in Science and Societal Change](https://www.worldhealthsummit.org/about/whs-academic-alliance/working-group-concepts).

## Opportunities for PSA Members

### The Love Consortium Conference

[Register](https://www.theloveconsortium.org/tlc-events) for **The Love Consortium (TLC) Virtual Conference** on **13 October from 09:00 to 16:00 Eastern Time**.
This year's conference highlights the many dimensions of love, including its connections to morality, religion, compassion, and prejudice as well as the ways culture, race, social class, and age shape our experiences of love and relationships.
In addition to new findings from around the world and a keynote address from TLC Director Sara Algoe, more will be shared about an upcoming [funding opportunity for early career scientists](https://www.theloveconsortium.org/grants) with research proposals on love and social connection.

### Vacancy: SAS User (Many-Analysts Study)

Statistical Analysis System (SAS) user sought to join a many-analysts study focused on computational reproducibility.
Tasks involve running simple analyses in SAS with supplied datasets and research questions.
Commitment to open science is a must.
Analysing data and helping revise the paper comes with authorship opportunity.
Students through full faculty welcome.

Contact John Protzko (Protzko\@gmail.com) for more details.

## PSA Project Updates

### 005 Stereotype Threat

Comments are being collected from co-authors on the final draft for Stage 2.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/6hju9_v1)

### 008 Minimal Groups

The team are currently writing the manuscript.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/5gpr4_v1)

### 009 Gendered Leadership

Congratulations to our accelerators for publishing their paper in the [*Leadership Quarterly*](https://doi.org/10.1016/j.leaqua.2026.101991), an incredible milestone for PSA009!

[Read more in our registered report \>\>](https://docs.google.com/document/d/1eRZmprM3_fyOE8DgPSN0EQaMMOQdYkoP/edit?usp=sharing&ouid=114736564429721617256&rtpof=true&sd=true)

### 010 Social Evaluation

The team have addressed publisher feedback and have requested fresh sets of eyes from their collaborators on the revised Stage 1 Registered Report.

[Read more in our proposal \>\>](https://drive.google.com/file/d/1K6NCI7h68WXbSBQESDxOBq61jnreODF4/view?usp=sharing)

### 011 Emotion Differentiation

PSA 011 has received its acceptance letter.
The team are drafting registered reports.
PSA 011 is **not ready for collaboration enquiries yet, but stay tuned!**

[Read more in our proposal \>\>](https://docs.google.com/document/d/1YybzqaASMx5wQVcf9Y7Ewi7Hjw4cIJmz/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

### 012 Aesthetic Well-being Evaluation

PSA 012 has received its acceptance letter.
The team are drafting registered reports.
PSA 012 is **not ready for collaboration enquiries yet, but stay tuned!**

[Read more in our proposal \>\>](https://docs.google.com/document/d/1KNtN1sl0FuDsdHZI8t2rRcfq2yeORSit/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

### 013 Global Crises

The team want to submit a Registered Report with *Nature Human Behaviour* for the main study.
They will shortly start drafting the Stage 1 Registered Report, and will soon announce a defined timeline for submission.
The aim being to submit by the end of 2026, start of 2027.

PSA 013 is **now open for collaboration enquiries**!
[See full details and express your interest](https://globalcrisesproject.net/collaborate/) in collaborating by **31 October**.

[Read more in our proposal \>\>](https://docs.google.com/document/d/1t63IiQpDhDEMnz3VOaxT6-i-rMuzSNGg/edit?usp=sharing&ouid=103542693559626876995&rtpof=true&sd=true)

### JTF1 Moral Experiences

The team have produced a manuscript.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/jktnv_v2)

### JTF2 Dignity Honor Face

Final edits are being made to the manuscript before it is sent to collaborators for review.

[Read more in our preprint \>\>](https://osf.io/preprints/psyarxiv/9hb8k_v1)

### JTF3 Error Correction

The team are running analyses.

[Read more in our preprint \>\>](https://osf.io/wn4vx/)

## PSA Newsletter Translations

View [translations of this month’s newsletter](https://docs.google.com/document/d/1InZdbZY7W8c1UUWWp22xRyQfKcwfRtd5afMVqr7zqlU/edit?usp=sharing), provided by the Translation & Cultural Diversity Committee (TCDC).
Stay tuned, as the TCDC is working on publishing the translations on the website in the near future for easier access.

## Got news to share?

[Submit content for the PSA newsletter](https://docs.google.com/forms/d/e/1FAIpQLScNpHiaa0uilRMDkAHuSzx_Og6XBZy623-swhNhkObJ91qX9Q/viewform) **by the last day of each month**, to be published **by the 6th of the following month**.
For example, content submitted by 31 January would appear in the February newsletter, published by 6 February.

When advertising time-sensitive activities, please allow enough time after the 6th of each month for PSA members to read the newsletter and take any required action.

We welcome content that is relevant to PSA members and aligns with the [PSA's Core Principles and mission](https://psysciacc.org/about.html) to advance psychological science through collaboration, open science, metascience, inclusivity, reproducibility, and big team science.
Examples include but are not limited to:

- **Opportunities for PSA members** (e.g. jobs, funding, collaboration, training, and professional development).
- **Research, initiatives, events, and resources**.
- **Announcements from affiliated networks, labs, societies, or organisations**.
- **Calls for participation** in research projects, working groups, and other collaborative or big team science initiatives.
- **Achievements of PSA members** (e.g. publications, awards, grants, fellowships, honours, prestigious appointments, promotions, and leadership roles).

For examples of accepted content and how to format your submission, see [previous newsletter issues](https://psysciacc.org/news.html).

## Thank you for reading!

Can you think of ways to improve the newsletter to be more accessible, useful, and relevant?
Fill this anonymous 2–3 minute [survey](https://formr.thedoomlab.online/PSA-newsletter-feedback-survey) to share your feedback.

If you notice an error, outdated content, missing alt text, formatting problem, or anything else that could be improved on the PSA website, newsletter, or other public-facing content, please let us know.
Suggestions for improving the navigation, design, layout, organisation, tagging, and etc. are also very welcome.

The responses to this survey will be reviewed regularly on an ongoing basis.
If you have immediate or urgent feedback, please directly [contact me via Slack](https://psy-sci-accelerator.slack.com/team/U092DUE45GA).

Until next month,

Sara Eftekhari\
PSA Newsletter Coordinator\
Find me on: [Slack](https://psy-sci-accelerator.slack.com/team/U092DUE45GA), [LinkedIn](https://www.linkedin.com/in/sara-eftekhari-787112322/), and [Bluesky](https://bsky.app/profile/sara-eftekhari.bsky.social)

## Get Involved in the PSA

Join us on [Slack](https://join.slack.com/t/psych-sci-accelerator/shared_invite/zt-2xanhh3n8-1IPQMNi6BEvRbOEgCTvDUw), or drop by our Directors’ Office Hours (Friday at 14:00 UTC, [Zoom link](https://ua-edu.zoom.us/my/slewis20)).
