---
title: "PSA007: SPAM-L"
doi: 10.31219/osf.io/q4fjy
contact: 007spaml@gmail.com 
categories:
  - language
  - multi-language
personnel:
  proposers: Erin Buchanan
  pm: Kelly Cuccolo
  methodology: Niels van Berkel
  data: Niels van Berkel
  translation: Aishwarya Iyer
  ethics: Kim Peters
  funding: Neil Lewis Jr.
---

Semantic priming has been studied for nearly fifty years across various experimental manipulations and theoretical frameworks. Critically, the understanding of semantic priming relies on reliable, well-studied stimuli with defined similarity values. In the last twenty years, the publication rates of normed stimuli databases and corpora (i.e., large bodies of text) has exponentially increased. Further, newer computational models of concept representation have been detailed using these databases. Using these newer models, we can define similarity between concepts to create reliable stimuli for study in semantic priming. In this proposal, we outline the need for a database of semantic priming values, particularly in non-English languages. We detail the process for creating a large database of priming values, from which new theories and hypotheses can be examined. Further, we describe the novel outputs that this proposal will support including a framework for determining sample size for studies of this nature.

Buchanan, E. M., Cuccolo, K., Coles, N. A., Heyman, T., Iyer, A., Lewis, N. A., Jr., … Lewis, S. C. (2021, December 7). Measuring the Semantic Priming Effect Across Many Languages. <https://doi.org/10.31219/osf.io/q4fjy>

