---
title: "PSACR001: Loss Gain"
doi: 10.31234/osf.io/m4gpq
categories:
  - covid rapid
  - multi-language
---

The COVID-19 pandemic presents a critical need to identify best practices for communicating health information to the global public. It also provides an opportunity to test theories about risk communication. As part of a larger Psychological Science Accelerator COVID-19 Rapid Project, a global consortium of researchers will experimentally test competing hypotheses regarding the effects of framing messages in terms of losses versus gains. We will examine effects on three primary outcomes: intentions to adhere to policies designed to prevent the spread of COVID-19, opinions about such policies, and the likelihood that participants seek additional policy information. Whereas research on negativity bias and loss aversion predicts that loss-framing will have greater impact, research on encouraging the adoption of protective health behaviour suggests the opposite (i.e., gain-framing will be more persuasive). We will also assess effects on experienced anxiety. Given the potentially low cost and the scalable nature of framing interventions, results could be valuable to health organizations, policymakers, and news sources globally.

Wang, K., Goldenberg, A., Dorison, C., Miller, J. K., PhD, Uusberg, A., Lerner, J. S., … Moshontz, H. (2020, April 17). A global test of brief reappraisal interventions on emotions during the COVID-19 pandemic. <https://doi.org/10.31234/osf.io/m4gpq>

